package com.svc.pokeguessteam.config.seed;

import com.svc.pokeguessteam.model.enums.EvolutionStage;
import com.svc.pokeguessteam.model.enums.PokedexColor;
import com.svc.pokeguessteam.model.enums.PokemonType;

import java.util.List;

public final class Generation3Seed {

    private Generation3Seed() {
    }

    public static List<PokemonSeedEntry> entries() {
        return List.of(
                PokemonSeedEntry.pokemon(252, "Treecko", PokemonType.GRASS, null, 3, PokedexColor.GREEN, 0.5, 5.0, EvolutionStage.BASE, 16, 139),
                PokemonSeedEntry.pokemon(253, "Grovyle", PokemonType.GRASS, null, 3, PokedexColor.GREEN, 0.9, 21.6, EvolutionStage.FIRST_STAGE, 36, 139),
                PokemonSeedEntry.pokemon(254, "Sceptile", PokemonType.GRASS, null, 3, PokedexColor.GREEN, 1.7, 52.2, EvolutionStage.SECOND_STAGE, null, 139),
                PokemonSeedEntry.pokemon(255, "Torchic", PokemonType.FIRE, null, 3, PokedexColor.RED, 0.4, 2.5, EvolutionStage.BASE, 16, 140),
                PokemonSeedEntry.pokemon(256, "Combusken", PokemonType.FIRE, PokemonType.FIGHTING, 3, PokedexColor.RED, 0.9, 19.5, EvolutionStage.FIRST_STAGE, 36, 140),
                PokemonSeedEntry.pokemon(257, "Blaziken", PokemonType.FIRE, PokemonType.FIGHTING, 3, PokedexColor.RED, 1.9, 52.0, EvolutionStage.SECOND_STAGE, null, 140),
                PokemonSeedEntry.pokemon(258, "Mudkip", PokemonType.WATER, null, 3, PokedexColor.BLUE, 0.4, 7.6, EvolutionStage.BASE, 16, 141),
                PokemonSeedEntry.pokemon(259, "Marshtomp", PokemonType.WATER, PokemonType.GROUND, 3, PokedexColor.BLUE, 0.7, 28.0, EvolutionStage.FIRST_STAGE, 36, 141),
                PokemonSeedEntry.pokemon(260, "Swampert", PokemonType.WATER, PokemonType.GROUND, 3, PokedexColor.BLUE, 1.5, 81.9, EvolutionStage.SECOND_STAGE, null, 141),
                PokemonSeedEntry.pokemon(261, "Poochyena", PokemonType.DARK, null, 3, PokedexColor.GRAY, 0.5, 13.6, EvolutionStage.BASE, 18, 142),
                PokemonSeedEntry.pokemon(262, "Mightyena", PokemonType.DARK, null, 3, PokedexColor.GRAY, 1.0, 37.0, EvolutionStage.SECOND_STAGE, null, 142),
                PokemonSeedEntry.pokemon(263, "Zigzagoon", PokemonType.NORMAL, null, 3, PokedexColor.BROWN, 0.4, 17.5, EvolutionStage.BASE, 20, 143),
                PokemonSeedEntry.pokemon(264, "Linoone", PokemonType.NORMAL, null, 3, PokedexColor.WHITE, 0.5, 32.5, EvolutionStage.FIRST_STAGE, 35, 143),
                PokemonSeedEntry.pokemon(265, "Wurmple", PokemonType.BUG, null, 3, PokedexColor.RED, 0.3, 3.6, EvolutionStage.BASE, 7, 144),
                PokemonSeedEntry.pokemon(266, "Silcoon", PokemonType.BUG, null, 3, PokedexColor.WHITE, 0.6, 10.0, EvolutionStage.FIRST_STAGE, 10, 144),
                PokemonSeedEntry.pokemon(267, "Beautifly", PokemonType.BUG, PokemonType.FLYING, 3, PokedexColor.YELLOW, 1.0, 28.4, EvolutionStage.SECOND_STAGE, null, 144),
                PokemonSeedEntry.pokemon(268, "Cascoon", PokemonType.BUG, null, 3, PokedexColor.PURPLE, 0.7, 11.5, EvolutionStage.FIRST_STAGE, 10, 145),
                PokemonSeedEntry.pokemon(269, "Dustox", PokemonType.BUG, PokemonType.POISON, 3, PokedexColor.GREEN, 1.2, 31.6, EvolutionStage.SECOND_STAGE, null, 145),
                PokemonSeedEntry.pokemon(270, "Lotad", PokemonType.WATER, PokemonType.GRASS, 3, PokedexColor.GREEN, 0.5, 2.6, EvolutionStage.BASE, 14, 146),
                PokemonSeedEntry.pokemon(271, "Lombre", PokemonType.WATER, PokemonType.GRASS, 3, PokedexColor.GREEN, 1.2, 32.5, EvolutionStage.FIRST_STAGE, null, 146),
                PokemonSeedEntry.pokemon(272, "Ludicolo", PokemonType.WATER, PokemonType.GRASS, 3, PokedexColor.GREEN, 1.5, 55.0, EvolutionStage.SECOND_STAGE, null, 146),
                PokemonSeedEntry.pokemon(273, "Seedot", PokemonType.GRASS, null, 3, PokedexColor.BROWN, 0.5, 4.0, EvolutionStage.BASE, 14, 147),
                PokemonSeedEntry.pokemon(274, "Nuzleaf", PokemonType.GRASS, PokemonType.DARK, 3, PokedexColor.BROWN, 1.0, 28.0, EvolutionStage.FIRST_STAGE, null, 147),
                PokemonSeedEntry.pokemon(275, "Shiftry", PokemonType.GRASS, PokemonType.DARK, 3, PokedexColor.BROWN, 1.3, 59.6, EvolutionStage.SECOND_STAGE, null, 147),
                PokemonSeedEntry.pokemon(276, "Taillow", PokemonType.NORMAL, PokemonType.FLYING, 3, PokedexColor.BLUE, 0.3, 2.3, EvolutionStage.BASE, 22, 148),
                PokemonSeedEntry.pokemon(277, "Swellow", PokemonType.NORMAL, PokemonType.FLYING, 3, PokedexColor.BLUE, 0.7, 19.8, EvolutionStage.SECOND_STAGE, null, 148),
                PokemonSeedEntry.pokemon(278, "Wingull", PokemonType.WATER, PokemonType.FLYING, 3, PokedexColor.WHITE, 0.6, 9.5, EvolutionStage.BASE, 25, 149),
                PokemonSeedEntry.pokemon(279, "Pelipper", PokemonType.WATER, PokemonType.FLYING, 3, PokedexColor.YELLOW, 1.2, 28.0, EvolutionStage.SECOND_STAGE, null, 149),
                PokemonSeedEntry.pokemon(280, "Ralts", PokemonType.PSYCHIC, PokemonType.FAIRY, 3, PokedexColor.WHITE, 0.4, 6.6, EvolutionStage.BASE, 20, 150),
                PokemonSeedEntry.pokemon(281, "Kirlia", PokemonType.PSYCHIC, PokemonType.FAIRY, 3, PokedexColor.WHITE, 0.8, 20.2, EvolutionStage.FIRST_STAGE, 30, 150),
                PokemonSeedEntry.pokemon(282, "Gardevoir", PokemonType.PSYCHIC, PokemonType.FAIRY, 3, PokedexColor.WHITE, 1.6, 48.4, EvolutionStage.SECOND_STAGE, null, 150),
                PokemonSeedEntry.pokemon(283, "Surskit", PokemonType.BUG, PokemonType.WATER, 3, PokedexColor.BLUE, 0.5, 1.7, EvolutionStage.BASE, 22, 152),
                PokemonSeedEntry.pokemon(284, "Masquerain", PokemonType.BUG, PokemonType.FLYING, 3, PokedexColor.BLUE, 0.8, 3.6, EvolutionStage.SECOND_STAGE, null, 152),
                PokemonSeedEntry.pokemon(285, "Shroomish", PokemonType.GRASS, null, 3, PokedexColor.BROWN, 0.4, 4.5, EvolutionStage.BASE, 23, 153),
                PokemonSeedEntry.pokemon(286, "Breloom", PokemonType.GRASS, PokemonType.FIGHTING, 3, PokedexColor.GREEN, 1.2, 39.2, EvolutionStage.SECOND_STAGE, null, 153),
                PokemonSeedEntry.pokemon(287, "Slakoth", PokemonType.NORMAL, null, 3, PokedexColor.BROWN, 0.8, 24.0, EvolutionStage.BASE, 18, 154),
                PokemonSeedEntry.pokemon(288, "Vigoroth", PokemonType.NORMAL, null, 3, PokedexColor.WHITE, 1.4, 46.5, EvolutionStage.FIRST_STAGE, 36, 154),
                PokemonSeedEntry.pokemon(289, "Slaking", PokemonType.NORMAL, null, 3, PokedexColor.BROWN, 2.0, 130.5, EvolutionStage.SECOND_STAGE, null, 154),
                PokemonSeedEntry.pokemon(290, "Nincada", PokemonType.BUG, PokemonType.GROUND, 3, PokedexColor.GRAY, 0.5, 5.5, EvolutionStage.BASE, 20, 155),
                PokemonSeedEntry.pokemon(291, "Ninjask", PokemonType.BUG, PokemonType.FLYING, 3, PokedexColor.YELLOW, 0.8, 12.0, EvolutionStage.SECOND_STAGE, null, 155),
                PokemonSeedEntry.pokemon(292, "Shedinja", PokemonType.BUG, PokemonType.GHOST, 3, PokedexColor.BROWN, 0.8, 1.2, EvolutionStage.SECOND_STAGE, null, 156),
                PokemonSeedEntry.pokemon(293, "Whismur", PokemonType.NORMAL, null, 3, PokedexColor.PINK, 0.6, 16.3, EvolutionStage.BASE, 20, 157),
                PokemonSeedEntry.pokemon(294, "Loudred", PokemonType.NORMAL, null, 3, PokedexColor.BLUE, 1.0, 40.5, EvolutionStage.FIRST_STAGE, 40, 157),
                PokemonSeedEntry.pokemon(295, "Exploud", PokemonType.NORMAL, null, 3, PokedexColor.BLUE, 1.5, 84.0, EvolutionStage.SECOND_STAGE, null, 157),
                PokemonSeedEntry.pokemon(296, "Makuhita", PokemonType.FIGHTING, null, 3, PokedexColor.YELLOW, 1.0, 86.4, EvolutionStage.BASE, 24, 158),
                PokemonSeedEntry.pokemon(297, "Hariyama", PokemonType.FIGHTING, null, 3, PokedexColor.BROWN, 2.3, 253.8, EvolutionStage.SECOND_STAGE, null, 158),
                PokemonSeedEntry.pokemon(298, "Azurill", PokemonType.NORMAL, PokemonType.FAIRY, 3, PokedexColor.BLUE, 0.2, 2.0, EvolutionStage.BASE, null, 159),
                PokemonSeedEntry.pokemon(299, "Nosepass", PokemonType.ROCK, null, 3, PokedexColor.GRAY, 1.0, 97.0, EvolutionStage.BASE, null, 160),
                PokemonSeedEntry.pokemon(300, "Skitty", PokemonType.NORMAL, null, 3, PokedexColor.PINK, 0.6, 11.0, EvolutionStage.BASE, null, 161),
                PokemonSeedEntry.pokemon(301, "Delcatty", PokemonType.NORMAL, null, 3, PokedexColor.PURPLE, 1.1, 32.6, EvolutionStage.SECOND_STAGE, null, 161),
                PokemonSeedEntry.pokemon(302, "Sableye", PokemonType.DARK, PokemonType.GHOST, 3, PokedexColor.PURPLE, 0.5, 11.0, null, null, 162),
                PokemonSeedEntry.pokemon(303, "Mawile", PokemonType.STEEL, PokemonType.FAIRY, 3, PokedexColor.BLACK, 0.6, 11.5, null, null, 163),
                PokemonSeedEntry.pokemon(304, "Aron", PokemonType.STEEL, PokemonType.ROCK, 3, PokedexColor.GRAY, 0.4, 60.0, EvolutionStage.BASE, 32, 164),
                PokemonSeedEntry.pokemon(305, "Lairon", PokemonType.STEEL, PokemonType.ROCK, 3, PokedexColor.GRAY, 0.9, 120.0, EvolutionStage.FIRST_STAGE, 42, 164),
                PokemonSeedEntry.pokemon(306, "Aggron", PokemonType.STEEL, PokemonType.ROCK, 3, PokedexColor.GRAY, 2.1, 360.0, EvolutionStage.SECOND_STAGE, null, 164),
                PokemonSeedEntry.pokemon(307, "Meditite", PokemonType.FIGHTING, PokemonType.PSYCHIC, 3, PokedexColor.BLUE, 0.6, 11.2, EvolutionStage.BASE, 37, 165),
                PokemonSeedEntry.pokemon(308, "Medicham", PokemonType.FIGHTING, PokemonType.PSYCHIC, 3, PokedexColor.RED, 1.3, 31.5, EvolutionStage.SECOND_STAGE, null, 165),
                PokemonSeedEntry.pokemon(309, "Electrike", PokemonType.ELECTRIC, null, 3, PokedexColor.GREEN, 0.6, 15.2, EvolutionStage.BASE, 26, 166),
                PokemonSeedEntry.pokemon(310, "Manectric", PokemonType.ELECTRIC, null, 3, PokedexColor.YELLOW, 1.5, 40.2, EvolutionStage.SECOND_STAGE, null, 166),
                PokemonSeedEntry.pokemon(311, "Plusle", PokemonType.ELECTRIC, null, 3, PokedexColor.YELLOW, 0.4, 4.2, null, null, 167),
                PokemonSeedEntry.pokemon(312, "Minun", PokemonType.ELECTRIC, null, 3, PokedexColor.YELLOW, 0.4, 4.2, null, null, 168),
                PokemonSeedEntry.pokemon(313, "Volbeat", PokemonType.BUG, null, 3, PokedexColor.GRAY, 0.7, 17.7, null, null, 169),
                PokemonSeedEntry.pokemon(314, "Illumise", PokemonType.BUG, null, 3, PokedexColor.PURPLE, 0.6, 17.7, null, null, 170),
                PokemonSeedEntry.pokemon(315, "Roselia", PokemonType.GRASS, PokemonType.POISON, 3, PokedexColor.GREEN, 0.3, 2.0, EvolutionStage.FIRST_STAGE, null, 224),
                PokemonSeedEntry.pokemon(316, "Gulpin", PokemonType.POISON, null, 3, PokedexColor.GREEN, 0.4, 10.3, EvolutionStage.BASE, 26, 171),
                PokemonSeedEntry.pokemon(317, "Swalot", PokemonType.POISON, null, 3, PokedexColor.PURPLE, 1.7, 80.0, EvolutionStage.SECOND_STAGE, null, 171),
                PokemonSeedEntry.pokemon(318, "Carvanha", PokemonType.WATER, PokemonType.DARK, 3, PokedexColor.RED, 0.8, 20.8, EvolutionStage.BASE, 30, 172),
                PokemonSeedEntry.pokemon(319, "Sharpedo", PokemonType.WATER, PokemonType.DARK, 3, PokedexColor.BLUE, 1.8, 88.8, EvolutionStage.SECOND_STAGE, null, 172),
                PokemonSeedEntry.pokemon(320, "Wailmer", PokemonType.WATER, null, 3, PokedexColor.BLUE, 2.0, 130.0, EvolutionStage.BASE, 40, 173),
                PokemonSeedEntry.pokemon(321, "Wailord", PokemonType.WATER, null, 3, PokedexColor.BLUE, 14.5, 398.0, EvolutionStage.SECOND_STAGE, null, 173),
                PokemonSeedEntry.pokemon(322, "Numel", PokemonType.FIRE, PokemonType.GROUND, 3, PokedexColor.YELLOW, 0.7, 24.0, EvolutionStage.BASE, 33, 174),
                PokemonSeedEntry.pokemon(323, "Camerupt", PokemonType.FIRE, PokemonType.GROUND, 3, PokedexColor.RED, 1.9, 220.0, EvolutionStage.SECOND_STAGE, null, 174),
                PokemonSeedEntry.pokemon(324, "Torkoal", PokemonType.FIRE, null, 3, PokedexColor.BROWN, 0.5, 80.4, null, null, 175),
                PokemonSeedEntry.pokemon(325, "Spoink", PokemonType.PSYCHIC, null, 3, PokedexColor.BLACK, 0.7, 30.6, EvolutionStage.BASE, 32, 176),
                PokemonSeedEntry.pokemon(326, "Grumpig", PokemonType.PSYCHIC, null, 3, PokedexColor.PURPLE, 0.9, 71.5, EvolutionStage.SECOND_STAGE, null, 176),
                PokemonSeedEntry.pokemon(327, "Spinda", PokemonType.NORMAL, null, 3, PokedexColor.BROWN, 1.1, 5.0, null, null, 177),
                PokemonSeedEntry.pokemon(328, "Trapinch", PokemonType.GROUND, null, 3, PokedexColor.BROWN, 0.7, 15.0, EvolutionStage.BASE, 35, 178),
                PokemonSeedEntry.pokemon(329, "Vibrava", PokemonType.GROUND, PokemonType.DRAGON, 3, PokedexColor.GREEN, 1.1, 15.3, EvolutionStage.FIRST_STAGE, 45, 178),
                PokemonSeedEntry.pokemon(330, "Flygon", PokemonType.GROUND, PokemonType.DRAGON, 3, PokedexColor.GREEN, 2.0, 82.0, EvolutionStage.SECOND_STAGE, null, 178),
                PokemonSeedEntry.pokemon(331, "Cacnea", PokemonType.GRASS, null, 3, PokedexColor.GREEN, 0.4, 51.3, EvolutionStage.BASE, 32, 179),
                PokemonSeedEntry.pokemon(332, "Cacturne", PokemonType.GRASS, PokemonType.DARK, 3, PokedexColor.GREEN, 1.3, 77.4, EvolutionStage.SECOND_STAGE, null, 179),
                PokemonSeedEntry.pokemon(333, "Swablu", PokemonType.NORMAL, PokemonType.FLYING, 3, PokedexColor.BLUE, 0.4, 1.2, EvolutionStage.BASE, 35, 180),
                PokemonSeedEntry.pokemon(334, "Altaria", PokemonType.DRAGON, PokemonType.FLYING, 3, PokedexColor.BLUE, 1.1, 20.6, EvolutionStage.SECOND_STAGE, null, 180),
                PokemonSeedEntry.pokemon(335, "Zangoose", PokemonType.NORMAL, null, 3, PokedexColor.WHITE, 1.3, 40.3, null, null, 181),
                PokemonSeedEntry.pokemon(336, "Seviper", PokemonType.POISON, null, 3, PokedexColor.BLACK, 2.7, 52.5, null, null, 182),
                PokemonSeedEntry.pokemon(337, "Lunatone", PokemonType.ROCK, PokemonType.PSYCHIC, 3, PokedexColor.YELLOW, 1.0, 168.0, null, null, 183),
                PokemonSeedEntry.pokemon(338, "Solrock", PokemonType.ROCK, PokemonType.PSYCHIC, 3, PokedexColor.RED, 1.2, 154.0, null, null, 184),
                PokemonSeedEntry.pokemon(339, "Barboach", PokemonType.WATER, PokemonType.GROUND, 3, PokedexColor.GRAY, 0.4, 1.9, EvolutionStage.BASE, 30, 185),
                PokemonSeedEntry.pokemon(340, "Whiscash", PokemonType.WATER, PokemonType.GROUND, 3, PokedexColor.BLUE, 0.9, 23.6, EvolutionStage.SECOND_STAGE, null, 185),
                PokemonSeedEntry.pokemon(341, "Corphish", PokemonType.WATER, null, 3, PokedexColor.RED, 0.6, 11.5, EvolutionStage.BASE, 30, 186),
                PokemonSeedEntry.pokemon(342, "Crawdaunt", PokemonType.WATER, PokemonType.DARK, 3, PokedexColor.RED, 1.1, 32.8, EvolutionStage.SECOND_STAGE, null, 186),
                PokemonSeedEntry.pokemon(343, "Baltoy", PokemonType.GROUND, PokemonType.PSYCHIC, 3, PokedexColor.BROWN, 0.5, 21.5, EvolutionStage.BASE, 36, 187),
                PokemonSeedEntry.pokemon(344, "Claydol", PokemonType.GROUND, PokemonType.PSYCHIC, 3, PokedexColor.BLACK, 1.5, 108.0, EvolutionStage.SECOND_STAGE, null, 187),
                PokemonSeedEntry.pokemon(345, "Lileep", PokemonType.ROCK, PokemonType.GRASS, 3, PokedexColor.PURPLE, 1.0, 23.8, EvolutionStage.BASE, 40, 188),
                PokemonSeedEntry.pokemon(346, "Cradily", PokemonType.ROCK, PokemonType.GRASS, 3, PokedexColor.GREEN, 1.5, 60.4, EvolutionStage.SECOND_STAGE, null, 188),
                PokemonSeedEntry.pokemon(347, "Anorith", PokemonType.ROCK, PokemonType.BUG, 3, PokedexColor.GRAY, 0.7, 12.5, EvolutionStage.BASE, 40, 189),
                PokemonSeedEntry.pokemon(348, "Armaldo", PokemonType.ROCK, PokemonType.BUG, 3, PokedexColor.GRAY, 1.5, 68.2, EvolutionStage.SECOND_STAGE, null, 189),
                PokemonSeedEntry.pokemon(349, "Feebas", PokemonType.WATER, null, 3, PokedexColor.BROWN, 0.6, 7.4, EvolutionStage.BASE, null, 190),
                PokemonSeedEntry.pokemon(350, "Milotic", PokemonType.WATER, null, 3, PokedexColor.PINK, 6.2, 162.0, EvolutionStage.SECOND_STAGE, null, 190),
                PokemonSeedEntry.pokemon(351, "Castform", PokemonType.NORMAL, null, 3, PokedexColor.GRAY, 0.3, 0.8, null, null, 191),
                PokemonSeedEntry.pokemon(352, "Kecleon", PokemonType.NORMAL, null, 3, PokedexColor.GREEN, 1.0, 22.0, null, null, 192),
                PokemonSeedEntry.pokemon(353, "Shuppet", PokemonType.GHOST, null, 3, PokedexColor.BLACK, 0.6, 2.3, EvolutionStage.BASE, 37, 193),
                PokemonSeedEntry.pokemon(354, "Banette", PokemonType.GHOST, null, 3, PokedexColor.BLACK, 1.1, 12.5, EvolutionStage.SECOND_STAGE, null, 193),
                PokemonSeedEntry.pokemon(355, "Duskull", PokemonType.GHOST, null, 3, PokedexColor.BLACK, 0.8, 15.0, EvolutionStage.BASE, 37, 194),
                PokemonSeedEntry.pokemon(356, "Dusclops", PokemonType.GHOST, null, 3, PokedexColor.BLACK, 1.6, 30.6, EvolutionStage.FIRST_STAGE, null, 194),
                PokemonSeedEntry.pokemon(357, "Tropius", PokemonType.GRASS, PokemonType.FLYING, 3, PokedexColor.GREEN, 2.0, 100.0, null, null, 195),
                PokemonSeedEntry.pokemon(358, "Chimecho", PokemonType.PSYCHIC, null, 3, PokedexColor.BLUE, 0.6, 1.0, EvolutionStage.SECOND_STAGE, null, 237),
                PokemonSeedEntry.pokemon(359, "Absol", PokemonType.DARK, null, 3, PokedexColor.WHITE, 1.2, 47.0, null, null, 196),
                PokemonSeedEntry.pokemon(360, "Wynaut", PokemonType.PSYCHIC, null, 3, PokedexColor.BLUE, 0.6, 14.0, EvolutionStage.BASE, 15, 197),
                PokemonSeedEntry.pokemon(361, "Snorunt", PokemonType.ICE, null, 3, PokedexColor.GRAY, 0.7, 16.8, EvolutionStage.BASE, 42, 198),
                PokemonSeedEntry.pokemon(362, "Glalie", PokemonType.ICE, null, 3, PokedexColor.GRAY, 1.5, 256.5, EvolutionStage.SECOND_STAGE, null, 198),
                PokemonSeedEntry.pokemon(363, "Spheal", PokemonType.ICE, PokemonType.WATER, 3, PokedexColor.BLUE, 0.8, 39.5, EvolutionStage.BASE, 32, 200),
                PokemonSeedEntry.pokemon(364, "Sealeo", PokemonType.ICE, PokemonType.WATER, 3, PokedexColor.BLUE, 1.1, 87.6, EvolutionStage.FIRST_STAGE, 44, 200),
                PokemonSeedEntry.pokemon(365, "Walrein", PokemonType.ICE, PokemonType.WATER, 3, PokedexColor.BLUE, 1.4, 150.6, EvolutionStage.SECOND_STAGE, null, 200),
                PokemonSeedEntry.pokemon(366, "Clamperl", PokemonType.WATER, null, 3, PokedexColor.BLUE, 0.4, 52.5, EvolutionStage.BASE, null, 201),
                PokemonSeedEntry.pokemon(367, "Huntail", PokemonType.WATER, null, 3, PokedexColor.BLUE, 1.7, 27.0, EvolutionStage.SECOND_STAGE, null, 201),
                PokemonSeedEntry.pokemon(368, "Gorebyss", PokemonType.WATER, null, 3, PokedexColor.PINK, 1.8, 22.6, EvolutionStage.SECOND_STAGE, null, 202),
                PokemonSeedEntry.pokemon(369, "Relicanth", PokemonType.WATER, PokemonType.ROCK, 3, PokedexColor.GRAY, 1.0, 23.4, null, null, 203),
                PokemonSeedEntry.pokemon(370, "Luvdisc", PokemonType.WATER, null, 3, PokedexColor.PINK, 0.6, 8.7, null, null, 204),
                PokemonSeedEntry.pokemon(371, "Bagon", PokemonType.DRAGON, null, 3, PokedexColor.BLUE, 0.6, 42.1, EvolutionStage.BASE, 30, 205),
                PokemonSeedEntry.pokemon(372, "Shelgon", PokemonType.DRAGON, null, 3, PokedexColor.WHITE, 1.1, 110.5, EvolutionStage.FIRST_STAGE, 50, 205),
                PokemonSeedEntry.pokemon(373, "Salamence", PokemonType.DRAGON, PokemonType.FLYING, 3, PokedexColor.BLUE, 1.5, 102.6, EvolutionStage.SECOND_STAGE, null, 205),
                PokemonSeedEntry.pokemon(374, "Beldum", PokemonType.STEEL, PokemonType.PSYCHIC, 3, PokedexColor.BLUE, 0.6, 95.2, EvolutionStage.BASE, 20, 206),
                PokemonSeedEntry.pokemon(375, "Metang", PokemonType.STEEL, PokemonType.PSYCHIC, 3, PokedexColor.BLUE, 1.2, 202.5, EvolutionStage.FIRST_STAGE, 45, 206),
                PokemonSeedEntry.pokemon(376, "Metagross", PokemonType.STEEL, PokemonType.PSYCHIC, 3, PokedexColor.BLUE, 1.6, 550.0, EvolutionStage.SECOND_STAGE, null, 206),
                PokemonSeedEntry.pokemon(377, "Regirock", PokemonType.ROCK, null, 3, PokedexColor.BROWN, 1.7, 230.0, null, null, 207),
                PokemonSeedEntry.pokemon(378, "Regice", PokemonType.ICE, null, 3, PokedexColor.BLUE, 1.8, 175.0, null, null, 208),
                PokemonSeedEntry.pokemon(379, "Registeel", PokemonType.STEEL, null, 3, PokedexColor.GRAY, 1.9, 205.0, null, null, 209),
                PokemonSeedEntry.pokemon(380, "Latias", PokemonType.DRAGON, PokemonType.PSYCHIC, 3, PokedexColor.RED, 1.4, 40.0, null, null, 210),
                PokemonSeedEntry.pokemon(381, "Latios", PokemonType.DRAGON, PokemonType.PSYCHIC, 3, PokedexColor.BLUE, 2.0, 60.0, null, null, 211),
                PokemonSeedEntry.pokemon(382, "Kyogre", PokemonType.WATER, null, 3, PokedexColor.BLUE, 4.5, 352.0, null, null, 212),
                PokemonSeedEntry.pokemon(383, "Groudon", PokemonType.GROUND, null, 3, PokedexColor.RED, 3.5, 950.0, null, null, 213),
                PokemonSeedEntry.pokemon(384, "Rayquaza", PokemonType.DRAGON, PokemonType.FLYING, 3, PokedexColor.GREEN, 7.0, 206.5, null, null, 214),
                PokemonSeedEntry.pokemon(385, "Jirachi", PokemonType.STEEL, PokemonType.PSYCHIC, 3, PokedexColor.YELLOW, 0.3, 1.1, null, null, 215),
                PokemonSeedEntry.pokemon(386, "Deoxys", PokemonType.PSYCHIC, null, 3, PokedexColor.RED, 1.7, 60.8, null, null, 216)
        );
    }
}
