package com.svc.pokeguessteam.config.seed;

import com.svc.pokeguessteam.model.enums.EvolutionStage;
import com.svc.pokeguessteam.model.enums.PokedexColor;
import com.svc.pokeguessteam.model.enums.PokemonType;

import java.util.List;

public final class Generation9Seed {

    private Generation9Seed() {
    }

    public static List<PokemonSeedEntry> entries() {
        return List.of(
                PokemonSeedEntry.pokemon(906, "Sprigatito", PokemonType.GRASS, null, 9, PokedexColor.GREEN, 0.4, 4.1, EvolutionStage.BASE, 16, 496),
                PokemonSeedEntry.pokemon(907, "Floragato", PokemonType.GRASS, null, 9, PokedexColor.GREEN, 0.9, 12.2, EvolutionStage.FIRST_STAGE, 36, 496),
                PokemonSeedEntry.pokemon(908, "Meowscarada", PokemonType.GRASS, PokemonType.DARK, 9, PokedexColor.GREEN, 1.5, 31.2, EvolutionStage.SECOND_STAGE, null, 496),
                PokemonSeedEntry.pokemon(909, "Fuecoco", PokemonType.FIRE, null, 9, PokedexColor.RED, 0.4, 9.8, EvolutionStage.BASE, 16, 497),
                PokemonSeedEntry.pokemon(910, "Crocalor", PokemonType.FIRE, null, 9, PokedexColor.RED, 1.0, 30.7, EvolutionStage.FIRST_STAGE, 36, 497),
                PokemonSeedEntry.pokemon(911, "Skeledirge", PokemonType.FIRE, PokemonType.GHOST, 9, PokedexColor.RED, 1.6, 326.5, EvolutionStage.SECOND_STAGE, null, 497),
                PokemonSeedEntry.pokemon(912, "Quaxly", PokemonType.WATER, null, 9, PokedexColor.WHITE, 0.5, 6.1, EvolutionStage.BASE, 16, 498),
                PokemonSeedEntry.pokemon(913, "Quaxwell", PokemonType.WATER, null, 9, PokedexColor.BLUE, 1.2, 21.5, EvolutionStage.FIRST_STAGE, 36, 498),
                PokemonSeedEntry.pokemon(914, "Quaquaval", PokemonType.WATER, PokemonType.FIGHTING, 9, PokedexColor.BLUE, 1.8, 61.9, EvolutionStage.SECOND_STAGE, null, 498),
                PokemonSeedEntry.pokemon(915, "Lechonk", PokemonType.NORMAL, null, 9, PokedexColor.GRAY, 0.5, 10.2, EvolutionStage.BASE, 18, 499),
                PokemonSeedEntry.pokemon(916, "Oinkologne", PokemonType.NORMAL, null, 9, PokedexColor.GRAY, 1.0, 120.0, EvolutionStage.SECOND_STAGE, null, 499),
                PokemonSeedEntry.pokemon(917, "Tarountula", PokemonType.BUG, null, 9, PokedexColor.WHITE, 0.3, 4.0, EvolutionStage.BASE, 15, 500),
                PokemonSeedEntry.pokemon(918, "Spidops", PokemonType.BUG, null, 9, PokedexColor.GREEN, 1.0, 16.5, EvolutionStage.SECOND_STAGE, null, 500),
                PokemonSeedEntry.pokemon(919, "Nymble", PokemonType.BUG, null, 9, PokedexColor.GRAY, 0.2, 1.0, EvolutionStage.BASE, 24, 501),
                PokemonSeedEntry.pokemon(920, "Lokix", PokemonType.BUG, PokemonType.DARK, 9, PokedexColor.GRAY, 1.0, 17.5, EvolutionStage.SECOND_STAGE, null, 501),
                PokemonSeedEntry.pokemon(921, "Pawmi", PokemonType.ELECTRIC, null, 9, PokedexColor.YELLOW, 0.3, 2.5, EvolutionStage.BASE, 18, 502),
                PokemonSeedEntry.pokemon(922, "Pawmo", PokemonType.ELECTRIC, PokemonType.FIGHTING, 9, PokedexColor.YELLOW, 0.4, 6.5, EvolutionStage.FIRST_STAGE, null, 502),
                PokemonSeedEntry.pokemon(923, "Pawmot", PokemonType.ELECTRIC, PokemonType.FIGHTING, 9, PokedexColor.YELLOW, 0.9, 41.0, EvolutionStage.SECOND_STAGE, null, 502),
                PokemonSeedEntry.pokemon(924, "Tandemaus", PokemonType.NORMAL, null, 9, PokedexColor.WHITE, 0.3, 1.8, EvolutionStage.BASE, 25, 503),
                PokemonSeedEntry.pokemon(925, "Maushold", PokemonType.NORMAL, null, 9, PokedexColor.WHITE, 0.3, 2.3, EvolutionStage.SECOND_STAGE, null, 503),
                PokemonSeedEntry.pokemon(926, "Fidough", PokemonType.FAIRY, null, 9, PokedexColor.YELLOW, 0.3, 10.9, EvolutionStage.BASE, 26, 504),
                PokemonSeedEntry.pokemon(927, "Dachsbun", PokemonType.FAIRY, null, 9, PokedexColor.BROWN, 0.5, 14.9, EvolutionStage.SECOND_STAGE, null, 504),
                PokemonSeedEntry.pokemon(928, "Smoliv", PokemonType.GRASS, PokemonType.NORMAL, 9, PokedexColor.GREEN, 0.3, 6.5, EvolutionStage.BASE, 25, 505),
                PokemonSeedEntry.pokemon(929, "Dolliv", PokemonType.GRASS, PokemonType.NORMAL, 9, PokedexColor.GREEN, 0.6, 11.9, EvolutionStage.FIRST_STAGE, 35, 505),
                PokemonSeedEntry.pokemon(930, "Arboliva", PokemonType.GRASS, PokemonType.NORMAL, 9, PokedexColor.GREEN, 1.4, 48.2, EvolutionStage.SECOND_STAGE, null, 505),
                PokemonSeedEntry.pokemon(931, "Squawkabilly", PokemonType.NORMAL, PokemonType.FLYING, 9, PokedexColor.GREEN, 0.6, 2.4, null, null, 506),
                PokemonSeedEntry.pokemon(932, "Nacli", PokemonType.ROCK, null, 9, PokedexColor.BROWN, 0.4, 16.0, EvolutionStage.BASE, 24, 507),
                PokemonSeedEntry.pokemon(933, "Naclstack", PokemonType.ROCK, null, 9, PokedexColor.BROWN, 0.6, 105.0, EvolutionStage.FIRST_STAGE, 38, 507),
                PokemonSeedEntry.pokemon(934, "Garganacl", PokemonType.ROCK, null, 9, PokedexColor.BROWN, 2.3, 240.0, EvolutionStage.SECOND_STAGE, null, 507),
                PokemonSeedEntry.pokemon(935, "Charcadet", PokemonType.FIRE, null, 9, PokedexColor.RED, 0.6, 10.5, EvolutionStage.BASE, null, 508),
                PokemonSeedEntry.pokemon(936, "Armarouge", PokemonType.FIRE, PokemonType.PSYCHIC, 9, PokedexColor.RED, 1.5, 85.0, EvolutionStage.SECOND_STAGE, null, 508),
                PokemonSeedEntry.pokemon(937, "Ceruledge", PokemonType.FIRE, PokemonType.GHOST, 9, PokedexColor.BLUE, 1.6, 62.0, EvolutionStage.SECOND_STAGE, null, 509),
                PokemonSeedEntry.pokemon(938, "Tadbulb", PokemonType.ELECTRIC, null, 9, PokedexColor.YELLOW, 0.3, 0.4, EvolutionStage.BASE, null, 510),
                PokemonSeedEntry.pokemon(939, "Bellibolt", PokemonType.ELECTRIC, null, 9, PokedexColor.GREEN, 1.2, 113.0, EvolutionStage.SECOND_STAGE, null, 510),
                PokemonSeedEntry.pokemon(940, "Wattrel", PokemonType.ELECTRIC, PokemonType.FLYING, 9, PokedexColor.BLACK, 0.4, 3.6, EvolutionStage.BASE, 25, 511),
                PokemonSeedEntry.pokemon(941, "Kilowattrel", PokemonType.ELECTRIC, PokemonType.FLYING, 9, PokedexColor.YELLOW, 1.4, 38.6, EvolutionStage.SECOND_STAGE, null, 511),
                PokemonSeedEntry.pokemon(942, "Maschiff", PokemonType.DARK, null, 9, PokedexColor.BROWN, 0.5, 16.0, EvolutionStage.BASE, 30, 512),
                PokemonSeedEntry.pokemon(943, "Mabosstiff", PokemonType.DARK, null, 9, PokedexColor.GRAY, 1.1, 61.0, EvolutionStage.SECOND_STAGE, null, 512),
                PokemonSeedEntry.pokemon(944, "Shroodle", PokemonType.POISON, PokemonType.NORMAL, 9, PokedexColor.GRAY, 0.2, 0.7, EvolutionStage.BASE, 28, 513),
                PokemonSeedEntry.pokemon(945, "Grafaiai", PokemonType.POISON, PokemonType.NORMAL, 9, PokedexColor.GRAY, 0.7, 27.2, EvolutionStage.SECOND_STAGE, null, 513),
                PokemonSeedEntry.pokemon(946, "Bramblin", PokemonType.GRASS, PokemonType.GHOST, 9, PokedexColor.BROWN, 0.6, 0.6, EvolutionStage.BASE, null, 514),
                PokemonSeedEntry.pokemon(947, "Brambleghast", PokemonType.GRASS, PokemonType.GHOST, 9, PokedexColor.BROWN, 1.2, 6.0, EvolutionStage.SECOND_STAGE, null, 514),
                PokemonSeedEntry.pokemon(948, "Toedscool", PokemonType.GROUND, PokemonType.GRASS, 9, PokedexColor.YELLOW, 0.9, 33.0, EvolutionStage.BASE, 30, 515),
                PokemonSeedEntry.pokemon(949, "Toedscruel", PokemonType.GROUND, PokemonType.GRASS, 9, PokedexColor.BLACK, 1.9, 58.0, EvolutionStage.SECOND_STAGE, null, 515),
                PokemonSeedEntry.pokemon(950, "Klawf", PokemonType.ROCK, null, 9, PokedexColor.RED, 1.3, 79.0, null, null, 516),
                PokemonSeedEntry.pokemon(951, "Capsakid", PokemonType.GRASS, null, 9, PokedexColor.GREEN, 0.3, 3.0, EvolutionStage.BASE, null, 517),
                PokemonSeedEntry.pokemon(952, "Scovillain", PokemonType.GRASS, PokemonType.FIRE, 9, PokedexColor.GREEN, 0.9, 15.0, EvolutionStage.SECOND_STAGE, null, 517),
                PokemonSeedEntry.pokemon(953, "Rellor", PokemonType.BUG, null, 9, PokedexColor.BROWN, 0.2, 1.0, EvolutionStage.BASE, null, 518),
                PokemonSeedEntry.pokemon(954, "Rabsca", PokemonType.BUG, PokemonType.PSYCHIC, 9, PokedexColor.GREEN, 0.3, 3.5, EvolutionStage.SECOND_STAGE, null, 518),
                PokemonSeedEntry.pokemon(955, "Flittle", PokemonType.PSYCHIC, null, 9, PokedexColor.YELLOW, 0.2, 1.5, EvolutionStage.BASE, 35, 519),
                PokemonSeedEntry.pokemon(956, "Espathra", PokemonType.PSYCHIC, null, 9, PokedexColor.YELLOW, 1.9, 90.0, EvolutionStage.SECOND_STAGE, null, 519),
                PokemonSeedEntry.pokemon(957, "Tinkatink", PokemonType.FAIRY, PokemonType.STEEL, 9, PokedexColor.PINK, 0.4, 8.9, EvolutionStage.BASE, 24, 520),
                PokemonSeedEntry.pokemon(958, "Tinkatuff", PokemonType.FAIRY, PokemonType.STEEL, 9, PokedexColor.PINK, 0.7, 59.1, EvolutionStage.FIRST_STAGE, 38, 520),
                PokemonSeedEntry.pokemon(959, "Tinkaton", PokemonType.FAIRY, PokemonType.STEEL, 9, PokedexColor.PINK, 0.7, 112.8, EvolutionStage.SECOND_STAGE, null, 520),
                PokemonSeedEntry.pokemon(960, "Wiglett", PokemonType.WATER, null, 9, PokedexColor.WHITE, 1.2, 1.8, EvolutionStage.BASE, 26, 521),
                PokemonSeedEntry.pokemon(961, "Wugtrio", PokemonType.WATER, null, 9, PokedexColor.RED, 1.2, 5.4, EvolutionStage.SECOND_STAGE, null, 521),
                PokemonSeedEntry.pokemon(962, "Bombirdier", PokemonType.FLYING, PokemonType.DARK, 9, PokedexColor.WHITE, 1.5, 42.9, null, null, 522),
                PokemonSeedEntry.pokemon(963, "Finizen", PokemonType.WATER, null, 9, PokedexColor.BLUE, 1.3, 60.2, EvolutionStage.BASE, 38, 523),
                PokemonSeedEntry.pokemon(964, "Palafin", PokemonType.WATER, null, 9, PokedexColor.BLUE, 1.3, 60.2, EvolutionStage.SECOND_STAGE, null, 523),
                PokemonSeedEntry.pokemon(965, "Varoom", PokemonType.STEEL, PokemonType.POISON, 9, PokedexColor.GRAY, 1.0, 35.0, EvolutionStage.BASE, 40, 524),
                PokemonSeedEntry.pokemon(966, "Revavroom", PokemonType.STEEL, PokemonType.POISON, 9, PokedexColor.GRAY, 1.8, 120.0, EvolutionStage.SECOND_STAGE, null, 524),
                PokemonSeedEntry.pokemon(967, "Cyclizar", PokemonType.DRAGON, PokemonType.NORMAL, 9, PokedexColor.GREEN, 1.6, 63.0, null, null, 525),
                PokemonSeedEntry.pokemon(968, "Orthworm", PokemonType.STEEL, null, 9, PokedexColor.PINK, 2.5, 310.0, null, null, 526),
                PokemonSeedEntry.pokemon(969, "Glimmet", PokemonType.ROCK, PokemonType.POISON, 9, PokedexColor.BLUE, 0.7, 8.0, EvolutionStage.BASE, 35, 527),
                PokemonSeedEntry.pokemon(970, "Glimmora", PokemonType.ROCK, PokemonType.POISON, 9, PokedexColor.BLUE, 1.5, 45.0, EvolutionStage.SECOND_STAGE, null, 527),
                PokemonSeedEntry.pokemon(971, "Greavard", PokemonType.GHOST, null, 9, PokedexColor.WHITE, 0.6, 35.0, EvolutionStage.BASE, 30, 528),
                PokemonSeedEntry.pokemon(972, "Houndstone", PokemonType.GHOST, null, 9, PokedexColor.WHITE, 2.0, 15.0, EvolutionStage.SECOND_STAGE, null, 528),
                PokemonSeedEntry.pokemon(973, "Flamigo", PokemonType.FLYING, PokemonType.FIGHTING, 9, PokedexColor.PINK, 1.6, 37.0, null, null, 529),
                PokemonSeedEntry.pokemon(974, "Cetoddle", PokemonType.ICE, null, 9, PokedexColor.WHITE, 1.2, 45.0, EvolutionStage.BASE, null, 530),
                PokemonSeedEntry.pokemon(975, "Cetitan", PokemonType.ICE, null, 9, PokedexColor.WHITE, 4.5, 700.0, EvolutionStage.SECOND_STAGE, null, 530),
                PokemonSeedEntry.pokemon(976, "Veluza", PokemonType.WATER, PokemonType.PSYCHIC, 9, PokedexColor.GRAY, 2.5, 90.0, null, null, 531),
                PokemonSeedEntry.pokemon(977, "Dondozo", PokemonType.WATER, null, 9, PokedexColor.BLUE, 12.0, 220.0, null, null, 532),
                PokemonSeedEntry.pokemon(978, "Tatsugiri", PokemonType.DRAGON, PokemonType.WATER, 9, PokedexColor.PINK, 0.3, 8.0, null, null, 533),
                PokemonSeedEntry.pokemon(979, "Annihilape", PokemonType.FIGHTING, PokemonType.GHOST, 9, PokedexColor.GRAY, 1.2, 56.0, EvolutionStage.SECOND_STAGE, null, 23),
                PokemonSeedEntry.pokemon(980, "Clodsire", PokemonType.POISON, PokemonType.GROUND, 9, PokedexColor.BROWN, 1.8, 223.0, EvolutionStage.SECOND_STAGE, null, 100),
                PokemonSeedEntry.pokemon(981, "Farigiraf", PokemonType.NORMAL, PokemonType.PSYCHIC, 9, PokedexColor.BROWN, 3.2, 160.0, EvolutionStage.SECOND_STAGE, null, 104),
                PokemonSeedEntry.pokemon(982, "Dudunsparce", PokemonType.NORMAL, null, 9, PokedexColor.YELLOW, 3.6, 39.2, EvolutionStage.SECOND_STAGE, null, 106),
                PokemonSeedEntry.pokemon(983, "Kingambit", PokemonType.DARK, PokemonType.STEEL, 9, PokedexColor.BLACK, 2.0, 120.0, EvolutionStage.SECOND_STAGE, null, 332),
                PokemonSeedEntry.pokemon(984, "Great Tusk", PokemonType.GROUND, PokemonType.FIGHTING, 9, PokedexColor.PURPLE, 2.2, 320.0, null, null, 534),
                PokemonSeedEntry.pokemon(985, "Scream Tail", PokemonType.FAIRY, PokemonType.PSYCHIC, 9, PokedexColor.PINK, 1.2, 8.0, null, null, 535),
                PokemonSeedEntry.pokemon(986, "Brute Bonnet", PokemonType.GRASS, PokemonType.DARK, 9, PokedexColor.GRAY, 1.2, 21.0, null, null, 536),
                PokemonSeedEntry.pokemon(987, "Flutter Mane", PokemonType.GHOST, PokemonType.FAIRY, 9, PokedexColor.GRAY, 1.4, 4.0, null, null, 537),
                PokemonSeedEntry.pokemon(988, "Slither Wing", PokemonType.BUG, PokemonType.FIGHTING, 9, PokedexColor.RED, 3.2, 92.0, null, null, 538),
                PokemonSeedEntry.pokemon(989, "Sandy Shocks", PokemonType.ELECTRIC, PokemonType.GROUND, 9, PokedexColor.GRAY, 2.3, 60.0, null, null, 539),
                PokemonSeedEntry.pokemon(990, "Iron Treads", PokemonType.GROUND, PokemonType.STEEL, 9, PokedexColor.GRAY, 0.9, 240.0, null, null, 540),
                PokemonSeedEntry.pokemon(991, "Iron Bundle", PokemonType.ICE, PokemonType.WATER, 9, PokedexColor.RED, 0.6, 11.0, null, null, 541),
                PokemonSeedEntry.pokemon(992, "Iron Hands", PokemonType.FIGHTING, PokemonType.ELECTRIC, 9, PokedexColor.GRAY, 1.8, 380.7, null, null, 542),
                PokemonSeedEntry.pokemon(993, "Iron Jugulis", PokemonType.DARK, PokemonType.FLYING, 9, PokedexColor.BLUE, 1.3, 111.0, null, null, 543),
                PokemonSeedEntry.pokemon(994, "Iron Moth", PokemonType.FIRE, PokemonType.POISON, 9, PokedexColor.YELLOW, 1.2, 36.0, null, null, 544),
                PokemonSeedEntry.pokemon(995, "Iron Thorns", PokemonType.ROCK, PokemonType.ELECTRIC, 9, PokedexColor.GREEN, 1.6, 303.0, null, null, 545),
                PokemonSeedEntry.pokemon(996, "Frigibax", PokemonType.DRAGON, PokemonType.ICE, 9, PokedexColor.GRAY, 0.5, 17.0, EvolutionStage.BASE, 35, 546),
                PokemonSeedEntry.pokemon(997, "Arctibax", PokemonType.DRAGON, PokemonType.ICE, 9, PokedexColor.GRAY, 0.8, 30.0, EvolutionStage.FIRST_STAGE, 54, 546),
                PokemonSeedEntry.pokemon(998, "Baxcalibur", PokemonType.DRAGON, PokemonType.ICE, 9, PokedexColor.GRAY, 2.1, 210.0, EvolutionStage.SECOND_STAGE, null, 546),
                PokemonSeedEntry.pokemon(999, "Gimmighoul", PokemonType.GHOST, null, 9, PokedexColor.BROWN, 0.3, 5.0, EvolutionStage.BASE, null, 547),
                PokemonSeedEntry.pokemon(1000, "Gholdengo", PokemonType.STEEL, PokemonType.GHOST, 9, PokedexColor.YELLOW, 1.2, 30.0, EvolutionStage.SECOND_STAGE, null, 547),
                PokemonSeedEntry.pokemon(1001, "Wo-Chien", PokemonType.DARK, PokemonType.GRASS, 9, PokedexColor.BROWN, 1.5, 74.2, null, null, 548),
                PokemonSeedEntry.pokemon(1002, "Chien-Pao", PokemonType.DARK, PokemonType.ICE, 9, PokedexColor.WHITE, 1.9, 152.2, null, null, 549),
                PokemonSeedEntry.pokemon(1003, "Ting-Lu", PokemonType.DARK, PokemonType.GROUND, 9, PokedexColor.BROWN, 2.7, 699.7, null, null, 550),
                PokemonSeedEntry.pokemon(1004, "Chi-Yu", PokemonType.DARK, PokemonType.FIRE, 9, PokedexColor.RED, 0.4, 4.9, null, null, 551),
                PokemonSeedEntry.pokemon(1005, "Roaring Moon", PokemonType.DRAGON, PokemonType.DARK, 9, PokedexColor.GREEN, 2.0, 380.0, null, null, 552),
                PokemonSeedEntry.pokemon(1006, "Iron Valiant", PokemonType.FAIRY, PokemonType.FIGHTING, 9, PokedexColor.WHITE, 1.4, 35.0, null, null, 553),
                PokemonSeedEntry.pokemon(1007, "Koraidon", PokemonType.FIGHTING, PokemonType.DRAGON, 9, PokedexColor.RED, 2.5, 303.0, null, null, 554),
                PokemonSeedEntry.pokemon(1008, "Miraidon", PokemonType.ELECTRIC, PokemonType.DRAGON, 9, PokedexColor.BLUE, 3.5, 240.0, null, null, 555),
                PokemonSeedEntry.pokemon(1009, "Walking Wake", PokemonType.WATER, PokemonType.DRAGON, 9, PokedexColor.BLUE, 3.5, 280.0, null, null, 556),
                PokemonSeedEntry.pokemon(1010, "Iron Leaves", PokemonType.GRASS, PokemonType.PSYCHIC, 9, PokedexColor.GREEN, 1.5, 125.0, null, null, 557),
                PokemonSeedEntry.pokemon(1011, "Dipplin", PokemonType.GRASS, PokemonType.DRAGON, 9, PokedexColor.GREEN, 0.4, 9.7, EvolutionStage.FIRST_STAGE, null, 460),
                PokemonSeedEntry.pokemon(1012, "Poltchageist", PokemonType.GRASS, PokemonType.GHOST, 9, PokedexColor.GREEN, 0.1, 1.1, EvolutionStage.BASE, null, 558),
                PokemonSeedEntry.pokemon(1013, "Sinistcha", PokemonType.GRASS, PokemonType.GHOST, 9, PokedexColor.GREEN, 0.2, 2.2, EvolutionStage.SECOND_STAGE, null, 558),
                PokemonSeedEntry.pokemon(1014, "Okidogi", PokemonType.POISON, PokemonType.FIGHTING, 9, PokedexColor.BLACK, 1.8, 92.2, null, null, 559),
                PokemonSeedEntry.pokemon(1015, "Munkidori", PokemonType.POISON, PokemonType.PSYCHIC, 9, PokedexColor.BLACK, 1.0, 12.2, null, null, 560),
                PokemonSeedEntry.pokemon(1016, "Fezandipiti", PokemonType.POISON, PokemonType.FAIRY, 9, PokedexColor.BLACK, 1.4, 30.1, null, null, 561),
                PokemonSeedEntry.pokemon(1017, "Ogerpon", PokemonType.GRASS, null, 9, PokedexColor.GREEN, 1.2, 39.8, null, null, 562),
                PokemonSeedEntry.pokemon(1018, "Archaludon", PokemonType.STEEL, PokemonType.DRAGON, 9, PokedexColor.WHITE, 2.0, 60.0, EvolutionStage.SECOND_STAGE, null, 483),
                PokemonSeedEntry.pokemon(1019, "Hydrapple", PokemonType.GRASS, PokemonType.DRAGON, 9, PokedexColor.GREEN, 1.8, 93.0, EvolutionStage.SECOND_STAGE, null, 460),
                PokemonSeedEntry.pokemon(1020, "Gouging Fire", PokemonType.FIRE, PokemonType.DRAGON, 9, PokedexColor.BROWN, 3.5, 590.0, null, null, 563),
                PokemonSeedEntry.pokemon(1021, "Raging Bolt", PokemonType.ELECTRIC, PokemonType.DRAGON, 9, PokedexColor.YELLOW, 5.2, 480.0, null, null, 564),
                PokemonSeedEntry.pokemon(1022, "Iron Boulder", PokemonType.ROCK, PokemonType.PSYCHIC, 9, PokedexColor.GRAY, 1.5, 162.5, null, null, 565),
                PokemonSeedEntry.pokemon(1023, "Iron Crown", PokemonType.STEEL, PokemonType.PSYCHIC, 9, PokedexColor.BLUE, 1.6, 156.0, null, null, 566),
                PokemonSeedEntry.pokemon(1024, "Terapagos", PokemonType.NORMAL, null, 9, PokedexColor.BLUE, 0.2, 6.5, null, null, 567),
                PokemonSeedEntry.pokemon(1025, "Pecharunt", PokemonType.POISON, PokemonType.GHOST, 9, PokedexColor.PURPLE, 0.3, 0.3, null, null, 568)
        );
    }
}
