package com.svc.pokeguessteam.config.seed;

import com.svc.pokeguessteam.model.enums.EvolutionStage;
import com.svc.pokeguessteam.model.enums.PokedexColor;
import com.svc.pokeguessteam.model.enums.PokemonType;

import java.util.List;

public final class Generation1Seed {

    private Generation1Seed() {
    }

    public static List<PokemonSeedEntry> entries() {
        return List.of(
                PokemonSeedEntry.pokemon(1, "Bulbasaur", PokemonType.GRASS, PokemonType.POISON, 1, PokedexColor.GREEN, 0.7, 6.9, EvolutionStage.BASE, 16, 1),
                PokemonSeedEntry.pokemon(2, "Ivysaur", PokemonType.GRASS, PokemonType.POISON, 1, PokedexColor.GREEN, 1, 13, EvolutionStage.FIRST_STAGE, 32, 1),
                PokemonSeedEntry.pokemon(3, "Venusaur", PokemonType.GRASS, PokemonType.POISON, 1, PokedexColor.GREEN, 2, 100, EvolutionStage.SECOND_STAGE, null, 1),
                PokemonSeedEntry.pokemon(4, "Charmander", PokemonType.FIRE, null, 1, PokedexColor.RED, 0.6, 8.5, EvolutionStage.BASE, 16, 2),
                PokemonSeedEntry.pokemon(5, "Charmeleon", PokemonType.FIRE, null, 1, PokedexColor.RED, 1.1, 19, EvolutionStage.FIRST_STAGE, 36, 2),
                PokemonSeedEntry.pokemon(6, "Charizard", PokemonType.FIRE, PokemonType.FLYING, 1, PokedexColor.RED, 1.7, 90.5, EvolutionStage.SECOND_STAGE, null, 2),
                PokemonSeedEntry.pokemon(7, "Squirtle", PokemonType.WATER, null, 1, PokedexColor.BLUE, 0.5, 9, EvolutionStage.BASE, 16, 3),
                PokemonSeedEntry.pokemon(8, "Wartortle", PokemonType.WATER, null, 1, PokedexColor.BLUE, 1, 22.5, EvolutionStage.FIRST_STAGE, 36, 3),
                PokemonSeedEntry.pokemon(9, "Blastoise", PokemonType.WATER, null, 1, PokedexColor.BLUE, 1.6, 85.5, EvolutionStage.SECOND_STAGE, null, 3),
                PokemonSeedEntry.pokemon(10, "Caterpie", PokemonType.BUG, null, 1, PokedexColor.GREEN, 0.3, 2.9, EvolutionStage.BASE, 7, 4),
                PokemonSeedEntry.pokemon(11, "Metapod", PokemonType.BUG, null, 1, PokedexColor.GREEN, 0.7, 9.9, EvolutionStage.FIRST_STAGE, 10, 4),
                PokemonSeedEntry.pokemon(12, "Butterfree", PokemonType.BUG, PokemonType.FLYING, 1, PokedexColor.WHITE, 1.1, 32, EvolutionStage.SECOND_STAGE, null, 4),
                PokemonSeedEntry.pokemon(13, "Weedle", PokemonType.BUG, PokemonType.POISON, 1, PokedexColor.BROWN, 0.3, 3.2, EvolutionStage.BASE, 7, 5),
                PokemonSeedEntry.pokemon(14, "Kakuna", PokemonType.BUG, PokemonType.POISON, 1, PokedexColor.YELLOW, 0.6, 10, EvolutionStage.FIRST_STAGE, 10, 5),
                PokemonSeedEntry.pokemon(15, "Beedrill", PokemonType.BUG, PokemonType.POISON, 1, PokedexColor.YELLOW, 1, 29.5, EvolutionStage.SECOND_STAGE, null, 5),
                PokemonSeedEntry.pokemon(16, "Pidgey", PokemonType.NORMAL, PokemonType.FLYING, 1, PokedexColor.BROWN, 0.3, 1.8, EvolutionStage.BASE, 18, 6),
                PokemonSeedEntry.pokemon(17, "Pidgeotto", PokemonType.NORMAL, PokemonType.FLYING, 1, PokedexColor.BROWN, 1.1, 30, EvolutionStage.FIRST_STAGE, 36, 6),
                PokemonSeedEntry.pokemon(18, "Pidgeot", PokemonType.NORMAL, PokemonType.FLYING, 1, PokedexColor.BROWN, 1.5, 39.5, EvolutionStage.SECOND_STAGE, null, 6),
                PokemonSeedEntry.pokemon(19, "Rattata", PokemonType.NORMAL, null, 1, PokedexColor.PURPLE, 0.3, 3.5, EvolutionStage.BASE, 20, 7),
                PokemonSeedEntry.pokemon(20, "Raticate", PokemonType.NORMAL, null, 1, PokedexColor.BROWN, 0.7, 18.5, EvolutionStage.SECOND_STAGE, null, 7),
                PokemonSeedEntry.pokemon(21, "Spearow", PokemonType.NORMAL, PokemonType.FLYING, 1, PokedexColor.BROWN, 0.3, 2, EvolutionStage.BASE, 20, 8),
                PokemonSeedEntry.pokemon(22, "Fearow", PokemonType.NORMAL, PokemonType.FLYING, 1, PokedexColor.BROWN, 1.2, 38, EvolutionStage.SECOND_STAGE, null, 8),
                PokemonSeedEntry.pokemon(23, "Ekans", PokemonType.POISON, null, 1, PokedexColor.PURPLE, 2, 6.9, EvolutionStage.BASE, 22, 9),
                PokemonSeedEntry.pokemon(24, "Arbok", PokemonType.POISON, null, 1, PokedexColor.PURPLE, 3.5, 65, EvolutionStage.SECOND_STAGE, null, 9),
                PokemonSeedEntry.pokemon(25, "Pikachu", PokemonType.ELECTRIC, null, 1, PokedexColor.YELLOW, 0.4, 6, EvolutionStage.BASE, null, 89),
                PokemonSeedEntry.pokemon(26, "Raichu", PokemonType.ELECTRIC, null, 1, PokedexColor.YELLOW, 0.8, 30, EvolutionStage.SECOND_STAGE, null, 89),
                PokemonSeedEntry.pokemon(27, "Sandshrew", PokemonType.GROUND, null, 1, PokedexColor.YELLOW, 0.6, 12, EvolutionStage.BASE, 22, 10),
                PokemonSeedEntry.pokemon(28, "Sandslash", PokemonType.GROUND, null, 1, PokedexColor.YELLOW, 1, 29.5, EvolutionStage.SECOND_STAGE, null, 10),
                PokemonSeedEntry.pokemon(29, "Nidoran F", PokemonType.POISON, null, 1, PokedexColor.BLUE, 0.4, 7, EvolutionStage.BASE, 16, 11),
                PokemonSeedEntry.pokemon(30, "Nidorina", PokemonType.POISON, null, 1, PokedexColor.BLUE, 0.8, 20, EvolutionStage.FIRST_STAGE, null, 11),
                PokemonSeedEntry.pokemon(31, "Nidoqueen", PokemonType.POISON, PokemonType.GROUND, 1, PokedexColor.BLUE, 1.3, 60, EvolutionStage.SECOND_STAGE, null, 11),
                PokemonSeedEntry.pokemon(32, "Nidoran M", PokemonType.POISON, null, 1, PokedexColor.PURPLE, 0.5, 9, EvolutionStage.BASE, 16, 12),
                PokemonSeedEntry.pokemon(33, "Nidorino", PokemonType.POISON, null, 1, PokedexColor.PURPLE, 0.9, 19.5, EvolutionStage.FIRST_STAGE, null, 12),
                PokemonSeedEntry.pokemon(34, "Nidoking", PokemonType.POISON, PokemonType.GROUND, 1, PokedexColor.PURPLE, 1.4, 62, EvolutionStage.SECOND_STAGE, null, 12),
                PokemonSeedEntry.pokemon(35, "Clefairy", PokemonType.FAIRY, null, 1, PokedexColor.PINK, 0.6, 7.5, EvolutionStage.BASE, null, 90),
                PokemonSeedEntry.pokemon(36, "Clefable", PokemonType.FAIRY, null, 1, PokedexColor.PINK, 1.3, 40, EvolutionStage.SECOND_STAGE, null, 90),
                PokemonSeedEntry.pokemon(37, "Vulpix", PokemonType.FIRE, null, 1, PokedexColor.BROWN, 0.6, 9.9, EvolutionStage.BASE, null, 13),
                PokemonSeedEntry.pokemon(38, "Ninetales", PokemonType.FIRE, null, 1, PokedexColor.YELLOW, 1.1, 19.9, EvolutionStage.SECOND_STAGE, null, 13),
                PokemonSeedEntry.pokemon(39, "Jigglypuff", PokemonType.NORMAL, PokemonType.FAIRY, 1, PokedexColor.PINK, 0.5, 5.5, EvolutionStage.BASE, null, 91),
                PokemonSeedEntry.pokemon(40, "Wigglytuff", PokemonType.NORMAL, PokemonType.FAIRY, 1, PokedexColor.PINK, 1, 12, EvolutionStage.SECOND_STAGE, null, 91),
                PokemonSeedEntry.pokemon(41, "Zubat", PokemonType.POISON, PokemonType.FLYING, 1, PokedexColor.PURPLE, 0.8, 7.5, EvolutionStage.BASE, 22, 14),
                PokemonSeedEntry.pokemon(42, "Golbat", PokemonType.POISON, PokemonType.FLYING, 1, PokedexColor.PURPLE, 1.6, 55, EvolutionStage.SECOND_STAGE, null, 14),
                PokemonSeedEntry.pokemon(43, "Oddish", PokemonType.GRASS, PokemonType.POISON, 1, PokedexColor.BLUE, 0.5, 5.4, EvolutionStage.BASE, 21, 15),
                PokemonSeedEntry.pokemon(44, "Gloom", PokemonType.GRASS, PokemonType.POISON, 1, PokedexColor.BLUE, 0.8, 8.6, EvolutionStage.FIRST_STAGE, null, 15),
                PokemonSeedEntry.pokemon(45, "Vileplume", PokemonType.GRASS, PokemonType.POISON, 1, PokedexColor.RED, 1.2, 18.6, EvolutionStage.SECOND_STAGE, null, 15),
                PokemonSeedEntry.pokemon(46, "Paras", PokemonType.BUG, PokemonType.GRASS, 1, PokedexColor.RED, 0.3, 5.4, EvolutionStage.BASE, 24, 17),
                PokemonSeedEntry.pokemon(47, "Parasect", PokemonType.BUG, PokemonType.GRASS, 1, PokedexColor.RED, 1, 29.5, EvolutionStage.SECOND_STAGE, null, 17),
                PokemonSeedEntry.pokemon(48, "Venonat", PokemonType.BUG, PokemonType.POISON, 1, PokedexColor.PURPLE, 1, 30, EvolutionStage.BASE, 31, 18),
                PokemonSeedEntry.pokemon(49, "Venomoth", PokemonType.BUG, PokemonType.POISON, 1, PokedexColor.PURPLE, 1.5, 12.5, EvolutionStage.SECOND_STAGE, null, 18),
                PokemonSeedEntry.pokemon(50, "Diglett", PokemonType.GROUND, null, 1, PokedexColor.BROWN, 0.2, 0.8, EvolutionStage.BASE, 26, 19),
                PokemonSeedEntry.pokemon(51, "Dugtrio", PokemonType.GROUND, null, 1, PokedexColor.BROWN, 0.7, 33.3, EvolutionStage.SECOND_STAGE, null, 19),
                PokemonSeedEntry.pokemon(52, "Meowth", PokemonType.NORMAL, null, 1, PokedexColor.YELLOW, 0.4, 4.2, EvolutionStage.BASE, 28, 20),
                PokemonSeedEntry.pokemon(53, "Persian", PokemonType.NORMAL, null, 1, PokedexColor.YELLOW, 1, 32, EvolutionStage.SECOND_STAGE, null, 20),
                PokemonSeedEntry.pokemon(54, "Psyduck", PokemonType.WATER, null, 1, PokedexColor.YELLOW, 0.8, 19.6, EvolutionStage.BASE, 33, 22),
                PokemonSeedEntry.pokemon(55, "Golduck", PokemonType.WATER, null, 1, PokedexColor.BLUE, 1.7, 76.6, EvolutionStage.SECOND_STAGE, null, 22),
                PokemonSeedEntry.pokemon(56, "Mankey", PokemonType.FIGHTING, null, 1, PokedexColor.BROWN, 0.5, 28, EvolutionStage.BASE, 28, 23),
                PokemonSeedEntry.pokemon(57, "Primeape", PokemonType.FIGHTING, null, 1, PokedexColor.BROWN, 1, 32, EvolutionStage.SECOND_STAGE, null, 23),
                PokemonSeedEntry.pokemon(58, "Growlithe", PokemonType.FIRE, null, 1, PokedexColor.BROWN, 0.7, 19, EvolutionStage.BASE, null, 24),
                PokemonSeedEntry.pokemon(59, "Arcanine", PokemonType.FIRE, null, 1, PokedexColor.BROWN, 1.9, 155, EvolutionStage.SECOND_STAGE, null, 24),
                PokemonSeedEntry.pokemon(60, "Poliwag", PokemonType.WATER, null, 1, PokedexColor.BLUE, 0.6, 12.4, EvolutionStage.BASE, 25, 25),
                PokemonSeedEntry.pokemon(61, "Poliwhirl", PokemonType.WATER, null, 1, PokedexColor.BLUE, 1, 20, EvolutionStage.FIRST_STAGE, null, 25),
                PokemonSeedEntry.pokemon(62, "Poliwrath", PokemonType.WATER, PokemonType.FIGHTING, 1, PokedexColor.BLUE, 1.3, 54, EvolutionStage.SECOND_STAGE, null, 25),
                PokemonSeedEntry.pokemon(63, "Abra", PokemonType.PSYCHIC, null, 1, PokedexColor.BROWN, 0.9, 19.5, EvolutionStage.BASE, 16, 27),
                PokemonSeedEntry.pokemon(64, "Kadabra", PokemonType.PSYCHIC, null, 1, PokedexColor.BROWN, 1.3, 56.5, EvolutionStage.FIRST_STAGE, null, 27),
                PokemonSeedEntry.pokemon(65, "Alakazam", PokemonType.PSYCHIC, null, 1, PokedexColor.BROWN, 1.5, 48, EvolutionStage.SECOND_STAGE, null, 27),
                PokemonSeedEntry.pokemon(66, "Machop", PokemonType.FIGHTING, null, 1, PokedexColor.GRAY, 0.8, 19.5, EvolutionStage.BASE, 28, 28),
                PokemonSeedEntry.pokemon(67, "Machoke", PokemonType.FIGHTING, null, 1, PokedexColor.GRAY, 1.5, 70.5, EvolutionStage.FIRST_STAGE, null, 28),
                PokemonSeedEntry.pokemon(68, "Machamp", PokemonType.FIGHTING, null, 1, PokedexColor.GRAY, 1.6, 130, EvolutionStage.SECOND_STAGE, null, 28),
                PokemonSeedEntry.pokemon(69, "Bellsprout", PokemonType.GRASS, PokemonType.POISON, 1, PokedexColor.GREEN, 0.7, 4, EvolutionStage.BASE, 21, 29),
                PokemonSeedEntry.pokemon(70, "Weepinbell", PokemonType.GRASS, PokemonType.POISON, 1, PokedexColor.GREEN, 1, 6.4, EvolutionStage.FIRST_STAGE, null, 29),
                PokemonSeedEntry.pokemon(71, "Victreebel", PokemonType.GRASS, PokemonType.POISON, 1, PokedexColor.GREEN, 1.7, 15.5, EvolutionStage.SECOND_STAGE, null, 29),
                PokemonSeedEntry.pokemon(72, "Tentacool", PokemonType.WATER, PokemonType.POISON, 1, PokedexColor.BLUE, 0.9, 45.5, EvolutionStage.BASE, 30, 30),
                PokemonSeedEntry.pokemon(73, "Tentacruel", PokemonType.WATER, PokemonType.POISON, 1, PokedexColor.BLUE, 1.6, 55, EvolutionStage.SECOND_STAGE, null, 30),
                PokemonSeedEntry.pokemon(74, "Geodude", PokemonType.ROCK, PokemonType.GROUND, 1, PokedexColor.BROWN, 0.4, 20, EvolutionStage.BASE, 25, 31),
                PokemonSeedEntry.pokemon(75, "Graveler", PokemonType.ROCK, PokemonType.GROUND, 1, PokedexColor.BROWN, 1, 105, EvolutionStage.FIRST_STAGE, null, 31),
                PokemonSeedEntry.pokemon(76, "Golem", PokemonType.ROCK, PokemonType.GROUND, 1, PokedexColor.BROWN, 1.4, 300, EvolutionStage.SECOND_STAGE, null, 31),
                PokemonSeedEntry.pokemon(77, "Ponyta", PokemonType.FIRE, null, 1, PokedexColor.YELLOW, 1, 30, EvolutionStage.BASE, 40, 32),
                PokemonSeedEntry.pokemon(78, "Rapidash", PokemonType.FIRE, null, 1, PokedexColor.YELLOW, 1.7, 95, EvolutionStage.SECOND_STAGE, null, 32),
                PokemonSeedEntry.pokemon(79, "Slowpoke", PokemonType.WATER, PokemonType.PSYCHIC, 1, PokedexColor.PINK, 1.2, 36, EvolutionStage.BASE, 37, 33),
                PokemonSeedEntry.pokemon(80, "Slowbro", PokemonType.WATER, PokemonType.PSYCHIC, 1, PokedexColor.PINK, 1.6, 78.5, EvolutionStage.SECOND_STAGE, null, 33),
                PokemonSeedEntry.pokemon(81, "Magnemite", PokemonType.ELECTRIC, PokemonType.STEEL, 1, PokedexColor.GRAY, 0.3, 6, EvolutionStage.BASE, 30, 35),
                PokemonSeedEntry.pokemon(82, "Magneton", PokemonType.ELECTRIC, PokemonType.STEEL, 1, PokedexColor.GRAY, 1, 60, EvolutionStage.SECOND_STAGE, null, 35),
                PokemonSeedEntry.pokemon(83, "Farfetch'd", PokemonType.NORMAL, PokemonType.FLYING, 1, PokedexColor.BROWN, 0.8, 15, null, null, 36),
                PokemonSeedEntry.pokemon(84, "Doduo", PokemonType.NORMAL, PokemonType.FLYING, 1, PokedexColor.BROWN, 1.4, 39.2, EvolutionStage.BASE, 31, 37),
                PokemonSeedEntry.pokemon(85, "Dodrio", PokemonType.NORMAL, PokemonType.FLYING, 1, PokedexColor.BROWN, 1.8, 85.2, EvolutionStage.SECOND_STAGE, null, 37),
                PokemonSeedEntry.pokemon(86, "Seel", PokemonType.WATER, null, 1, PokedexColor.WHITE, 1.1, 90, EvolutionStage.BASE, 34, 38),
                PokemonSeedEntry.pokemon(87, "Dewgong", PokemonType.WATER, PokemonType.ICE, 1, PokedexColor.WHITE, 1.7, 120, EvolutionStage.SECOND_STAGE, null, 38),
                PokemonSeedEntry.pokemon(88, "Grimer", PokemonType.POISON, null, 1, PokedexColor.PURPLE, 0.9, 30, EvolutionStage.BASE, 38, 39),
                PokemonSeedEntry.pokemon(89, "Muk", PokemonType.POISON, null, 1, PokedexColor.PURPLE, 1.2, 30, EvolutionStage.SECOND_STAGE, null, 39),
                PokemonSeedEntry.pokemon(90, "Shellder", PokemonType.WATER, null, 1, PokedexColor.PURPLE, 0.3, 4, EvolutionStage.BASE, null, 40),
                PokemonSeedEntry.pokemon(91, "Cloyster", PokemonType.WATER, PokemonType.ICE, 1, PokedexColor.PURPLE, 1.5, 132.5, EvolutionStage.SECOND_STAGE, null, 40),
                PokemonSeedEntry.pokemon(92, "Gastly", PokemonType.GHOST, PokemonType.POISON, 1, PokedexColor.PURPLE, 1.3, 0.1, EvolutionStage.BASE, 25, 41),
                PokemonSeedEntry.pokemon(93, "Haunter", PokemonType.GHOST, PokemonType.POISON, 1, PokedexColor.PURPLE, 1.6, 0.1, EvolutionStage.FIRST_STAGE, null, 41),
                PokemonSeedEntry.pokemon(94, "Gengar", PokemonType.GHOST, PokemonType.POISON, 1, PokedexColor.PURPLE, 1.5, 40.5, EvolutionStage.SECOND_STAGE, null, 41),
                PokemonSeedEntry.pokemon(95, "Onix", PokemonType.ROCK, PokemonType.GROUND, 1, PokedexColor.GRAY, 8.8, 210, null, null, 42),
                PokemonSeedEntry.pokemon(96, "Drowzee", PokemonType.PSYCHIC, null, 1, PokedexColor.YELLOW, 1, 32.4, EvolutionStage.BASE, 26, 43),
                PokemonSeedEntry.pokemon(97, "Hypno", PokemonType.PSYCHIC, null, 1, PokedexColor.YELLOW, 1.6, 75.6, EvolutionStage.SECOND_STAGE, null, 43),
                PokemonSeedEntry.pokemon(98, "Krabby", PokemonType.WATER, null, 1, PokedexColor.RED, 0.4, 6.5, EvolutionStage.BASE, 28, 44),
                PokemonSeedEntry.pokemon(99, "Kingler", PokemonType.WATER, null, 1, PokedexColor.RED, 1.3, 60, EvolutionStage.SECOND_STAGE, null, 44),
                PokemonSeedEntry.pokemon(100, "Voltorb", PokemonType.ELECTRIC, null, 1, PokedexColor.RED, 0.5, 10.4, EvolutionStage.BASE, 30, 45),
                PokemonSeedEntry.pokemon(101, "Electrode", PokemonType.ELECTRIC, null, 1, PokedexColor.RED, 1.2, 66.6, EvolutionStage.SECOND_STAGE, null, 45),
                PokemonSeedEntry.pokemon(102, "Exeggcute", PokemonType.GRASS, PokemonType.PSYCHIC, 1, PokedexColor.PINK, 0.4, 2.5, EvolutionStage.BASE, null, 46),
                PokemonSeedEntry.pokemon(103, "Exeggutor", PokemonType.GRASS, PokemonType.PSYCHIC, 1, PokedexColor.YELLOW, 2, 120, EvolutionStage.SECOND_STAGE, null, 46),
                PokemonSeedEntry.pokemon(104, "Cubone", PokemonType.GROUND, null, 1, PokedexColor.BROWN, 0.4, 6.5, EvolutionStage.BASE, 28, 47),
                PokemonSeedEntry.pokemon(105, "Marowak", PokemonType.GROUND, null, 1, PokedexColor.BROWN, 1, 45, EvolutionStage.SECOND_STAGE, null, 47),
                PokemonSeedEntry.pokemon(106, "Hitmonlee", PokemonType.FIGHTING, null, 1, PokedexColor.BROWN, 1.5, 49.8, null, null, 125),
                PokemonSeedEntry.pokemon(107, "Hitmonchan", PokemonType.FIGHTING, null, 1, PokedexColor.BROWN, 1.4, 50.2, null, null, 126),
                PokemonSeedEntry.pokemon(108, "Lickitung", PokemonType.NORMAL, null, 1, PokedexColor.PINK, 1.2, 65.5, null, null, 48),
                PokemonSeedEntry.pokemon(109, "Koffing", PokemonType.POISON, null, 1, PokedexColor.PURPLE, 0.6, 1, EvolutionStage.BASE, 35, 49),
                PokemonSeedEntry.pokemon(110, "Weezing", PokemonType.POISON, null, 1, PokedexColor.PURPLE, 1.2, 9.5, EvolutionStage.SECOND_STAGE, null, 49),
                PokemonSeedEntry.pokemon(111, "Rhyhorn", PokemonType.GROUND, PokemonType.ROCK, 1, PokedexColor.GRAY, 1, 115, EvolutionStage.BASE, 42, 50),
                PokemonSeedEntry.pokemon(112, "Rhydon", PokemonType.GROUND, PokemonType.ROCK, 1, PokedexColor.GRAY, 1.9, 120, EvolutionStage.SECOND_STAGE, null, 50),
                PokemonSeedEntry.pokemon(113, "Chansey", PokemonType.NORMAL, null, 1, PokedexColor.PINK, 1.1, 34.6, null, null, 242),
                PokemonSeedEntry.pokemon(114, "Tangela", PokemonType.GRASS, null, 1, PokedexColor.BLUE, 1, 35, null, null, 51),
                PokemonSeedEntry.pokemon(115, "Kangaskhan", PokemonType.NORMAL, null, 1, PokedexColor.BROWN, 2.2, 80, null, null, 52),
                PokemonSeedEntry.pokemon(116, "Horsea", PokemonType.WATER, null, 1, PokedexColor.BLUE, 0.4, 8, EvolutionStage.BASE, 32, 53),
                PokemonSeedEntry.pokemon(117, "Seadra", PokemonType.WATER, null, 1, PokedexColor.BLUE, 1.2, 25, EvolutionStage.SECOND_STAGE, null, 53),
                PokemonSeedEntry.pokemon(118, "Goldeen", PokemonType.WATER, null, 1, PokedexColor.RED, 0.6, 15, EvolutionStage.BASE, 33, 54),
                PokemonSeedEntry.pokemon(119, "Seaking", PokemonType.WATER, null, 1, PokedexColor.RED, 1.3, 39, EvolutionStage.SECOND_STAGE, null, 54),
                PokemonSeedEntry.pokemon(120, "Staryu", PokemonType.WATER, null, 1, PokedexColor.BROWN, 0.8, 34.5, EvolutionStage.BASE, null, 55),
                PokemonSeedEntry.pokemon(121, "Starmie", PokemonType.WATER, PokemonType.PSYCHIC, 1, PokedexColor.PURPLE, 1.1, 80, EvolutionStage.SECOND_STAGE, null, 55),
                PokemonSeedEntry.pokemon(122, "Mr. Mime", PokemonType.PSYCHIC, PokemonType.FAIRY, 1, PokedexColor.PINK, 1.3, 54.5, null, null, 241),
                PokemonSeedEntry.pokemon(123, "Scyther", PokemonType.BUG, PokemonType.FLYING, 1, PokedexColor.GREEN, 1.5, 56, null, null, 56),
                PokemonSeedEntry.pokemon(124, "Jynx", PokemonType.ICE, PokemonType.PSYCHIC, 1, PokedexColor.RED, 1.4, 40.6, null, null, 128),
                PokemonSeedEntry.pokemon(125, "Electabuzz", PokemonType.ELECTRIC, null, 1, PokedexColor.YELLOW, 1.1, 30, null, null, 129),
                PokemonSeedEntry.pokemon(126, "Magmar", PokemonType.FIRE, null, 1, PokedexColor.RED, 1.3, 44.5, null, null, 130),
                PokemonSeedEntry.pokemon(127, "Pinsir", PokemonType.BUG, null, 1, PokedexColor.BROWN, 1.5, 55, null, null, 58),
                PokemonSeedEntry.pokemon(128, "Tauros", PokemonType.NORMAL, null, 1, PokedexColor.BROWN, 1.4, 88.4, null, null, 59),
                PokemonSeedEntry.pokemon(129, "Magikarp", PokemonType.WATER, null, 1, PokedexColor.RED, 0.9, 10, EvolutionStage.BASE, 20, 60),
                PokemonSeedEntry.pokemon(130, "Gyarados", PokemonType.WATER, PokemonType.FLYING, 1, PokedexColor.BLUE, 6.5, 235, EvolutionStage.SECOND_STAGE, null, 60),
                PokemonSeedEntry.pokemon(131, "Lapras", PokemonType.WATER, PokemonType.ICE, 1, PokedexColor.BLUE, 2.5, 220, null, null, 61),
                PokemonSeedEntry.pokemon(132, "Ditto", PokemonType.NORMAL, null, 1, PokedexColor.PURPLE, 0.3, 4, null, null, 62),
                PokemonSeedEntry.pokemon(133, "Eevee", PokemonType.NORMAL, null, 1, PokedexColor.BROWN, 0.3, 6.5, EvolutionStage.BASE, null, 63),
                PokemonSeedEntry.pokemon(134, "Vaporeon", PokemonType.WATER, null, 1, PokedexColor.BLUE, 1, 29, EvolutionStage.SECOND_STAGE, null, 63),
                PokemonSeedEntry.pokemon(135, "Jolteon", PokemonType.ELECTRIC, null, 1, PokedexColor.YELLOW, 0.8, 24.5, EvolutionStage.SECOND_STAGE, null, 64),
                PokemonSeedEntry.pokemon(136, "Flareon", PokemonType.FIRE, null, 1, PokedexColor.RED, 0.9, 25, EvolutionStage.SECOND_STAGE, null, 65),
                PokemonSeedEntry.pokemon(137, "Porygon", PokemonType.NORMAL, null, 1, PokedexColor.PINK, 0.8, 36.5, null, null, 71),
                PokemonSeedEntry.pokemon(138, "Omanyte", PokemonType.ROCK, PokemonType.WATER, 1, PokedexColor.BLUE, 0.4, 7.5, EvolutionStage.BASE, 40, 72),
                PokemonSeedEntry.pokemon(139, "Omastar", PokemonType.ROCK, PokemonType.WATER, 1, PokedexColor.BLUE, 1, 35, EvolutionStage.SECOND_STAGE, null, 72),
                PokemonSeedEntry.pokemon(140, "Kabuto", PokemonType.ROCK, PokemonType.WATER, 1, PokedexColor.BROWN, 0.5, 11.5, EvolutionStage.BASE, 40, 73),
                PokemonSeedEntry.pokemon(141, "Kabutops", PokemonType.ROCK, PokemonType.WATER, 1, PokedexColor.BROWN, 1.3, 40.5, EvolutionStage.SECOND_STAGE, null, 73),
                PokemonSeedEntry.pokemon(142, "Aerodactyl", PokemonType.ROCK, PokemonType.FLYING, 1, PokedexColor.PURPLE, 1.8, 59, null, null, 74),
                PokemonSeedEntry.pokemon(143, "Snorlax", PokemonType.NORMAL, null, 1, PokedexColor.BLACK, 2.1, 460, null, null, 246),
                PokemonSeedEntry.pokemon(144, "Articuno", PokemonType.ICE, PokemonType.FLYING, 1, PokedexColor.BLUE, 1.7, 55.4, null, null, 75),
                PokemonSeedEntry.pokemon(145, "Zapdos", PokemonType.ELECTRIC, PokemonType.FLYING, 1, PokedexColor.YELLOW, 1.6, 52.6, null, null, 76),
                PokemonSeedEntry.pokemon(146, "Moltres", PokemonType.FIRE, PokemonType.FLYING, 1, PokedexColor.YELLOW, 2, 60, null, null, 77),
                PokemonSeedEntry.pokemon(147, "Dratini", PokemonType.DRAGON, null, 1, PokedexColor.BLUE, 1.8, 3.3, EvolutionStage.BASE, 30, 78),
                PokemonSeedEntry.pokemon(148, "Dragonair", PokemonType.DRAGON, null, 1, PokedexColor.BLUE, 4, 16.5, EvolutionStage.FIRST_STAGE, 55, 78),
                PokemonSeedEntry.pokemon(149, "Dragonite", PokemonType.DRAGON, PokemonType.FLYING, 1, PokedexColor.BROWN, 2.2, 210, EvolutionStage.SECOND_STAGE, null, 78),
                PokemonSeedEntry.pokemon(150, "Mewtwo", PokemonType.PSYCHIC, null, 1, PokedexColor.PURPLE, 2, 122, null, null, 79),
                PokemonSeedEntry.pokemon(151, "Mew", PokemonType.PSYCHIC, null, 1, PokedexColor.PINK, 0.4, 4, null, null, 80)
        );
    }
}
