package com.svc.pokeguessteam.config.seed;

import com.svc.pokeguessteam.model.enums.EvolutionStage;
import com.svc.pokeguessteam.model.enums.PokedexColor;
import com.svc.pokeguessteam.model.enums.PokemonType;

import java.util.List;

public final class Generation8Seed {

    private Generation8Seed() {
    }

    public static List<PokemonSeedEntry> entries() {
        return List.of(
                PokemonSeedEntry.pokemon(810, "Grookey", PokemonType.GRASS, null, 8, PokedexColor.GREEN, 0.3, 5.0, EvolutionStage.BASE, 16, 446),
                PokemonSeedEntry.pokemon(811, "Thwackey", PokemonType.GRASS, null, 8, PokedexColor.GREEN, 0.7, 14.0, EvolutionStage.FIRST_STAGE, 35, 446),
                PokemonSeedEntry.pokemon(812, "Rillaboom", PokemonType.GRASS, null, 8, PokedexColor.GREEN, 2.1, 90.0, EvolutionStage.SECOND_STAGE, null, 446),
                PokemonSeedEntry.pokemon(813, "Scorbunny", PokemonType.FIRE, null, 8, PokedexColor.WHITE, 0.3, 4.5, EvolutionStage.BASE, 16, 447),
                PokemonSeedEntry.pokemon(814, "Raboot", PokemonType.FIRE, null, 8, PokedexColor.GRAY, 0.6, 9.0, EvolutionStage.FIRST_STAGE, 35, 447),
                PokemonSeedEntry.pokemon(815, "Cinderace", PokemonType.FIRE, null, 8, PokedexColor.WHITE, 1.4, 33.0, EvolutionStage.SECOND_STAGE, null, 447),
                PokemonSeedEntry.pokemon(816, "Sobble", PokemonType.WATER, null, 8, PokedexColor.BLUE, 0.3, 4.0, EvolutionStage.BASE, 16, 448),
                PokemonSeedEntry.pokemon(817, "Drizzile", PokemonType.WATER, null, 8, PokedexColor.BLUE, 0.7, 11.5, EvolutionStage.FIRST_STAGE, 35, 448),
                PokemonSeedEntry.pokemon(818, "Inteleon", PokemonType.WATER, null, 8, PokedexColor.BLUE, 1.9, 45.2, EvolutionStage.SECOND_STAGE, null, 448),
                PokemonSeedEntry.pokemon(819, "Skwovet", PokemonType.NORMAL, null, 8, PokedexColor.BROWN, 0.3, 2.5, EvolutionStage.BASE, 24, 449),
                PokemonSeedEntry.pokemon(820, "Greedent", PokemonType.NORMAL, null, 8, PokedexColor.BROWN, 0.6, 6.0, EvolutionStage.SECOND_STAGE, null, 449),
                PokemonSeedEntry.pokemon(821, "Rookidee", PokemonType.FLYING, null, 8, PokedexColor.BLUE, 0.2, 1.8, EvolutionStage.BASE, 18, 450),
                PokemonSeedEntry.pokemon(822, "Corvisquire", PokemonType.FLYING, null, 8, PokedexColor.BLUE, 0.8, 16.0, EvolutionStage.FIRST_STAGE, 38, 450),
                PokemonSeedEntry.pokemon(823, "Corviknight", PokemonType.FLYING, PokemonType.STEEL, 8, PokedexColor.PURPLE, 2.2, 75.0, EvolutionStage.SECOND_STAGE, null, 450),
                PokemonSeedEntry.pokemon(824, "Blipbug", PokemonType.BUG, null, 8, PokedexColor.BLUE, 0.4, 8.0, EvolutionStage.BASE, 10, 451),
                PokemonSeedEntry.pokemon(825, "Dottler", PokemonType.BUG, PokemonType.PSYCHIC, 8, PokedexColor.YELLOW, 0.4, 19.5, EvolutionStage.FIRST_STAGE, 30, 451),
                PokemonSeedEntry.pokemon(826, "Orbeetle", PokemonType.BUG, PokemonType.PSYCHIC, 8, PokedexColor.RED, 0.4, 40.8, EvolutionStage.SECOND_STAGE, null, 451),
                PokemonSeedEntry.pokemon(827, "Nickit", PokemonType.DARK, null, 8, PokedexColor.BROWN, 0.6, 8.9, EvolutionStage.BASE, 18, 452),
                PokemonSeedEntry.pokemon(828, "Thievul", PokemonType.DARK, null, 8, PokedexColor.BROWN, 1.2, 19.9, EvolutionStage.SECOND_STAGE, null, 452),
                PokemonSeedEntry.pokemon(829, "Gossifleur", PokemonType.GRASS, null, 8, PokedexColor.GREEN, 0.4, 2.2, EvolutionStage.BASE, 20, 453),
                PokemonSeedEntry.pokemon(830, "Eldegoss", PokemonType.GRASS, null, 8, PokedexColor.GREEN, 0.5, 2.5, EvolutionStage.SECOND_STAGE, null, 453),
                PokemonSeedEntry.pokemon(831, "Wooloo", PokemonType.NORMAL, null, 8, PokedexColor.WHITE, 0.6, 6.0, EvolutionStage.BASE, 24, 454),
                PokemonSeedEntry.pokemon(832, "Dubwool", PokemonType.NORMAL, null, 8, PokedexColor.WHITE, 1.3, 43.0, EvolutionStage.SECOND_STAGE, null, 454),
                PokemonSeedEntry.pokemon(833, "Chewtle", PokemonType.WATER, null, 8, PokedexColor.GREEN, 0.3, 8.5, EvolutionStage.BASE, 22, 455),
                PokemonSeedEntry.pokemon(834, "Drednaw", PokemonType.WATER, PokemonType.ROCK, 8, PokedexColor.GREEN, 1.0, 115.5, EvolutionStage.SECOND_STAGE, null, 455),
                PokemonSeedEntry.pokemon(835, "Yamper", PokemonType.ELECTRIC, null, 8, PokedexColor.YELLOW, 0.3, 13.5, EvolutionStage.BASE, 25, 456),
                PokemonSeedEntry.pokemon(836, "Boltund", PokemonType.ELECTRIC, null, 8, PokedexColor.YELLOW, 1.0, 34.0, EvolutionStage.SECOND_STAGE, null, 456),
                PokemonSeedEntry.pokemon(837, "Rolycoly", PokemonType.ROCK, null, 8, PokedexColor.BLACK, 0.3, 12.0, EvolutionStage.BASE, 18, 457),
                PokemonSeedEntry.pokemon(838, "Carkol", PokemonType.ROCK, PokemonType.FIRE, 8, PokedexColor.BLACK, 1.1, 78.0, EvolutionStage.FIRST_STAGE, 34, 457),
                PokemonSeedEntry.pokemon(839, "Coalossal", PokemonType.ROCK, PokemonType.FIRE, 8, PokedexColor.BLACK, 2.8, 310.5, EvolutionStage.SECOND_STAGE, null, 457),
                PokemonSeedEntry.pokemon(840, "Applin", PokemonType.GRASS, PokemonType.DRAGON, 8, PokedexColor.GREEN, 0.2, 0.5, EvolutionStage.BASE, null, 460),
                PokemonSeedEntry.pokemon(841, "Flapple", PokemonType.GRASS, PokemonType.DRAGON, 8, PokedexColor.GREEN, 0.3, 1.0, EvolutionStage.SECOND_STAGE, null, 458),
                PokemonSeedEntry.pokemon(842, "Appletun", PokemonType.GRASS, PokemonType.DRAGON, 8, PokedexColor.GREEN, 0.4, 13.0, EvolutionStage.SECOND_STAGE, null, 459),
                PokemonSeedEntry.pokemon(843, "Silicobra", PokemonType.GROUND, null, 8, PokedexColor.GREEN, 2.2, 7.6, EvolutionStage.BASE, 36, 461),
                PokemonSeedEntry.pokemon(844, "Sandaconda", PokemonType.GROUND, null, 8, PokedexColor.GREEN, 3.8, 65.5, EvolutionStage.SECOND_STAGE, null, 461),
                PokemonSeedEntry.pokemon(845, "Cramorant", PokemonType.FLYING, PokemonType.WATER, 8, PokedexColor.BLUE, 0.8, 18.0, null, null, 462),
                PokemonSeedEntry.pokemon(846, "Arrokuda", PokemonType.WATER, null, 8, PokedexColor.BROWN, 0.5, 1.0, EvolutionStage.BASE, 26, 463),
                PokemonSeedEntry.pokemon(847, "Barraskewda", PokemonType.WATER, null, 8, PokedexColor.BROWN, 1.3, 30.0, EvolutionStage.SECOND_STAGE, null, 463),
                PokemonSeedEntry.pokemon(848, "Toxel", PokemonType.ELECTRIC, PokemonType.POISON, 8, PokedexColor.PURPLE, 0.4, 11.0, EvolutionStage.BASE, 30, 464),
                PokemonSeedEntry.pokemon(849, "Toxtricity", PokemonType.ELECTRIC, PokemonType.POISON, 8, PokedexColor.PURPLE, 1.6, 40.0, EvolutionStage.SECOND_STAGE, null, 464),
                PokemonSeedEntry.pokemon(850, "Sizzlipede", PokemonType.FIRE, PokemonType.BUG, 8, PokedexColor.RED, 0.7, 1.0, EvolutionStage.BASE, 28, 465),
                PokemonSeedEntry.pokemon(851, "Centiskorch", PokemonType.FIRE, PokemonType.BUG, 8, PokedexColor.RED, 3.0, 120.0, EvolutionStage.SECOND_STAGE, null, 465),
                PokemonSeedEntry.pokemon(852, "Clobbopus", PokemonType.FIGHTING, null, 8, PokedexColor.BROWN, 0.6, 4.0, EvolutionStage.BASE, null, 466),
                PokemonSeedEntry.pokemon(853, "Grapploct", PokemonType.FIGHTING, null, 8, PokedexColor.BLUE, 1.6, 39.0, EvolutionStage.SECOND_STAGE, null, 466),
                PokemonSeedEntry.pokemon(854, "Sinistea", PokemonType.GHOST, null, 8, PokedexColor.PURPLE, 0.1, 0.2, EvolutionStage.BASE, null, 467),
                PokemonSeedEntry.pokemon(855, "Polteageist", PokemonType.GHOST, null, 8, PokedexColor.PURPLE, 0.2, 0.4, EvolutionStage.SECOND_STAGE, null, 467),
                PokemonSeedEntry.pokemon(856, "Hatenna", PokemonType.PSYCHIC, null, 8, PokedexColor.PINK, 0.4, 3.4, EvolutionStage.BASE, 32, 468),
                PokemonSeedEntry.pokemon(857, "Hattrem", PokemonType.PSYCHIC, null, 8, PokedexColor.PINK, 0.6, 4.8, EvolutionStage.FIRST_STAGE, 42, 468),
                PokemonSeedEntry.pokemon(858, "Hatterene", PokemonType.PSYCHIC, PokemonType.FAIRY, 8, PokedexColor.PINK, 2.1, 5.1, EvolutionStage.SECOND_STAGE, null, 468),
                PokemonSeedEntry.pokemon(859, "Impidimp", PokemonType.DARK, PokemonType.FAIRY, 8, PokedexColor.PINK, 0.4, 5.5, EvolutionStage.BASE, 32, 469),
                PokemonSeedEntry.pokemon(860, "Morgrem", PokemonType.DARK, PokemonType.FAIRY, 8, PokedexColor.PINK, 0.8, 12.5, EvolutionStage.FIRST_STAGE, 42, 469),
                PokemonSeedEntry.pokemon(861, "Grimmsnarl", PokemonType.DARK, PokemonType.FAIRY, 8, PokedexColor.PURPLE, 1.5, 61.0, EvolutionStage.SECOND_STAGE, null, 469),
                PokemonSeedEntry.pokemon(862, "Obstagoon", PokemonType.DARK, PokemonType.NORMAL, 8, PokedexColor.GRAY, 1.6, 46.0, EvolutionStage.SECOND_STAGE, null, 143),
                PokemonSeedEntry.pokemon(863, "Perrserker", PokemonType.STEEL, null, 8, PokedexColor.BROWN, 0.8, 28.0, EvolutionStage.SECOND_STAGE, null, 21),
                PokemonSeedEntry.pokemon(864, "Cursola", PokemonType.GHOST, null, 8, PokedexColor.WHITE, 1.0, 0.4, EvolutionStage.SECOND_STAGE, null, 117),
                PokemonSeedEntry.pokemon(865, "Sirfetch'd", PokemonType.FIGHTING, null, 8, PokedexColor.WHITE, 0.8, 117.0, EvolutionStage.SECOND_STAGE, null, 36),
                PokemonSeedEntry.pokemon(866, "Mr. Rime", PokemonType.ICE, PokemonType.PSYCHIC, 8, PokedexColor.PURPLE, 1.5, 58.2, EvolutionStage.SECOND_STAGE, null, 241),
                PokemonSeedEntry.pokemon(867, "Runerigus", PokemonType.GROUND, PokemonType.GHOST, 8, PokedexColor.GRAY, 1.6, 66.6, EvolutionStage.SECOND_STAGE, null, 302),
                PokemonSeedEntry.pokemon(868, "Milcery", PokemonType.FAIRY, null, 8, PokedexColor.WHITE, 0.2, 0.3, EvolutionStage.BASE, null, 470),
                PokemonSeedEntry.pokemon(869, "Alcremie", PokemonType.FAIRY, null, 8, PokedexColor.WHITE, 0.3, 0.5, EvolutionStage.SECOND_STAGE, null, 470),
                PokemonSeedEntry.pokemon(870, "Falinks", PokemonType.FIGHTING, null, 8, PokedexColor.YELLOW, 3.0, 62.0, null, null, 471),
                PokemonSeedEntry.pokemon(871, "Pincurchin", PokemonType.ELECTRIC, null, 8, PokedexColor.PURPLE, 0.3, 1.0, null, null, 472),
                PokemonSeedEntry.pokemon(872, "Snom", PokemonType.ICE, PokemonType.BUG, 8, PokedexColor.WHITE, 0.3, 3.8, EvolutionStage.BASE, null, 473),
                PokemonSeedEntry.pokemon(873, "Frosmoth", PokemonType.ICE, PokemonType.BUG, 8, PokedexColor.WHITE, 1.3, 42.0, EvolutionStage.SECOND_STAGE, null, 473),
                PokemonSeedEntry.pokemon(874, "Stonjourner", PokemonType.ROCK, null, 8, PokedexColor.GRAY, 2.5, 520.0, null, null, 474),
                PokemonSeedEntry.pokemon(875, "Eiscue", PokemonType.ICE, null, 8, PokedexColor.BLUE, 1.4, 89.0, null, null, 475),
                PokemonSeedEntry.pokemon(876, "Indeedee", PokemonType.PSYCHIC, PokemonType.NORMAL, 8, PokedexColor.PURPLE, 0.9, 28.0, null, null, 476),
                PokemonSeedEntry.pokemon(877, "Morpeko", PokemonType.ELECTRIC, PokemonType.DARK, 8, PokedexColor.YELLOW, 0.3, 3.0, null, null, 477),
                PokemonSeedEntry.pokemon(878, "Cufant", PokemonType.STEEL, null, 8, PokedexColor.YELLOW, 1.2, 100.0, EvolutionStage.BASE, 34, 478),
                PokemonSeedEntry.pokemon(879, "Copperajah", PokemonType.STEEL, null, 8, PokedexColor.GREEN, 3.0, 650.0, EvolutionStage.SECOND_STAGE, null, 478),
                PokemonSeedEntry.pokemon(880, "Dracozolt", PokemonType.ELECTRIC, PokemonType.DRAGON, 8, PokedexColor.GREEN, 1.8, 190.0, null, null, 479),
                PokemonSeedEntry.pokemon(881, "Arctozolt", PokemonType.ELECTRIC, PokemonType.ICE, 8, PokedexColor.BLUE, 2.3, 150.0, null, null, 480),
                PokemonSeedEntry.pokemon(882, "Dracovish", PokemonType.WATER, PokemonType.DRAGON, 8, PokedexColor.GREEN, 2.3, 215.0, null, null, 481),
                PokemonSeedEntry.pokemon(883, "Arctovish", PokemonType.WATER, PokemonType.ICE, 8, PokedexColor.BLUE, 2.0, 175.0, null, null, 482),
                PokemonSeedEntry.pokemon(884, "Duraludon", PokemonType.STEEL, PokemonType.DRAGON, 8, PokedexColor.WHITE, 1.8, 40.0, EvolutionStage.BASE, null, 483),
                PokemonSeedEntry.pokemon(885, "Dreepy", PokemonType.DRAGON, PokemonType.GHOST, 8, PokedexColor.GREEN, 0.5, 2.0, EvolutionStage.BASE, 50, 484),
                PokemonSeedEntry.pokemon(886, "Drakloak", PokemonType.DRAGON, PokemonType.GHOST, 8, PokedexColor.GREEN, 1.4, 11.0, EvolutionStage.FIRST_STAGE, 60, 484),
                PokemonSeedEntry.pokemon(887, "Dragapult", PokemonType.DRAGON, PokemonType.GHOST, 8, PokedexColor.GREEN, 3.0, 50.0, EvolutionStage.SECOND_STAGE, null, 484),
                PokemonSeedEntry.pokemon(888, "Zacian", PokemonType.FAIRY, null, 8, PokedexColor.BLUE, 2.8, 110.0, null, null, 485),
                PokemonSeedEntry.pokemon(889, "Zamazenta", PokemonType.FIGHTING, null, 8, PokedexColor.RED, 2.9, 210.0, null, null, 486),
                PokemonSeedEntry.pokemon(890, "Eternatus", PokemonType.POISON, PokemonType.DRAGON, 8, PokedexColor.PURPLE, 20.0, 950.0, null, null, 487),
                PokemonSeedEntry.pokemon(891, "Kubfu", PokemonType.FIGHTING, null, 8, PokedexColor.GRAY, 0.6, 12.0, EvolutionStage.BASE, null, 488),
                PokemonSeedEntry.pokemon(892, "Urshifu", PokemonType.FIGHTING, PokemonType.DARK, 8, PokedexColor.GRAY, 1.9, 105.0, EvolutionStage.SECOND_STAGE, null, 488),
                PokemonSeedEntry.pokemon(893, "Zarude", PokemonType.DARK, PokemonType.GRASS, 8, PokedexColor.GREEN, 1.8, 70.0, null, null, 489),
                PokemonSeedEntry.pokemon(894, "Regieleki", PokemonType.ELECTRIC, null, 8, PokedexColor.YELLOW, 1.2, 145.0, null, null, 490),
                PokemonSeedEntry.pokemon(895, "Regidrago", PokemonType.DRAGON, null, 8, PokedexColor.GREEN, 2.1, 200.0, null, null, 491),
                PokemonSeedEntry.pokemon(896, "Glastrier", PokemonType.ICE, null, 8, PokedexColor.WHITE, 2.2, 800.0, null, null, 492),
                PokemonSeedEntry.pokemon(897, "Spectrier", PokemonType.GHOST, null, 8, PokedexColor.BLACK, 2.0, 44.5, null, null, 493),
                PokemonSeedEntry.pokemon(898, "Calyrex", PokemonType.PSYCHIC, PokemonType.GRASS, 8, PokedexColor.GREEN, 1.1, 7.7, null, null, 494),
                PokemonSeedEntry.pokemon(899, "Wyrdeer", PokemonType.NORMAL, PokemonType.PSYCHIC, 8, PokedexColor.GRAY, 1.8, 95.1, EvolutionStage.SECOND_STAGE, null, 123),
                PokemonSeedEntry.pokemon(900, "Kleavor", PokemonType.BUG, PokemonType.ROCK, 8, PokedexColor.BROWN, 1.8, 89.0, EvolutionStage.SECOND_STAGE, null, 57),
                PokemonSeedEntry.pokemon(901, "Ursaluna", PokemonType.GROUND, PokemonType.NORMAL, 8, PokedexColor.BROWN, 2.4, 290.0, EvolutionStage.SECOND_STAGE, null, 114),
                PokemonSeedEntry.pokemon(902, "Basculegion", PokemonType.WATER, PokemonType.GHOST, 8, PokedexColor.GREEN, 3.0, 110.0, EvolutionStage.SECOND_STAGE, null, 294),
                PokemonSeedEntry.pokemon(903, "Sneasler", PokemonType.FIGHTING, PokemonType.POISON, 8, PokedexColor.GRAY, 1.3, 43.0, EvolutionStage.SECOND_STAGE, null, 113),
                PokemonSeedEntry.pokemon(904, "Overqwil", PokemonType.DARK, PokemonType.POISON, 8, PokedexColor.BLACK, 2.5, 60.5, EvolutionStage.SECOND_STAGE, null, 109),
                PokemonSeedEntry.pokemon(905, "Enamorus", PokemonType.FAIRY, PokemonType.FLYING, 8, PokedexColor.PINK, 1.6, 48.0, null, null, 495)
        );
    }
}
