package com.svc.pokeguessteam.config.seed;

import com.svc.pokeguessteam.model.enums.EvolutionStage;
import com.svc.pokeguessteam.model.enums.PokedexColor;
import com.svc.pokeguessteam.model.enums.PokemonType;

import java.util.List;

public final class Generation7Seed {

    private Generation7Seed() {
    }

    public static List<PokemonSeedEntry> entries() {
        return List.of(
                PokemonSeedEntry.pokemon(722, "Rowlet", PokemonType.GRASS, PokemonType.FLYING, 7, PokedexColor.BROWN, 0.3, 1.5, EvolutionStage.BASE, 17, 389),
                PokemonSeedEntry.pokemon(723, "Dartrix", PokemonType.GRASS, PokemonType.FLYING, 7, PokedexColor.BROWN, 0.7, 16.0, EvolutionStage.FIRST_STAGE, 34, 389),
                PokemonSeedEntry.pokemon(724, "Decidueye", PokemonType.GRASS, PokemonType.GHOST, 7, PokedexColor.BROWN, 1.6, 36.6, EvolutionStage.SECOND_STAGE, null, 389),
                PokemonSeedEntry.pokemon(725, "Litten", PokemonType.FIRE, null, 7, PokedexColor.RED, 0.4, 4.3, EvolutionStage.BASE, 17, 390),
                PokemonSeedEntry.pokemon(726, "Torracat", PokemonType.FIRE, null, 7, PokedexColor.RED, 0.7, 25.0, EvolutionStage.FIRST_STAGE, 34, 390),
                PokemonSeedEntry.pokemon(727, "Incineroar", PokemonType.FIRE, PokemonType.DARK, 7, PokedexColor.RED, 1.8, 83.0, EvolutionStage.SECOND_STAGE, null, 390),
                PokemonSeedEntry.pokemon(728, "Popplio", PokemonType.WATER, null, 7, PokedexColor.BLUE, 0.4, 7.5, EvolutionStage.BASE, 17, 391),
                PokemonSeedEntry.pokemon(729, "Brionne", PokemonType.WATER, null, 7, PokedexColor.BLUE, 0.6, 17.5, EvolutionStage.FIRST_STAGE, 34, 391),
                PokemonSeedEntry.pokemon(730, "Primarina", PokemonType.WATER, PokemonType.FAIRY, 7, PokedexColor.BLUE, 1.8, 44.0, EvolutionStage.SECOND_STAGE, null, 391),
                PokemonSeedEntry.pokemon(731, "Pikipek", PokemonType.NORMAL, PokemonType.FLYING, 7, PokedexColor.BLACK, 0.3, 1.2, EvolutionStage.BASE, 14, 392),
                PokemonSeedEntry.pokemon(732, "Trumbeak", PokemonType.NORMAL, PokemonType.FLYING, 7, PokedexColor.BLACK, 0.6, 14.8, EvolutionStage.FIRST_STAGE, 28, 392),
                PokemonSeedEntry.pokemon(733, "Toucannon", PokemonType.NORMAL, PokemonType.FLYING, 7, PokedexColor.BLACK, 1.1, 26.0, EvolutionStage.SECOND_STAGE, null, 392),
                PokemonSeedEntry.pokemon(734, "Yungoos", PokemonType.NORMAL, null, 7, PokedexColor.BROWN, 0.4, 6.0, EvolutionStage.BASE, 20, 393),
                PokemonSeedEntry.pokemon(735, "Gumshoos", PokemonType.NORMAL, null, 7, PokedexColor.BROWN, 0.7, 14.2, EvolutionStage.SECOND_STAGE, null, 393),
                PokemonSeedEntry.pokemon(736, "Grubbin", PokemonType.BUG, null, 7, PokedexColor.GRAY, 0.4, 4.4, EvolutionStage.BASE, 20, 394),
                PokemonSeedEntry.pokemon(737, "Charjabug", PokemonType.BUG, PokemonType.ELECTRIC, 7, PokedexColor.GREEN, 0.5, 10.5, EvolutionStage.FIRST_STAGE, null, 394),
                PokemonSeedEntry.pokemon(738, "Vikavolt", PokemonType.BUG, PokemonType.ELECTRIC, 7, PokedexColor.BLUE, 1.5, 45.0, EvolutionStage.SECOND_STAGE, null, 394),
                PokemonSeedEntry.pokemon(739, "Crabrawler", PokemonType.FIGHTING, null, 7, PokedexColor.PURPLE, 0.6, 7.0, EvolutionStage.BASE, null, 395),
                PokemonSeedEntry.pokemon(740, "Crabominable", PokemonType.FIGHTING, PokemonType.ICE, 7, PokedexColor.WHITE, 1.7, 180.0, EvolutionStage.SECOND_STAGE, null, 395),
                PokemonSeedEntry.pokemon(741, "Oricorio", PokemonType.FIRE, PokemonType.FLYING, 7, PokedexColor.RED, 0.6, 3.4, null, null, 396),
                PokemonSeedEntry.pokemon(742, "Cutiefly", PokemonType.BUG, PokemonType.FAIRY, 7, PokedexColor.YELLOW, 0.1, 0.2, EvolutionStage.BASE, 25, 397),
                PokemonSeedEntry.pokemon(743, "Ribombee", PokemonType.BUG, PokemonType.FAIRY, 7, PokedexColor.YELLOW, 0.2, 0.5, EvolutionStage.SECOND_STAGE, null, 397),
                PokemonSeedEntry.pokemon(744, "Rockruff", PokemonType.ROCK, null, 7, PokedexColor.BROWN, 0.5, 9.2, EvolutionStage.BASE, 25, 398),
                PokemonSeedEntry.pokemon(745, "Lycanroc", PokemonType.ROCK, null, 7, PokedexColor.BROWN, 0.8, 25.0, EvolutionStage.SECOND_STAGE, null, 398),
                PokemonSeedEntry.pokemon(746, "Wishiwashi", PokemonType.WATER, null, 7, PokedexColor.BLUE, 0.2, 0.3, null, null, 399),
                PokemonSeedEntry.pokemon(747, "Mareanie", PokemonType.POISON, PokemonType.WATER, 7, PokedexColor.BLUE, 0.4, 8.0, EvolutionStage.BASE, 38, 400),
                PokemonSeedEntry.pokemon(748, "Toxapex", PokemonType.POISON, PokemonType.WATER, 7, PokedexColor.BLUE, 0.7, 14.5, EvolutionStage.SECOND_STAGE, null, 400),
                PokemonSeedEntry.pokemon(749, "Mudbray", PokemonType.GROUND, null, 7, PokedexColor.BROWN, 1.0, 110.0, EvolutionStage.BASE, 30, 401),
                PokemonSeedEntry.pokemon(750, "Mudsdale", PokemonType.GROUND, null, 7, PokedexColor.BROWN, 2.5, 920.0, EvolutionStage.SECOND_STAGE, null, 401),
                PokemonSeedEntry.pokemon(751, "Dewpider", PokemonType.WATER, PokemonType.BUG, 7, PokedexColor.GREEN, 0.3, 4.0, EvolutionStage.BASE, 22, 402),
                PokemonSeedEntry.pokemon(752, "Araquanid", PokemonType.WATER, PokemonType.BUG, 7, PokedexColor.GREEN, 1.8, 82.0, EvolutionStage.SECOND_STAGE, null, 402),
                PokemonSeedEntry.pokemon(753, "Fomantis", PokemonType.GRASS, null, 7, PokedexColor.PINK, 0.3, 1.5, EvolutionStage.BASE, 34, 403),
                PokemonSeedEntry.pokemon(754, "Lurantis", PokemonType.GRASS, null, 7, PokedexColor.PINK, 0.9, 18.5, EvolutionStage.SECOND_STAGE, null, 403),
                PokemonSeedEntry.pokemon(755, "Morelull", PokemonType.GRASS, PokemonType.FAIRY, 7, PokedexColor.PURPLE, 0.2, 1.5, EvolutionStage.BASE, 24, 404),
                PokemonSeedEntry.pokemon(756, "Shiinotic", PokemonType.GRASS, PokemonType.FAIRY, 7, PokedexColor.PURPLE, 1.0, 11.5, EvolutionStage.SECOND_STAGE, null, 404),
                PokemonSeedEntry.pokemon(757, "Salandit", PokemonType.POISON, PokemonType.FIRE, 7, PokedexColor.BLACK, 0.6, 4.8, EvolutionStage.BASE, 33, 405),
                PokemonSeedEntry.pokemon(758, "Salazzle", PokemonType.POISON, PokemonType.FIRE, 7, PokedexColor.BLACK, 1.2, 22.2, EvolutionStage.SECOND_STAGE, null, 405),
                PokemonSeedEntry.pokemon(759, "Stufful", PokemonType.NORMAL, PokemonType.FIGHTING, 7, PokedexColor.PINK, 0.5, 6.8, EvolutionStage.BASE, 27, 406),
                PokemonSeedEntry.pokemon(760, "Bewear", PokemonType.NORMAL, PokemonType.FIGHTING, 7, PokedexColor.PINK, 2.1, 135.0, EvolutionStage.SECOND_STAGE, null, 406),
                PokemonSeedEntry.pokemon(761, "Bounsweet", PokemonType.GRASS, null, 7, PokedexColor.PURPLE, 0.3, 3.2, EvolutionStage.BASE, 18, 407),
                PokemonSeedEntry.pokemon(762, "Steenee", PokemonType.GRASS, null, 7, PokedexColor.PURPLE, 0.7, 8.2, EvolutionStage.FIRST_STAGE, null, 407),
                PokemonSeedEntry.pokemon(763, "Tsareena", PokemonType.GRASS, null, 7, PokedexColor.PURPLE, 1.2, 21.4, EvolutionStage.SECOND_STAGE, null, 407),
                PokemonSeedEntry.pokemon(764, "Comfey", PokemonType.FAIRY, null, 7, PokedexColor.GREEN, 0.1, 0.3, null, null, 408),
                PokemonSeedEntry.pokemon(765, "Oranguru", PokemonType.NORMAL, PokemonType.PSYCHIC, 7, PokedexColor.WHITE, 1.5, 76.0, null, null, 409),
                PokemonSeedEntry.pokemon(766, "Passimian", PokemonType.FIGHTING, null, 7, PokedexColor.WHITE, 2.0, 82.8, null, null, 410),
                PokemonSeedEntry.pokemon(767, "Wimpod", PokemonType.BUG, PokemonType.WATER, 7, PokedexColor.GRAY, 0.5, 12.0, EvolutionStage.BASE, 30, 411),
                PokemonSeedEntry.pokemon(768, "Golisopod", PokemonType.BUG, PokemonType.WATER, 7, PokedexColor.GRAY, 2.0, 108.0, EvolutionStage.SECOND_STAGE, null, 411),
                PokemonSeedEntry.pokemon(769, "Sandygast", PokemonType.GHOST, PokemonType.GROUND, 7, PokedexColor.BROWN, 0.5, 70.0, EvolutionStage.BASE, 42, 412),
                PokemonSeedEntry.pokemon(770, "Palossand", PokemonType.GHOST, PokemonType.GROUND, 7, PokedexColor.BROWN, 1.3, 250.0, EvolutionStage.SECOND_STAGE, null, 412),
                PokemonSeedEntry.pokemon(771, "Pyukumuku", PokemonType.WATER, null, 7, PokedexColor.BLACK, 0.3, 1.2, null, null, 413),
                PokemonSeedEntry.pokemon(772, "Type: Null", PokemonType.NORMAL, null, 7, PokedexColor.GRAY, 1.9, 120.5, EvolutionStage.BASE, null, 414),
                PokemonSeedEntry.pokemon(773, "Silvally", PokemonType.NORMAL, null, 7, PokedexColor.GRAY, 2.3, 100.5, EvolutionStage.SECOND_STAGE, null, 414),
                PokemonSeedEntry.pokemon(774, "Minior", PokemonType.ROCK, PokemonType.FLYING, 7, PokedexColor.BROWN, 0.3, 40.0, null, null, 415),
                PokemonSeedEntry.pokemon(775, "Komala", PokemonType.NORMAL, null, 7, PokedexColor.BLUE, 0.4, 19.9, null, null, 416),
                PokemonSeedEntry.pokemon(776, "Turtonator", PokemonType.FIRE, PokemonType.DRAGON, 7, PokedexColor.RED, 2.0, 212.0, null, null, 417),
                PokemonSeedEntry.pokemon(777, "Togedemaru", PokemonType.ELECTRIC, PokemonType.STEEL, 7, PokedexColor.GRAY, 0.3, 3.3, null, null, 418),
                PokemonSeedEntry.pokemon(778, "Mimikyu", PokemonType.GHOST, PokemonType.FAIRY, 7, PokedexColor.YELLOW, 0.2, 0.7, null, null, 419),
                PokemonSeedEntry.pokemon(779, "Bruxish", PokemonType.WATER, PokemonType.PSYCHIC, 7, PokedexColor.PINK, 0.9, 19.0, null, null, 420),
                PokemonSeedEntry.pokemon(780, "Drampa", PokemonType.NORMAL, PokemonType.DRAGON, 7, PokedexColor.WHITE, 3.0, 185.0, null, null, 421),
                PokemonSeedEntry.pokemon(781, "Dhelmise", PokemonType.GHOST, PokemonType.GRASS, 7, PokedexColor.GREEN, 3.9, 210.0, null, null, 422),
                PokemonSeedEntry.pokemon(782, "Jangmo-o", PokemonType.DRAGON, null, 7, PokedexColor.GRAY, 0.6, 29.7, EvolutionStage.BASE, 35, 423),
                PokemonSeedEntry.pokemon(783, "Hakamo-o", PokemonType.DRAGON, PokemonType.FIGHTING, 7, PokedexColor.GRAY, 1.2, 47.0, EvolutionStage.FIRST_STAGE, 45, 423),
                PokemonSeedEntry.pokemon(784, "Kommo-o", PokemonType.DRAGON, PokemonType.FIGHTING, 7, PokedexColor.GRAY, 1.6, 78.2, EvolutionStage.SECOND_STAGE, null, 423),
                PokemonSeedEntry.pokemon(785, "Tapu Koko", PokemonType.ELECTRIC, PokemonType.FAIRY, 7, PokedexColor.YELLOW, 1.8, 20.5, null, null, 424),
                PokemonSeedEntry.pokemon(786, "Tapu Lele", PokemonType.PSYCHIC, PokemonType.FAIRY, 7, PokedexColor.PINK, 1.2, 18.6, null, null, 425),
                PokemonSeedEntry.pokemon(787, "Tapu Bulu", PokemonType.GRASS, PokemonType.FAIRY, 7, PokedexColor.RED, 1.9, 45.5, null, null, 426),
                PokemonSeedEntry.pokemon(788, "Tapu Fini", PokemonType.WATER, PokemonType.FAIRY, 7, PokedexColor.PURPLE, 1.3, 21.2, null, null, 427),
                PokemonSeedEntry.pokemon(789, "Cosmog", PokemonType.PSYCHIC, null, 7, PokedexColor.BLUE, 0.2, 0.1, EvolutionStage.BASE, 43, 428),
                PokemonSeedEntry.pokemon(790, "Cosmoem", PokemonType.PSYCHIC, null, 7, PokedexColor.BLUE, 0.1, 999.9, EvolutionStage.FIRST_STAGE, 53, 428),
                PokemonSeedEntry.pokemon(791, "Solgaleo", PokemonType.PSYCHIC, PokemonType.STEEL, 7, PokedexColor.WHITE, 3.4, 230.0, EvolutionStage.SECOND_STAGE, null, 428),
                PokemonSeedEntry.pokemon(792, "Lunala", PokemonType.PSYCHIC, PokemonType.GHOST, 7, PokedexColor.PURPLE, 4.0, 120.0, EvolutionStage.SECOND_STAGE, null, 429),
                PokemonSeedEntry.pokemon(793, "Nihilego", PokemonType.ROCK, PokemonType.POISON, 7, PokedexColor.WHITE, 1.2, 55.5, null, null, 430),
                PokemonSeedEntry.pokemon(794, "Buzzwole", PokemonType.BUG, PokemonType.FIGHTING, 7, PokedexColor.RED, 2.4, 333.6, null, null, 431),
                PokemonSeedEntry.pokemon(795, "Pheromosa", PokemonType.BUG, PokemonType.FIGHTING, 7, PokedexColor.WHITE, 1.8, 25.0, null, null, 432),
                PokemonSeedEntry.pokemon(796, "Xurkitree", PokemonType.ELECTRIC, null, 7, PokedexColor.BLACK, 3.8, 100.0, null, null, 433),
                PokemonSeedEntry.pokemon(797, "Celesteela", PokemonType.STEEL, PokemonType.FLYING, 7, PokedexColor.GREEN, 9.2, 999.9, null, null, 434),
                PokemonSeedEntry.pokemon(798, "Kartana", PokemonType.GRASS, PokemonType.STEEL, 7, PokedexColor.WHITE, 0.3, 0.1, null, null, 435),
                PokemonSeedEntry.pokemon(799, "Guzzlord", PokemonType.DARK, PokemonType.DRAGON, 7, PokedexColor.BLACK, 5.5, 888.0, null, null, 436),
                PokemonSeedEntry.pokemon(800, "Necrozma", PokemonType.PSYCHIC, null, 7, PokedexColor.BLACK, 2.4, 230.0, null, null, 437),
                PokemonSeedEntry.pokemon(801, "Magearna", PokemonType.STEEL, PokemonType.FAIRY, 7, PokedexColor.GRAY, 1.0, 80.5, null, null, 438),
                PokemonSeedEntry.pokemon(802, "Marshadow", PokemonType.FIGHTING, PokemonType.GHOST, 7, PokedexColor.GRAY, 0.7, 22.2, null, null, 439),
                PokemonSeedEntry.pokemon(803, "Poipole", PokemonType.POISON, null, 7, PokedexColor.PURPLE, 0.6, 1.8, EvolutionStage.BASE, null, 440),
                PokemonSeedEntry.pokemon(804, "Naganadel", PokemonType.POISON, PokemonType.DRAGON, 7, PokedexColor.PURPLE, 3.6, 150.0, EvolutionStage.SECOND_STAGE, null, 440),
                PokemonSeedEntry.pokemon(805, "Stakataka", PokemonType.ROCK, PokemonType.STEEL, 7, PokedexColor.GRAY, 5.5, 820.0, null, null, 441),
                PokemonSeedEntry.pokemon(806, "Blacephalon", PokemonType.FIRE, PokemonType.GHOST, 7, PokedexColor.WHITE, 1.8, 13.0, null, null, 442),
                PokemonSeedEntry.pokemon(807, "Zeraora", PokemonType.ELECTRIC, null, 7, PokedexColor.YELLOW, 1.5, 44.5, null, null, 443),
                PokemonSeedEntry.pokemon(808, "Meltan", PokemonType.STEEL, null, 7, PokedexColor.GRAY, 0.2, 8.0, null, null, 444),
                PokemonSeedEntry.pokemon(809, "Melmetal", PokemonType.STEEL, null, 7, PokedexColor.GRAY, 2.5, 800.0, EvolutionStage.SECOND_STAGE, null, 445)
        );
    }
}
