package com.svc.pokeguessteam.config.seed;

import com.svc.pokeguessteam.model.enums.EvolutionStage;
import com.svc.pokeguessteam.model.enums.PokedexColor;
import com.svc.pokeguessteam.model.enums.PokemonType;

import java.util.List;

public final class Generation4Seed {

    private Generation4Seed() {
    }

    public static List<PokemonSeedEntry> entries() {
        return List.of(
                PokemonSeedEntry.pokemon(387, "Turtwig", PokemonType.GRASS, null, 4, PokedexColor.GREEN, 0.4, 10.2, EvolutionStage.BASE, 18, 217),
                PokemonSeedEntry.pokemon(388, "Grotle", PokemonType.GRASS, null, 4, PokedexColor.GREEN, 1.1, 97.0, EvolutionStage.FIRST_STAGE, 32, 217),
                PokemonSeedEntry.pokemon(389, "Torterra", PokemonType.GRASS, PokemonType.GROUND, 4, PokedexColor.GREEN, 2.2, 310.0, EvolutionStage.SECOND_STAGE, null, 217),
                PokemonSeedEntry.pokemon(390, "Chimchar", PokemonType.FIRE, null, 4, PokedexColor.BROWN, 0.5, 6.2, EvolutionStage.BASE, 14, 218),
                PokemonSeedEntry.pokemon(391, "Monferno", PokemonType.FIRE, PokemonType.FIGHTING, 4, PokedexColor.BROWN, 0.9, 22.0, EvolutionStage.FIRST_STAGE, 36, 218),
                PokemonSeedEntry.pokemon(392, "Infernape", PokemonType.FIRE, PokemonType.FIGHTING, 4, PokedexColor.BROWN, 1.2, 55.0, EvolutionStage.SECOND_STAGE, null, 218),
                PokemonSeedEntry.pokemon(393, "Piplup", PokemonType.WATER, null, 4, PokedexColor.BLUE, 0.4, 5.2, EvolutionStage.BASE, 16, 219),
                PokemonSeedEntry.pokemon(394, "Prinplup", PokemonType.WATER, null, 4, PokedexColor.BLUE, 0.8, 23.0, EvolutionStage.FIRST_STAGE, 36, 219),
                PokemonSeedEntry.pokemon(395, "Empoleon", PokemonType.WATER, PokemonType.STEEL, 4, PokedexColor.BLUE, 1.7, 84.5, EvolutionStage.SECOND_STAGE, null, 219),
                PokemonSeedEntry.pokemon(396, "Starly", PokemonType.NORMAL, PokemonType.FLYING, 4, PokedexColor.BROWN, 0.3, 2.0, EvolutionStage.BASE, 14, 220),
                PokemonSeedEntry.pokemon(397, "Staravia", PokemonType.NORMAL, PokemonType.FLYING, 4, PokedexColor.BROWN, 0.6, 15.5, EvolutionStage.FIRST_STAGE, 34, 220),
                PokemonSeedEntry.pokemon(398, "Staraptor", PokemonType.NORMAL, PokemonType.FLYING, 4, PokedexColor.BROWN, 1.2, 24.9, EvolutionStage.SECOND_STAGE, null, 220),
                PokemonSeedEntry.pokemon(399, "Bidoof", PokemonType.NORMAL, null, 4, PokedexColor.BROWN, 0.5, 20.0, EvolutionStage.BASE, 15, 221),
                PokemonSeedEntry.pokemon(400, "Bibarel", PokemonType.NORMAL, PokemonType.WATER, 4, PokedexColor.BROWN, 1.0, 31.5, EvolutionStage.SECOND_STAGE, null, 221),
                PokemonSeedEntry.pokemon(401, "Kricketot", PokemonType.BUG, null, 4, PokedexColor.RED, 0.3, 2.2, EvolutionStage.BASE, 10, 222),
                PokemonSeedEntry.pokemon(402, "Kricketune", PokemonType.BUG, null, 4, PokedexColor.RED, 1.0, 25.5, EvolutionStage.SECOND_STAGE, null, 222),
                PokemonSeedEntry.pokemon(403, "Shinx", PokemonType.ELECTRIC, null, 4, PokedexColor.BLUE, 0.5, 9.5, EvolutionStage.BASE, 15, 223),
                PokemonSeedEntry.pokemon(404, "Luxio", PokemonType.ELECTRIC, null, 4, PokedexColor.BLUE, 0.9, 30.5, EvolutionStage.FIRST_STAGE, 30, 223),
                PokemonSeedEntry.pokemon(405, "Luxray", PokemonType.ELECTRIC, null, 4, PokedexColor.BLUE, 1.4, 42.0, EvolutionStage.SECOND_STAGE, null, 223),
                PokemonSeedEntry.pokemon(406, "Budew", PokemonType.GRASS, PokemonType.POISON, 4, PokedexColor.GREEN, 0.2, 1.2, EvolutionStage.BASE, null, 224),
                PokemonSeedEntry.pokemon(407, "Roserade", PokemonType.GRASS, PokemonType.POISON, 4, PokedexColor.GREEN, 0.9, 14.5, EvolutionStage.SECOND_STAGE, null, 224),
                PokemonSeedEntry.pokemon(408, "Cranidos", PokemonType.ROCK, null, 4, PokedexColor.BLUE, 0.9, 31.5, EvolutionStage.BASE, 30, 225),
                PokemonSeedEntry.pokemon(409, "Rampardos", PokemonType.ROCK, null, 4, PokedexColor.BLUE, 1.6, 102.5, EvolutionStage.SECOND_STAGE, null, 225),
                PokemonSeedEntry.pokemon(410, "Shieldon", PokemonType.ROCK, PokemonType.STEEL, 4, PokedexColor.GRAY, 0.5, 57.0, EvolutionStage.BASE, 30, 226),
                PokemonSeedEntry.pokemon(411, "Bastiodon", PokemonType.ROCK, PokemonType.STEEL, 4, PokedexColor.GRAY, 1.3, 149.5, EvolutionStage.SECOND_STAGE, null, 226),
                PokemonSeedEntry.pokemon(412, "Burmy", PokemonType.BUG, null, 4, PokedexColor.GREEN, 0.2, 3.4, EvolutionStage.BASE, 20, 227),
                PokemonSeedEntry.pokemon(413, "Wormadam", PokemonType.BUG, PokemonType.GRASS, 4, PokedexColor.GREEN, 0.5, 6.5, EvolutionStage.SECOND_STAGE, null, 227),
                PokemonSeedEntry.pokemon(414, "Mothim", PokemonType.BUG, PokemonType.FLYING, 4, PokedexColor.YELLOW, 0.9, 23.3, EvolutionStage.SECOND_STAGE, null, 228),
                PokemonSeedEntry.pokemon(415, "Combee", PokemonType.BUG, PokemonType.FLYING, 4, PokedexColor.YELLOW, 0.3, 5.5, EvolutionStage.BASE, 21, 229),
                PokemonSeedEntry.pokemon(416, "Vespiquen", PokemonType.BUG, PokemonType.FLYING, 4, PokedexColor.YELLOW, 1.2, 38.5, EvolutionStage.SECOND_STAGE, null, 229),
                PokemonSeedEntry.pokemon(417, "Pachirisu", PokemonType.ELECTRIC, null, 4, PokedexColor.WHITE, 0.4, 3.9, null, null, 230),
                PokemonSeedEntry.pokemon(418, "Buizel", PokemonType.WATER, null, 4, PokedexColor.BROWN, 0.7, 29.5, EvolutionStage.BASE, 26, 231),
                PokemonSeedEntry.pokemon(419, "Floatzel", PokemonType.WATER, null, 4, PokedexColor.BROWN, 1.1, 33.5, EvolutionStage.SECOND_STAGE, null, 231),
                PokemonSeedEntry.pokemon(420, "Cherubi", PokemonType.GRASS, null, 4, PokedexColor.PINK, 0.4, 3.3, EvolutionStage.BASE, 25, 232),
                PokemonSeedEntry.pokemon(421, "Cherrim", PokemonType.GRASS, null, 4, PokedexColor.PURPLE, 0.5, 9.3, EvolutionStage.SECOND_STAGE, null, 232),
                PokemonSeedEntry.pokemon(422, "Shellos", PokemonType.WATER, null, 4, PokedexColor.PURPLE, 0.3, 6.3, EvolutionStage.BASE, 30, 233),
                PokemonSeedEntry.pokemon(423, "Gastrodon", PokemonType.WATER, PokemonType.GROUND, 4, PokedexColor.PURPLE, 0.9, 29.9, EvolutionStage.SECOND_STAGE, null, 233),
                PokemonSeedEntry.pokemon(424, "Ambipom", PokemonType.NORMAL, null, 4, PokedexColor.PURPLE, 1.2, 20.3, EvolutionStage.SECOND_STAGE, null, 96),
                PokemonSeedEntry.pokemon(425, "Drifloon", PokemonType.GHOST, PokemonType.FLYING, 4, PokedexColor.PURPLE, 0.4, 1.2, EvolutionStage.BASE, 28, 234),
                PokemonSeedEntry.pokemon(426, "Drifblim", PokemonType.GHOST, PokemonType.FLYING, 4, PokedexColor.PURPLE, 1.2, 15.0, EvolutionStage.SECOND_STAGE, null, 234),
                PokemonSeedEntry.pokemon(427, "Buneary", PokemonType.NORMAL, null, 4, PokedexColor.BROWN, 0.4, 5.5, EvolutionStage.BASE, null, 235),
                PokemonSeedEntry.pokemon(428, "Lopunny", PokemonType.NORMAL, null, 4, PokedexColor.BROWN, 1.2, 33.3, EvolutionStage.SECOND_STAGE, null, 235),
                PokemonSeedEntry.pokemon(429, "Mismagius", PokemonType.GHOST, null, 4, PokedexColor.PURPLE, 0.9, 4.4, EvolutionStage.SECOND_STAGE, null, 102),
                PokemonSeedEntry.pokemon(430, "Honchkrow", PokemonType.DARK, PokemonType.FLYING, 4, PokedexColor.BLACK, 0.9, 27.3, EvolutionStage.SECOND_STAGE, null, 101),
                PokemonSeedEntry.pokemon(431, "Glameow", PokemonType.NORMAL, null, 4, PokedexColor.GRAY, 0.5, 3.9, EvolutionStage.BASE, 38, 236),
                PokemonSeedEntry.pokemon(432, "Purugly", PokemonType.NORMAL, null, 4, PokedexColor.GRAY, 1.0, 43.8, EvolutionStage.SECOND_STAGE, null, 236),
                PokemonSeedEntry.pokemon(433, "Chingling", PokemonType.PSYCHIC, null, 4, PokedexColor.YELLOW, 0.2, 0.6, EvolutionStage.BASE, null, 237),
                PokemonSeedEntry.pokemon(434, "Stunky", PokemonType.POISON, PokemonType.DARK, 4, PokedexColor.PURPLE, 0.4, 19.2, EvolutionStage.BASE, 34, 238),
                PokemonSeedEntry.pokemon(435, "Skuntank", PokemonType.POISON, PokemonType.DARK, 4, PokedexColor.PURPLE, 1.0, 38.0, EvolutionStage.SECOND_STAGE, null, 238),
                PokemonSeedEntry.pokemon(436, "Bronzor", PokemonType.STEEL, PokemonType.PSYCHIC, 4, PokedexColor.GREEN, 0.5, 60.5, EvolutionStage.BASE, 33, 239),
                PokemonSeedEntry.pokemon(437, "Bronzong", PokemonType.STEEL, PokemonType.PSYCHIC, 4, PokedexColor.GREEN, 1.3, 187.0, EvolutionStage.SECOND_STAGE, null, 239),
                PokemonSeedEntry.pokemon(438, "Bonsly", PokemonType.ROCK, null, 4, PokedexColor.BROWN, 0.5, 15.0, EvolutionStage.BASE, null, 240),
                PokemonSeedEntry.pokemon(439, "Mime Jr.", PokemonType.PSYCHIC, PokemonType.FAIRY, 4, PokedexColor.PINK, 0.6, 13.0, EvolutionStage.BASE, null, 241),
                PokemonSeedEntry.pokemon(440, "Happiny", PokemonType.NORMAL, null, 4, PokedexColor.PINK, 0.6, 24.4, EvolutionStage.BASE, null, 242),
                PokemonSeedEntry.pokemon(441, "Chatot", PokemonType.NORMAL, PokemonType.FLYING, 4, PokedexColor.BLACK, 0.5, 1.9, null, null, 243),
                PokemonSeedEntry.pokemon(442, "Spiritomb", PokemonType.GHOST, PokemonType.DARK, 4, PokedexColor.PURPLE, 1.0, 108.0, null, null, 244),
                PokemonSeedEntry.pokemon(443, "Gible", PokemonType.DRAGON, PokemonType.GROUND, 4, PokedexColor.BLUE, 0.7, 20.5, EvolutionStage.BASE, 24, 245),
                PokemonSeedEntry.pokemon(444, "Gabite", PokemonType.DRAGON, PokemonType.GROUND, 4, PokedexColor.BLUE, 1.4, 56.0, EvolutionStage.FIRST_STAGE, 48, 245),
                PokemonSeedEntry.pokemon(445, "Garchomp", PokemonType.DRAGON, PokemonType.GROUND, 4, PokedexColor.BLUE, 1.9, 95.0, EvolutionStage.SECOND_STAGE, null, 245),
                PokemonSeedEntry.pokemon(446, "Munchlax", PokemonType.NORMAL, null, 4, PokedexColor.BLACK, 0.6, 105.0, EvolutionStage.BASE, null, 246),
                PokemonSeedEntry.pokemon(447, "Riolu", PokemonType.FIGHTING, null, 4, PokedexColor.BLUE, 0.7, 20.2, EvolutionStage.BASE, null, 247),
                PokemonSeedEntry.pokemon(448, "Lucario", PokemonType.FIGHTING, PokemonType.STEEL, 4, PokedexColor.BLUE, 1.2, 54.0, EvolutionStage.SECOND_STAGE, null, 247),
                PokemonSeedEntry.pokemon(449, "Hippopotas", PokemonType.GROUND, null, 4, PokedexColor.BROWN, 0.8, 49.5, EvolutionStage.BASE, 34, 248),
                PokemonSeedEntry.pokemon(450, "Hippowdon", PokemonType.GROUND, null, 4, PokedexColor.BROWN, 2.0, 300.0, EvolutionStage.SECOND_STAGE, null, 248),
                PokemonSeedEntry.pokemon(451, "Skorupi", PokemonType.POISON, PokemonType.BUG, 4, PokedexColor.PURPLE, 0.8, 12.0, EvolutionStage.BASE, 40, 249),
                PokemonSeedEntry.pokemon(452, "Drapion", PokemonType.POISON, PokemonType.DARK, 4, PokedexColor.PURPLE, 1.3, 61.5, EvolutionStage.SECOND_STAGE, null, 249),
                PokemonSeedEntry.pokemon(453, "Croagunk", PokemonType.POISON, PokemonType.FIGHTING, 4, PokedexColor.BLUE, 0.7, 23.0, EvolutionStage.BASE, 37, 250),
                PokemonSeedEntry.pokemon(454, "Toxicroak", PokemonType.POISON, PokemonType.FIGHTING, 4, PokedexColor.BLUE, 1.3, 44.4, EvolutionStage.SECOND_STAGE, null, 250),
                PokemonSeedEntry.pokemon(455, "Carnivine", PokemonType.GRASS, null, 4, PokedexColor.GREEN, 1.4, 27.0, null, null, 251),
                PokemonSeedEntry.pokemon(456, "Finneon", PokemonType.WATER, null, 4, PokedexColor.BLUE, 0.4, 7.0, EvolutionStage.BASE, 31, 252),
                PokemonSeedEntry.pokemon(457, "Lumineon", PokemonType.WATER, null, 4, PokedexColor.BLUE, 1.2, 24.0, EvolutionStage.SECOND_STAGE, null, 252),
                PokemonSeedEntry.pokemon(458, "Mantyke", PokemonType.WATER, PokemonType.FLYING, 4, PokedexColor.BLUE, 1.0, 65.0, EvolutionStage.BASE, null, 253),
                PokemonSeedEntry.pokemon(459, "Snover", PokemonType.GRASS, PokemonType.ICE, 4, PokedexColor.WHITE, 1.0, 50.5, EvolutionStage.BASE, 40, 254),
                PokemonSeedEntry.pokemon(460, "Abomasnow", PokemonType.GRASS, PokemonType.ICE, 4, PokedexColor.WHITE, 2.2, 135.5, EvolutionStage.SECOND_STAGE, null, 254),
                PokemonSeedEntry.pokemon(461, "Weavile", PokemonType.DARK, PokemonType.ICE, 4, PokedexColor.BLACK, 1.1, 34.0, EvolutionStage.SECOND_STAGE, null, 112),
                PokemonSeedEntry.pokemon(462, "Magnezone", PokemonType.ELECTRIC, PokemonType.STEEL, 4, PokedexColor.GRAY, 1.2, 180.0, EvolutionStage.SECOND_STAGE, null, 35),
                PokemonSeedEntry.pokemon(463, "Lickilicky", PokemonType.NORMAL, null, 4, PokedexColor.PINK, 1.7, 140.0, EvolutionStage.SECOND_STAGE, null, 48),
                PokemonSeedEntry.pokemon(464, "Rhyperior", PokemonType.GROUND, PokemonType.ROCK, 4, PokedexColor.GRAY, 2.4, 282.8, EvolutionStage.SECOND_STAGE, null, 50),
                PokemonSeedEntry.pokemon(465, "Tangrowth", PokemonType.GRASS, null, 4, PokedexColor.BLUE, 2.0, 128.6, EvolutionStage.SECOND_STAGE, null, 51),
                PokemonSeedEntry.pokemon(466, "Electivire", PokemonType.ELECTRIC, null, 4, PokedexColor.YELLOW, 1.8, 138.6, EvolutionStage.SECOND_STAGE, null, 129),
                PokemonSeedEntry.pokemon(467, "Magmortar", PokemonType.FIRE, null, 4, PokedexColor.RED, 1.6, 68.0, EvolutionStage.SECOND_STAGE, null, 130),
                PokemonSeedEntry.pokemon(468, "Togekiss", PokemonType.FAIRY, PokemonType.FLYING, 4, PokedexColor.WHITE, 1.5, 38.0, EvolutionStage.SECOND_STAGE, null, 92),
                PokemonSeedEntry.pokemon(469, "Yanmega", PokemonType.BUG, PokemonType.FLYING, 4, PokedexColor.GREEN, 1.9, 51.5, EvolutionStage.SECOND_STAGE, null, 98),
                PokemonSeedEntry.pokemon(470, "Leafeon", PokemonType.GRASS, null, 4, PokedexColor.GREEN, 1.0, 25.5, EvolutionStage.SECOND_STAGE, null, 68),
                PokemonSeedEntry.pokemon(471, "Glaceon", PokemonType.ICE, null, 4, PokedexColor.BLUE, 0.8, 25.9, EvolutionStage.SECOND_STAGE, null, 69),
                PokemonSeedEntry.pokemon(472, "Gliscor", PokemonType.GROUND, PokemonType.FLYING, 4, PokedexColor.PURPLE, 2.0, 42.5, EvolutionStage.SECOND_STAGE, null, 107),
                PokemonSeedEntry.pokemon(473, "Mamoswine", PokemonType.ICE, PokemonType.GROUND, 4, PokedexColor.BROWN, 2.5, 291.0, EvolutionStage.SECOND_STAGE, null, 116),
                PokemonSeedEntry.pokemon(474, "Porygon-Z", PokemonType.NORMAL, null, 4, PokedexColor.RED, 0.9, 34.0, EvolutionStage.SECOND_STAGE, null, 71),
                PokemonSeedEntry.pokemon(475, "Gallade", PokemonType.PSYCHIC, PokemonType.FIGHTING, 4, PokedexColor.WHITE, 1.6, 52.0, EvolutionStage.SECOND_STAGE, null, 151),
                PokemonSeedEntry.pokemon(476, "Probopass", PokemonType.ROCK, PokemonType.STEEL, 4, PokedexColor.GRAY, 1.4, 340.0, EvolutionStage.SECOND_STAGE, null, 160),
                PokemonSeedEntry.pokemon(477, "Dusknoir", PokemonType.GHOST, null, 4, PokedexColor.BLACK, 2.2, 106.6, EvolutionStage.SECOND_STAGE, null, 194),
                PokemonSeedEntry.pokemon(478, "Froslass", PokemonType.ICE, PokemonType.GHOST, 4, PokedexColor.WHITE, 1.3, 26.6, EvolutionStage.SECOND_STAGE, null, 199),
                PokemonSeedEntry.pokemon(479, "Rotom", PokemonType.ELECTRIC, PokemonType.GHOST, 4, PokedexColor.RED, 0.3, 0.3, null, null, 255),
                PokemonSeedEntry.pokemon(480, "Uxie", PokemonType.PSYCHIC, null, 4, PokedexColor.YELLOW, 0.3, 0.3, null, null, 256),
                PokemonSeedEntry.pokemon(481, "Mesprit", PokemonType.PSYCHIC, null, 4, PokedexColor.PINK, 0.3, 0.3, null, null, 257),
                PokemonSeedEntry.pokemon(482, "Azelf", PokemonType.PSYCHIC, null, 4, PokedexColor.BLUE, 0.3, 0.3, null, null, 258),
                PokemonSeedEntry.pokemon(483, "Dialga", PokemonType.STEEL, PokemonType.DRAGON, 4, PokedexColor.WHITE, 5.4, 683.0, null, null, 259),
                PokemonSeedEntry.pokemon(484, "Palkia", PokemonType.WATER, PokemonType.DRAGON, 4, PokedexColor.PURPLE, 4.2, 336.0, null, null, 260),
                PokemonSeedEntry.pokemon(485, "Heatran", PokemonType.FIRE, PokemonType.STEEL, 4, PokedexColor.BROWN, 1.7, 430.0, null, null, 261),
                PokemonSeedEntry.pokemon(486, "Regigigas", PokemonType.NORMAL, null, 4, PokedexColor.WHITE, 3.7, 420.0, null, null, 262),
                PokemonSeedEntry.pokemon(487, "Giratina", PokemonType.GHOST, PokemonType.DRAGON, 4, PokedexColor.BLACK, 4.5, 750.0, null, null, 263),
                PokemonSeedEntry.pokemon(488, "Cresselia", PokemonType.PSYCHIC, null, 4, PokedexColor.YELLOW, 1.5, 85.6, null, null, 264),
                PokemonSeedEntry.pokemon(489, "Phione", PokemonType.WATER, null, 4, PokedexColor.BLUE, 0.4, 3.1, EvolutionStage.BASE, null, 265),
                PokemonSeedEntry.pokemon(490, "Manaphy", PokemonType.WATER, null, 4, PokedexColor.BLUE, 0.3, 1.4, null, null, 265),
                PokemonSeedEntry.pokemon(491, "Darkrai", PokemonType.DARK, null, 4, PokedexColor.BLACK, 1.5, 50.5, null, null, 266),
                PokemonSeedEntry.pokemon(492, "Shaymin", PokemonType.GRASS, null, 4, PokedexColor.GREEN, 0.2, 2.1, null, null, 267),
                PokemonSeedEntry.pokemon(493, "Arceus", PokemonType.NORMAL, null, 4, PokedexColor.WHITE, 3.2, 320.0, null, null, 268)
        );
    }
}
