package com.svc.pokeguessteam.config.seed;

import com.svc.pokeguessteam.model.enums.EvolutionStage;
import com.svc.pokeguessteam.model.enums.PokedexColor;
import com.svc.pokeguessteam.model.enums.PokemonType;

import java.util.List;

public final class Generation2Seed {

    private Generation2Seed() {
    }

    public static List<PokemonSeedEntry> entries() {
        return List.of(
                PokemonSeedEntry.pokemon(152, "Chikorita", PokemonType.GRASS, null, 2, PokedexColor.GREEN, 0.9, 6.4, EvolutionStage.BASE, 16, 81),
                PokemonSeedEntry.pokemon(153, "Bayleef", PokemonType.GRASS, null, 2, PokedexColor.GREEN, 1.2, 15.8, EvolutionStage.FIRST_STAGE, 32, 81),
                PokemonSeedEntry.pokemon(154, "Meganium", PokemonType.GRASS, null, 2, PokedexColor.GREEN, 1.8, 100.5, EvolutionStage.SECOND_STAGE, null, 81),
                PokemonSeedEntry.pokemon(155, "Cyndaquil", PokemonType.FIRE, null, 2, PokedexColor.YELLOW, 0.5, 7.9, EvolutionStage.BASE, 14, 82),
                PokemonSeedEntry.pokemon(156, "Quilava", PokemonType.FIRE, null, 2, PokedexColor.YELLOW, 0.9, 19.0, EvolutionStage.FIRST_STAGE, 36, 82),
                PokemonSeedEntry.pokemon(157, "Typhlosion", PokemonType.FIRE, null, 2, PokedexColor.YELLOW, 1.7, 79.5, EvolutionStage.SECOND_STAGE, null, 82),
                PokemonSeedEntry.pokemon(158, "Totodile", PokemonType.WATER, null, 2, PokedexColor.BLUE, 0.6, 9.5, EvolutionStage.BASE, 18, 83),
                PokemonSeedEntry.pokemon(159, "Croconaw", PokemonType.WATER, null, 2, PokedexColor.BLUE, 1.1, 25.0, EvolutionStage.FIRST_STAGE, 30, 83),
                PokemonSeedEntry.pokemon(160, "Feraligatr", PokemonType.WATER, null, 2, PokedexColor.BLUE, 2.3, 88.8, EvolutionStage.SECOND_STAGE, null, 83),
                PokemonSeedEntry.pokemon(161, "Sentret", PokemonType.NORMAL, null, 2, PokedexColor.BROWN, 0.8, 6.0, EvolutionStage.BASE, 15, 84),
                PokemonSeedEntry.pokemon(162, "Furret", PokemonType.NORMAL, null, 2, PokedexColor.BROWN, 1.8, 32.5, EvolutionStage.SECOND_STAGE, null, 84),
                PokemonSeedEntry.pokemon(163, "Hoothoot", PokemonType.NORMAL, PokemonType.FLYING, 2, PokedexColor.BROWN, 0.7, 21.2, EvolutionStage.BASE, 20, 85),
                PokemonSeedEntry.pokemon(164, "Noctowl", PokemonType.NORMAL, PokemonType.FLYING, 2, PokedexColor.BROWN, 1.6, 40.8, EvolutionStage.SECOND_STAGE, null, 85),
                PokemonSeedEntry.pokemon(165, "Ledyba", PokemonType.BUG, PokemonType.FLYING, 2, PokedexColor.RED, 1.0, 10.8, EvolutionStage.BASE, 18, 86),
                PokemonSeedEntry.pokemon(166, "Ledian", PokemonType.BUG, PokemonType.FLYING, 2, PokedexColor.RED, 1.4, 35.6, EvolutionStage.SECOND_STAGE, null, 86),
                PokemonSeedEntry.pokemon(167, "Spinarak", PokemonType.BUG, PokemonType.POISON, 2, PokedexColor.GREEN, 0.5, 8.5, EvolutionStage.BASE, 22, 87),
                PokemonSeedEntry.pokemon(168, "Ariados", PokemonType.BUG, PokemonType.POISON, 2, PokedexColor.RED, 1.1, 33.5, EvolutionStage.SECOND_STAGE, null, 87),
                PokemonSeedEntry.pokemon(169, "Crobat", PokemonType.POISON, PokemonType.FLYING, 2, PokedexColor.PURPLE, 1.8, 75.0, EvolutionStage.SECOND_STAGE, null, 14),
                PokemonSeedEntry.pokemon(170, "Chinchou", PokemonType.WATER, PokemonType.ELECTRIC, 2, PokedexColor.BLUE, 0.5, 12.0, EvolutionStage.BASE, 27, 88),
                PokemonSeedEntry.pokemon(171, "Lanturn", PokemonType.WATER, PokemonType.ELECTRIC, 2, PokedexColor.BLUE, 1.2, 22.5, EvolutionStage.SECOND_STAGE, null, 88),
                PokemonSeedEntry.pokemon(172, "Pichu", PokemonType.ELECTRIC, null, 2, PokedexColor.YELLOW, 0.3, 2.0, EvolutionStage.BASE, null, 89),
                PokemonSeedEntry.pokemon(173, "Cleffa", PokemonType.FAIRY, null, 2, PokedexColor.PINK, 0.3, 3.0, EvolutionStage.BASE, null, 90),
                PokemonSeedEntry.pokemon(174, "Igglybuff", PokemonType.NORMAL, PokemonType.FAIRY, 2, PokedexColor.PINK, 0.3, 1.0, EvolutionStage.BASE, null, 91),
                PokemonSeedEntry.pokemon(175, "Togepi", PokemonType.FAIRY, null, 2, PokedexColor.WHITE, 0.3, 1.5, EvolutionStage.BASE, null, 92),
                PokemonSeedEntry.pokemon(176, "Togetic", PokemonType.FAIRY, PokemonType.FLYING, 2, PokedexColor.WHITE, 0.6, 3.2, EvolutionStage.FIRST_STAGE, null, 92),
                PokemonSeedEntry.pokemon(177, "Natu", PokemonType.PSYCHIC, PokemonType.FLYING, 2, PokedexColor.GREEN, 0.2, 2.0, EvolutionStage.BASE, 25, 93),
                PokemonSeedEntry.pokemon(178, "Xatu", PokemonType.PSYCHIC, PokemonType.FLYING, 2, PokedexColor.GREEN, 1.5, 15.0, EvolutionStage.SECOND_STAGE, null, 93),
                PokemonSeedEntry.pokemon(179, "Mareep", PokemonType.ELECTRIC, null, 2, PokedexColor.WHITE, 0.6, 7.8, EvolutionStage.BASE, 15, 94),
                PokemonSeedEntry.pokemon(180, "Flaaffy", PokemonType.ELECTRIC, null, 2, PokedexColor.PINK, 0.8, 13.3, EvolutionStage.FIRST_STAGE, 30, 94),
                PokemonSeedEntry.pokemon(181, "Ampharos", PokemonType.ELECTRIC, null, 2, PokedexColor.YELLOW, 1.4, 61.5, EvolutionStage.SECOND_STAGE, null, 94),
                PokemonSeedEntry.pokemon(182, "Bellossom", PokemonType.GRASS, null, 2, PokedexColor.GREEN, 0.4, 5.8, EvolutionStage.SECOND_STAGE, null, 16),
                PokemonSeedEntry.pokemon(183, "Marill", PokemonType.WATER, PokemonType.FAIRY, 2, PokedexColor.BLUE, 0.4, 8.5, EvolutionStage.FIRST_STAGE, 18, 159),
                PokemonSeedEntry.pokemon(184, "Azumarill", PokemonType.WATER, PokemonType.FAIRY, 2, PokedexColor.BLUE, 0.8, 28.5, EvolutionStage.SECOND_STAGE, null, 159),
                PokemonSeedEntry.pokemon(185, "Sudowoodo", PokemonType.ROCK, null, 2, PokedexColor.BROWN, 1.2, 38.0, EvolutionStage.SECOND_STAGE, null, 240),
                PokemonSeedEntry.pokemon(186, "Politoed", PokemonType.WATER, null, 2, PokedexColor.GREEN, 1.1, 33.9, EvolutionStage.SECOND_STAGE, null, 26),
                PokemonSeedEntry.pokemon(187, "Hoppip", PokemonType.GRASS, PokemonType.FLYING, 2, PokedexColor.PINK, 0.4, 0.5, EvolutionStage.BASE, 18, 95),
                PokemonSeedEntry.pokemon(188, "Skiploom", PokemonType.GRASS, PokemonType.FLYING, 2, PokedexColor.GREEN, 0.6, 1.0, EvolutionStage.FIRST_STAGE, 27, 95),
                PokemonSeedEntry.pokemon(189, "Jumpluff", PokemonType.GRASS, PokemonType.FLYING, 2, PokedexColor.BLUE, 0.8, 3.0, EvolutionStage.SECOND_STAGE, null, 95),
                PokemonSeedEntry.pokemon(190, "Aipom", PokemonType.NORMAL, null, 2, PokedexColor.PURPLE, 0.8, 11.5, EvolutionStage.BASE, null, 96),
                PokemonSeedEntry.pokemon(191, "Sunkern", PokemonType.GRASS, null, 2, PokedexColor.YELLOW, 0.3, 1.8, EvolutionStage.BASE, null, 97),
                PokemonSeedEntry.pokemon(192, "Sunflora", PokemonType.GRASS, null, 2, PokedexColor.YELLOW, 0.8, 8.5, EvolutionStage.SECOND_STAGE, null, 97),
                PokemonSeedEntry.pokemon(193, "Yanma", PokemonType.BUG, PokemonType.FLYING, 2, PokedexColor.RED, 1.2, 38.0, EvolutionStage.BASE, null, 98),
                PokemonSeedEntry.pokemon(194, "Wooper", PokemonType.WATER, PokemonType.GROUND, 2, PokedexColor.BLUE, 0.4, 8.5, EvolutionStage.BASE, 20, 99),
                PokemonSeedEntry.pokemon(195, "Quagsire", PokemonType.WATER, PokemonType.GROUND, 2, PokedexColor.BLUE, 1.4, 75.0, EvolutionStage.SECOND_STAGE, null, 99),
                PokemonSeedEntry.pokemon(196, "Espeon", PokemonType.PSYCHIC, null, 2, PokedexColor.PURPLE, 0.9, 26.5, EvolutionStage.SECOND_STAGE, null, 66),
                PokemonSeedEntry.pokemon(197, "Umbreon", PokemonType.DARK, null, 2, PokedexColor.BLACK, 1.0, 27.0, EvolutionStage.SECOND_STAGE, null, 67),
                PokemonSeedEntry.pokemon(198, "Murkrow", PokemonType.DARK, PokemonType.FLYING, 2, PokedexColor.BLACK, 0.5, 2.1, EvolutionStage.BASE, null, 101),
                PokemonSeedEntry.pokemon(199, "Slowking", PokemonType.WATER, PokemonType.PSYCHIC, 2, PokedexColor.PINK, 2.0, 79.5, EvolutionStage.SECOND_STAGE, null, 34),
                PokemonSeedEntry.pokemon(200, "Misdreavus", PokemonType.GHOST, null, 2, PokedexColor.GRAY, 0.7, 1.0, EvolutionStage.BASE, null, 102),
                PokemonSeedEntry.pokemon(201, "Unown", PokemonType.PSYCHIC, null, 2, PokedexColor.BLACK, 0.5, 5.0, null, null, 103),
                PokemonSeedEntry.pokemon(202, "Wobbuffet", PokemonType.PSYCHIC, null, 2, PokedexColor.BLUE, 1.3, 28.5, EvolutionStage.SECOND_STAGE, null, 197),
                PokemonSeedEntry.pokemon(203, "Girafarig", PokemonType.NORMAL, PokemonType.PSYCHIC, 2, PokedexColor.YELLOW, 1.5, 41.5, EvolutionStage.BASE, null, 104),
                PokemonSeedEntry.pokemon(204, "Pineco", PokemonType.BUG, null, 2, PokedexColor.GRAY, 0.6, 7.2, EvolutionStage.BASE, 31, 105),
                PokemonSeedEntry.pokemon(205, "Forretress", PokemonType.BUG, PokemonType.STEEL, 2, PokedexColor.PURPLE, 1.2, 125.8, EvolutionStage.SECOND_STAGE, null, 105),
                PokemonSeedEntry.pokemon(206, "Dunsparce", PokemonType.NORMAL, null, 2, PokedexColor.YELLOW, 1.5, 14.0, EvolutionStage.BASE, null, 106),
                PokemonSeedEntry.pokemon(207, "Gligar", PokemonType.GROUND, PokemonType.FLYING, 2, PokedexColor.PURPLE, 1.1, 64.8, EvolutionStage.BASE, null, 107),
                PokemonSeedEntry.pokemon(208, "Steelix", PokemonType.STEEL, PokemonType.GROUND, 2, PokedexColor.GRAY, 9.2, 400.0, EvolutionStage.SECOND_STAGE, null, 42),
                PokemonSeedEntry.pokemon(209, "Snubbull", PokemonType.FAIRY, null, 2, PokedexColor.PINK, 0.6, 7.8, EvolutionStage.BASE, 23, 108),
                PokemonSeedEntry.pokemon(210, "Granbull", PokemonType.FAIRY, null, 2, PokedexColor.PURPLE, 1.4, 48.7, EvolutionStage.SECOND_STAGE, null, 108),
                PokemonSeedEntry.pokemon(211, "Qwilfish", PokemonType.WATER, PokemonType.POISON, 2, PokedexColor.GRAY, 0.5, 3.9, EvolutionStage.BASE, null, 109),
                PokemonSeedEntry.pokemon(212, "Scizor", PokemonType.BUG, PokemonType.STEEL, 2, PokedexColor.RED, 1.8, 118.0, EvolutionStage.SECOND_STAGE, null, 56),
                PokemonSeedEntry.pokemon(213, "Shuckle", PokemonType.BUG, PokemonType.ROCK, 2, PokedexColor.YELLOW, 0.6, 20.5, null, null, 110),
                PokemonSeedEntry.pokemon(214, "Heracross", PokemonType.BUG, PokemonType.FIGHTING, 2, PokedexColor.BLUE, 1.5, 54.0, null, null, 111),
                PokemonSeedEntry.pokemon(215, "Sneasel", PokemonType.DARK, PokemonType.ICE, 2, PokedexColor.BLACK, 0.9, 28.0, EvolutionStage.BASE, null, 112),
                PokemonSeedEntry.pokemon(216, "Teddiursa", PokemonType.NORMAL, null, 2, PokedexColor.BROWN, 0.6, 8.8, EvolutionStage.BASE, 30, 114),
                PokemonSeedEntry.pokemon(217, "Ursaring", PokemonType.NORMAL, null, 2, PokedexColor.BROWN, 1.8, 125.8, EvolutionStage.FIRST_STAGE, null, 114),
                PokemonSeedEntry.pokemon(218, "Slugma", PokemonType.FIRE, null, 2, PokedexColor.RED, 0.7, 35.0, EvolutionStage.BASE, 38, 115),
                PokemonSeedEntry.pokemon(219, "Magcargo", PokemonType.FIRE, PokemonType.ROCK, 2, PokedexColor.RED, 0.8, 55.0, EvolutionStage.SECOND_STAGE, null, 115),
                PokemonSeedEntry.pokemon(220, "Swinub", PokemonType.ICE, PokemonType.GROUND, 2, PokedexColor.BROWN, 0.4, 6.5, EvolutionStage.BASE, 33, 116),
                PokemonSeedEntry.pokemon(221, "Piloswine", PokemonType.ICE, PokemonType.GROUND, 2, PokedexColor.BROWN, 1.1, 55.8, EvolutionStage.FIRST_STAGE, null, 116),
                PokemonSeedEntry.pokemon(222, "Corsola", PokemonType.WATER, PokemonType.ROCK, 2, PokedexColor.PINK, 0.6, 5.0, EvolutionStage.BASE, 38, 117),
                PokemonSeedEntry.pokemon(223, "Remoraid", PokemonType.WATER, null, 2, PokedexColor.GRAY, 0.6, 12.0, EvolutionStage.BASE, 25, 118),
                PokemonSeedEntry.pokemon(224, "Octillery", PokemonType.WATER, null, 2, PokedexColor.RED, 0.9, 28.5, EvolutionStage.SECOND_STAGE, null, 118),
                PokemonSeedEntry.pokemon(225, "Delibird", PokemonType.ICE, PokemonType.FLYING, 2, PokedexColor.RED, 0.9, 16.0, null, null, 119),
                PokemonSeedEntry.pokemon(226, "Mantine", PokemonType.WATER, PokemonType.FLYING, 2, PokedexColor.PURPLE, 2.1, 220.0, EvolutionStage.SECOND_STAGE, null, 253),
                PokemonSeedEntry.pokemon(227, "Skarmory", PokemonType.STEEL, PokemonType.FLYING, 2, PokedexColor.GRAY, 1.7, 50.5, null, null, 120),
                PokemonSeedEntry.pokemon(228, "Houndour", PokemonType.DARK, PokemonType.FIRE, 2, PokedexColor.BLACK, 0.6, 10.8, EvolutionStage.BASE, 24, 121),
                PokemonSeedEntry.pokemon(229, "Houndoom", PokemonType.DARK, PokemonType.FIRE, 2, PokedexColor.BLACK, 1.4, 35.0, EvolutionStage.SECOND_STAGE, null, 121),
                PokemonSeedEntry.pokemon(230, "Kingdra", PokemonType.WATER, PokemonType.DRAGON, 2, PokedexColor.BLUE, 1.8, 152.0, EvolutionStage.SECOND_STAGE, null, 53),
                PokemonSeedEntry.pokemon(231, "Phanpy", PokemonType.GROUND, null, 2, PokedexColor.BLUE, 0.5, 33.5, EvolutionStage.BASE, 25, 122),
                PokemonSeedEntry.pokemon(232, "Donphan", PokemonType.GROUND, null, 2, PokedexColor.GRAY, 1.1, 120.0, EvolutionStage.SECOND_STAGE, null, 122),
                PokemonSeedEntry.pokemon(233, "Porygon2", PokemonType.NORMAL, null, 2, PokedexColor.RED, 0.6, 32.5, EvolutionStage.FIRST_STAGE, null, 71),
                PokemonSeedEntry.pokemon(234, "Stantler", PokemonType.NORMAL, null, 2, PokedexColor.BROWN, 1.4, 71.2, EvolutionStage.BASE, null, 123),
                PokemonSeedEntry.pokemon(235, "Smeargle", PokemonType.NORMAL, null, 2, PokedexColor.WHITE, 1.2, 58.0, null, null, 124),
                PokemonSeedEntry.pokemon(236, "Tyrogue", PokemonType.FIGHTING, null, 2, PokedexColor.PURPLE, 0.7, 21.0, EvolutionStage.BASE, 20, 125),
                PokemonSeedEntry.pokemon(237, "Hitmontop", PokemonType.FIGHTING, null, 2, PokedexColor.BROWN, 1.4, 48.0, EvolutionStage.SECOND_STAGE, null, 127),
                PokemonSeedEntry.pokemon(238, "Smoochum", PokemonType.ICE, PokemonType.PSYCHIC, 2, PokedexColor.PINK, 0.4, 6.0, EvolutionStage.BASE, 30, 128),
                PokemonSeedEntry.pokemon(239, "Elekid", PokemonType.ELECTRIC, null, 2, PokedexColor.YELLOW, 0.6, 23.5, EvolutionStage.BASE, 30, 129),
                PokemonSeedEntry.pokemon(240, "Magby", PokemonType.FIRE, null, 2, PokedexColor.RED, 0.7, 21.4, EvolutionStage.BASE, 30, 130),
                PokemonSeedEntry.pokemon(241, "Miltank", PokemonType.NORMAL, null, 2, PokedexColor.PINK, 1.2, 75.5, null, null, 131),
                PokemonSeedEntry.pokemon(242, "Blissey", PokemonType.NORMAL, null, 2, PokedexColor.PINK, 1.5, 46.8, EvolutionStage.SECOND_STAGE, null, 242),
                PokemonSeedEntry.pokemon(243, "Raikou", PokemonType.ELECTRIC, null, 2, PokedexColor.YELLOW, 1.9, 178.0, null, null, 132),
                PokemonSeedEntry.pokemon(244, "Entei", PokemonType.FIRE, null, 2, PokedexColor.BROWN, 2.1, 198.0, null, null, 133),
                PokemonSeedEntry.pokemon(245, "Suicune", PokemonType.WATER, null, 2, PokedexColor.BLUE, 2.0, 187.0, null, null, 134),
                PokemonSeedEntry.pokemon(246, "Larvitar", PokemonType.ROCK, PokemonType.GROUND, 2, PokedexColor.GREEN, 0.6, 72.0, EvolutionStage.BASE, 30, 135),
                PokemonSeedEntry.pokemon(247, "Pupitar", PokemonType.ROCK, PokemonType.GROUND, 2, PokedexColor.GRAY, 1.2, 152.0, EvolutionStage.FIRST_STAGE, 55, 135),
                PokemonSeedEntry.pokemon(248, "Tyranitar", PokemonType.ROCK, PokemonType.DARK, 2, PokedexColor.GREEN, 2.0, 202.0, EvolutionStage.SECOND_STAGE, null, 135),
                PokemonSeedEntry.pokemon(249, "Lugia", PokemonType.PSYCHIC, PokemonType.FLYING, 2, PokedexColor.WHITE, 5.2, 216.0, null, null, 136),
                PokemonSeedEntry.pokemon(250, "Ho-Oh", PokemonType.FIRE, PokemonType.FLYING, 2, PokedexColor.RED, 3.8, 199.0, null, null, 137),
                PokemonSeedEntry.pokemon(251, "Celebi", PokemonType.PSYCHIC, PokemonType.GRASS, 2, PokedexColor.GREEN, 0.6, 5.0, null, null, 138)
        );
    }
}
