package com.svc.pokeguessteam.config.seed;

import com.svc.pokeguessteam.model.enums.EvolutionStage;
import com.svc.pokeguessteam.model.enums.PokedexColor;
import com.svc.pokeguessteam.model.enums.PokemonType;

import java.util.List;

public final class Generation5Seed {

    private Generation5Seed() {
    }

    public static List<PokemonSeedEntry> entries() {
        return List.of(
                PokemonSeedEntry.pokemon(494, "Victini", PokemonType.PSYCHIC, PokemonType.FIRE, 5, PokedexColor.YELLOW, 0.4, 4.0, null, null, 269),
                PokemonSeedEntry.pokemon(495, "Snivy", PokemonType.GRASS, null, 5, PokedexColor.GREEN, 0.6, 8.1, EvolutionStage.BASE, 17, 270),
                PokemonSeedEntry.pokemon(496, "Servine", PokemonType.GRASS, null, 5, PokedexColor.GREEN, 0.8, 16.0, EvolutionStage.FIRST_STAGE, 36, 270),
                PokemonSeedEntry.pokemon(497, "Serperior", PokemonType.GRASS, null, 5, PokedexColor.GREEN, 3.3, 63.0, EvolutionStage.SECOND_STAGE, null, 270),
                PokemonSeedEntry.pokemon(498, "Tepig", PokemonType.FIRE, null, 5, PokedexColor.RED, 0.5, 9.9, EvolutionStage.BASE, 17, 271),
                PokemonSeedEntry.pokemon(499, "Pignite", PokemonType.FIRE, PokemonType.FIGHTING, 5, PokedexColor.RED, 1.0, 55.5, EvolutionStage.FIRST_STAGE, 36, 271),
                PokemonSeedEntry.pokemon(500, "Emboar", PokemonType.FIRE, PokemonType.FIGHTING, 5, PokedexColor.RED, 1.6, 150.0, EvolutionStage.SECOND_STAGE, null, 271),
                PokemonSeedEntry.pokemon(501, "Oshawott", PokemonType.WATER, null, 5, PokedexColor.BLUE, 0.5, 5.9, EvolutionStage.BASE, 17, 272),
                PokemonSeedEntry.pokemon(502, "Dewott", PokemonType.WATER, null, 5, PokedexColor.BLUE, 0.8, 24.5, EvolutionStage.FIRST_STAGE, 36, 272),
                PokemonSeedEntry.pokemon(503, "Samurott", PokemonType.WATER, null, 5, PokedexColor.BLUE, 1.5, 94.6, EvolutionStage.SECOND_STAGE, null, 272),
                PokemonSeedEntry.pokemon(504, "Patrat", PokemonType.NORMAL, null, 5, PokedexColor.BROWN, 0.5, 11.6, EvolutionStage.BASE, 20, 273),
                PokemonSeedEntry.pokemon(505, "Watchog", PokemonType.NORMAL, null, 5, PokedexColor.BROWN, 1.1, 27.0, EvolutionStage.SECOND_STAGE, null, 273),
                PokemonSeedEntry.pokemon(506, "Lillipup", PokemonType.NORMAL, null, 5, PokedexColor.BROWN, 0.4, 4.1, EvolutionStage.BASE, 16, 274),
                PokemonSeedEntry.pokemon(507, "Herdier", PokemonType.NORMAL, null, 5, PokedexColor.GRAY, 0.9, 14.7, EvolutionStage.FIRST_STAGE, 32, 274),
                PokemonSeedEntry.pokemon(508, "Stoutland", PokemonType.NORMAL, null, 5, PokedexColor.GRAY, 1.2, 61.0, EvolutionStage.SECOND_STAGE, null, 274),
                PokemonSeedEntry.pokemon(509, "Purrloin", PokemonType.DARK, null, 5, PokedexColor.PURPLE, 0.4, 10.1, EvolutionStage.BASE, 20, 275),
                PokemonSeedEntry.pokemon(510, "Liepard", PokemonType.DARK, null, 5, PokedexColor.PURPLE, 1.1, 37.5, EvolutionStage.SECOND_STAGE, null, 275),
                PokemonSeedEntry.pokemon(511, "Pansage", PokemonType.GRASS, null, 5, PokedexColor.GREEN, 0.6, 10.5, EvolutionStage.BASE, null, 276),
                PokemonSeedEntry.pokemon(512, "Simisage", PokemonType.GRASS, null, 5, PokedexColor.GREEN, 1.1, 30.5, EvolutionStage.SECOND_STAGE, null, 276),
                PokemonSeedEntry.pokemon(513, "Pansear", PokemonType.FIRE, null, 5, PokedexColor.RED, 0.6, 11.0, EvolutionStage.BASE, null, 277),
                PokemonSeedEntry.pokemon(514, "Simisear", PokemonType.FIRE, null, 5, PokedexColor.RED, 1.0, 28.0, EvolutionStage.SECOND_STAGE, null, 277),
                PokemonSeedEntry.pokemon(515, "Panpour", PokemonType.WATER, null, 5, PokedexColor.BLUE, 0.6, 13.5, EvolutionStage.BASE, null, 278),
                PokemonSeedEntry.pokemon(516, "Simipour", PokemonType.WATER, null, 5, PokedexColor.BLUE, 1.0, 29.0, EvolutionStage.SECOND_STAGE, null, 278),
                PokemonSeedEntry.pokemon(517, "Munna", PokemonType.PSYCHIC, null, 5, PokedexColor.PINK, 0.6, 23.3, EvolutionStage.BASE, null, 279),
                PokemonSeedEntry.pokemon(518, "Musharna", PokemonType.PSYCHIC, null, 5, PokedexColor.PINK, 1.1, 60.5, EvolutionStage.SECOND_STAGE, null, 279),
                PokemonSeedEntry.pokemon(519, "Pidove", PokemonType.NORMAL, PokemonType.FLYING, 5, PokedexColor.GRAY, 0.3, 2.1, EvolutionStage.BASE, 21, 280),
                PokemonSeedEntry.pokemon(520, "Tranquill", PokemonType.NORMAL, PokemonType.FLYING, 5, PokedexColor.GRAY, 0.6, 15.0, EvolutionStage.FIRST_STAGE, 32, 280),
                PokemonSeedEntry.pokemon(521, "Unfezant", PokemonType.NORMAL, PokemonType.FLYING, 5, PokedexColor.GRAY, 1.2, 29.0, EvolutionStage.SECOND_STAGE, null, 280),
                PokemonSeedEntry.pokemon(522, "Blitzle", PokemonType.ELECTRIC, null, 5, PokedexColor.BLACK, 0.8, 29.8, EvolutionStage.BASE, 27, 281),
                PokemonSeedEntry.pokemon(523, "Zebstrika", PokemonType.ELECTRIC, null, 5, PokedexColor.BLACK, 1.6, 79.5, EvolutionStage.SECOND_STAGE, null, 281),
                PokemonSeedEntry.pokemon(524, "Roggenrola", PokemonType.ROCK, null, 5, PokedexColor.BLUE, 0.4, 18.0, EvolutionStage.BASE, 25, 282),
                PokemonSeedEntry.pokemon(525, "Boldore", PokemonType.ROCK, null, 5, PokedexColor.BLUE, 0.9, 102.0, EvolutionStage.FIRST_STAGE, null, 282),
                PokemonSeedEntry.pokemon(526, "Gigalith", PokemonType.ROCK, null, 5, PokedexColor.BLUE, 1.7, 260.0, EvolutionStage.SECOND_STAGE, null, 282),
                PokemonSeedEntry.pokemon(527, "Woobat", PokemonType.PSYCHIC, PokemonType.FLYING, 5, PokedexColor.BLUE, 0.4, 2.1, EvolutionStage.BASE, null, 283),
                PokemonSeedEntry.pokemon(528, "Swoobat", PokemonType.PSYCHIC, PokemonType.FLYING, 5, PokedexColor.BLUE, 0.9, 10.5, EvolutionStage.SECOND_STAGE, null, 283),
                PokemonSeedEntry.pokemon(529, "Drilbur", PokemonType.GROUND, null, 5, PokedexColor.GRAY, 0.3, 8.5, EvolutionStage.BASE, 31, 284),
                PokemonSeedEntry.pokemon(530, "Excadrill", PokemonType.GROUND, PokemonType.STEEL, 5, PokedexColor.GRAY, 0.7, 40.4, EvolutionStage.SECOND_STAGE, null, 284),
                PokemonSeedEntry.pokemon(531, "Audino", PokemonType.NORMAL, null, 5, PokedexColor.PINK, 1.1, 31.0, null, null, 285),
                PokemonSeedEntry.pokemon(532, "Timburr", PokemonType.FIGHTING, null, 5, PokedexColor.GRAY, 0.6, 12.5, EvolutionStage.BASE, 25, 286),
                PokemonSeedEntry.pokemon(533, "Gurdurr", PokemonType.FIGHTING, null, 5, PokedexColor.GRAY, 1.2, 40.0, EvolutionStage.FIRST_STAGE, null, 286),
                PokemonSeedEntry.pokemon(534, "Conkeldurr", PokemonType.FIGHTING, null, 5, PokedexColor.BROWN, 1.4, 87.0, EvolutionStage.SECOND_STAGE, null, 286),
                PokemonSeedEntry.pokemon(535, "Tympole", PokemonType.WATER, null, 5, PokedexColor.BLUE, 0.5, 4.5, EvolutionStage.BASE, 25, 287),
                PokemonSeedEntry.pokemon(536, "Palpitoad", PokemonType.WATER, PokemonType.GROUND, 5, PokedexColor.BLUE, 0.8, 17.0, EvolutionStage.FIRST_STAGE, 36, 287),
                PokemonSeedEntry.pokemon(537, "Seismitoad", PokemonType.WATER, PokemonType.GROUND, 5, PokedexColor.BLUE, 1.5, 62.0, EvolutionStage.SECOND_STAGE, null, 287),
                PokemonSeedEntry.pokemon(538, "Throh", PokemonType.FIGHTING, null, 5, PokedexColor.RED, 1.3, 55.5, null, null, 288),
                PokemonSeedEntry.pokemon(539, "Sawk", PokemonType.FIGHTING, null, 5, PokedexColor.BLUE, 1.4, 51.0, null, null, 289),
                PokemonSeedEntry.pokemon(540, "Sewaddle", PokemonType.BUG, PokemonType.GRASS, 5, PokedexColor.YELLOW, 0.3, 2.5, EvolutionStage.BASE, 20, 290),
                PokemonSeedEntry.pokemon(541, "Swadloon", PokemonType.BUG, PokemonType.GRASS, 5, PokedexColor.GREEN, 0.5, 7.3, EvolutionStage.FIRST_STAGE, null, 290),
                PokemonSeedEntry.pokemon(542, "Leavanny", PokemonType.BUG, PokemonType.GRASS, 5, PokedexColor.YELLOW, 1.2, 20.5, EvolutionStage.SECOND_STAGE, null, 290),
                PokemonSeedEntry.pokemon(543, "Venipede", PokemonType.BUG, PokemonType.POISON, 5, PokedexColor.RED, 0.4, 5.3, EvolutionStage.BASE, 22, 291),
                PokemonSeedEntry.pokemon(544, "Whirlipede", PokemonType.BUG, PokemonType.POISON, 5, PokedexColor.GRAY, 1.2, 58.5, EvolutionStage.FIRST_STAGE, 30, 291),
                PokemonSeedEntry.pokemon(545, "Scolipede", PokemonType.BUG, PokemonType.POISON, 5, PokedexColor.RED, 2.5, 200.5, EvolutionStage.SECOND_STAGE, null, 291),
                PokemonSeedEntry.pokemon(546, "Cottonee", PokemonType.GRASS, PokemonType.FAIRY, 5, PokedexColor.GREEN, 0.3, 0.6, EvolutionStage.BASE, null, 292),
                PokemonSeedEntry.pokemon(547, "Whimsicott", PokemonType.GRASS, PokemonType.FAIRY, 5, PokedexColor.GREEN, 0.7, 6.6, EvolutionStage.SECOND_STAGE, null, 292),
                PokemonSeedEntry.pokemon(548, "Petilil", PokemonType.GRASS, null, 5, PokedexColor.GREEN, 0.5, 6.6, EvolutionStage.BASE, null, 293),
                PokemonSeedEntry.pokemon(549, "Lilligant", PokemonType.GRASS, null, 5, PokedexColor.GREEN, 1.1, 16.3, EvolutionStage.SECOND_STAGE, null, 293),
                PokemonSeedEntry.pokemon(550, "Basculin", PokemonType.WATER, null, 5, PokedexColor.GREEN, 1.0, 18.0, EvolutionStage.BASE, null, 294),
                PokemonSeedEntry.pokemon(551, "Sandile", PokemonType.GROUND, PokemonType.DARK, 5, PokedexColor.BROWN, 0.7, 15.2, EvolutionStage.BASE, 29, 295),
                PokemonSeedEntry.pokemon(552, "Krokorok", PokemonType.GROUND, PokemonType.DARK, 5, PokedexColor.BROWN, 1.0, 33.4, EvolutionStage.FIRST_STAGE, 40, 295),
                PokemonSeedEntry.pokemon(553, "Krookodile", PokemonType.GROUND, PokemonType.DARK, 5, PokedexColor.RED, 1.5, 96.3, EvolutionStage.SECOND_STAGE, null, 295),
                PokemonSeedEntry.pokemon(554, "Darumaka", PokemonType.FIRE, null, 5, PokedexColor.RED, 0.6, 37.5, EvolutionStage.BASE, 35, 296),
                PokemonSeedEntry.pokemon(555, "Darmanitan", PokemonType.FIRE, null, 5, PokedexColor.RED, 1.3, 92.9, EvolutionStage.SECOND_STAGE, null, 296),
                PokemonSeedEntry.pokemon(556, "Maractus", PokemonType.GRASS, null, 5, PokedexColor.GREEN, 1.0, 28.0, null, null, 297),
                PokemonSeedEntry.pokemon(557, "Dwebble", PokemonType.BUG, PokemonType.ROCK, 5, PokedexColor.RED, 0.3, 14.5, EvolutionStage.BASE, 34, 298),
                PokemonSeedEntry.pokemon(558, "Crustle", PokemonType.BUG, PokemonType.ROCK, 5, PokedexColor.RED, 1.4, 200.0, EvolutionStage.SECOND_STAGE, null, 298),
                PokemonSeedEntry.pokemon(559, "Scraggy", PokemonType.DARK, PokemonType.FIGHTING, 5, PokedexColor.YELLOW, 0.6, 11.8, EvolutionStage.BASE, 39, 299),
                PokemonSeedEntry.pokemon(560, "Scrafty", PokemonType.DARK, PokemonType.FIGHTING, 5, PokedexColor.RED, 1.1, 30.0, EvolutionStage.SECOND_STAGE, null, 299),
                PokemonSeedEntry.pokemon(561, "Sigilyph", PokemonType.PSYCHIC, PokemonType.FLYING, 5, PokedexColor.BLACK, 1.4, 14.0, null, null, 300),
                PokemonSeedEntry.pokemon(562, "Yamask", PokemonType.GHOST, null, 5, PokedexColor.BLACK, 0.5, 1.5, EvolutionStage.BASE, 34, 301),
                PokemonSeedEntry.pokemon(563, "Cofagrigus", PokemonType.GHOST, null, 5, PokedexColor.YELLOW, 1.7, 76.5, EvolutionStage.SECOND_STAGE, null, 301),
                PokemonSeedEntry.pokemon(564, "Tirtouga", PokemonType.WATER, PokemonType.ROCK, 5, PokedexColor.BLUE, 0.7, 16.5, EvolutionStage.BASE, 37, 303),
                PokemonSeedEntry.pokemon(565, "Carracosta", PokemonType.WATER, PokemonType.ROCK, 5, PokedexColor.BLUE, 1.2, 81.0, EvolutionStage.SECOND_STAGE, null, 303),
                PokemonSeedEntry.pokemon(566, "Archen", PokemonType.ROCK, PokemonType.FLYING, 5, PokedexColor.YELLOW, 0.5, 9.5, EvolutionStage.BASE, 37, 304),
                PokemonSeedEntry.pokemon(567, "Archeops", PokemonType.ROCK, PokemonType.FLYING, 5, PokedexColor.YELLOW, 1.4, 32.0, EvolutionStage.SECOND_STAGE, null, 304),
                PokemonSeedEntry.pokemon(568, "Trubbish", PokemonType.POISON, null, 5, PokedexColor.GREEN, 0.6, 31.0, EvolutionStage.BASE, 36, 305),
                PokemonSeedEntry.pokemon(569, "Garbodor", PokemonType.POISON, null, 5, PokedexColor.GREEN, 1.9, 107.3, EvolutionStage.SECOND_STAGE, null, 305),
                PokemonSeedEntry.pokemon(570, "Zorua", PokemonType.DARK, null, 5, PokedexColor.GRAY, 0.7, 12.5, EvolutionStage.BASE, 30, 306),
                PokemonSeedEntry.pokemon(571, "Zoroark", PokemonType.DARK, null, 5, PokedexColor.GRAY, 1.6, 81.1, EvolutionStage.SECOND_STAGE, null, 306),
                PokemonSeedEntry.pokemon(572, "Minccino", PokemonType.NORMAL, null, 5, PokedexColor.GRAY, 0.4, 5.8, EvolutionStage.BASE, null, 307),
                PokemonSeedEntry.pokemon(573, "Cinccino", PokemonType.NORMAL, null, 5, PokedexColor.GRAY, 0.5, 7.5, EvolutionStage.SECOND_STAGE, null, 307),
                PokemonSeedEntry.pokemon(574, "Gothita", PokemonType.PSYCHIC, null, 5, PokedexColor.PURPLE, 0.4, 5.8, EvolutionStage.BASE, 32, 308),
                PokemonSeedEntry.pokemon(575, "Gothorita", PokemonType.PSYCHIC, null, 5, PokedexColor.PURPLE, 0.7, 18.0, EvolutionStage.FIRST_STAGE, 41, 308),
                PokemonSeedEntry.pokemon(576, "Gothitelle", PokemonType.PSYCHIC, null, 5, PokedexColor.PURPLE, 1.5, 44.0, EvolutionStage.SECOND_STAGE, null, 308),
                PokemonSeedEntry.pokemon(577, "Solosis", PokemonType.PSYCHIC, null, 5, PokedexColor.GREEN, 0.3, 1.0, EvolutionStage.BASE, 32, 309),
                PokemonSeedEntry.pokemon(578, "Duosion", PokemonType.PSYCHIC, null, 5, PokedexColor.GREEN, 0.6, 8.0, EvolutionStage.FIRST_STAGE, 41, 309),
                PokemonSeedEntry.pokemon(579, "Reuniclus", PokemonType.PSYCHIC, null, 5, PokedexColor.GREEN, 1.0, 20.1, EvolutionStage.SECOND_STAGE, null, 309),
                PokemonSeedEntry.pokemon(580, "Ducklett", PokemonType.WATER, PokemonType.FLYING, 5, PokedexColor.BLUE, 0.5, 5.5, EvolutionStage.BASE, 35, 310),
                PokemonSeedEntry.pokemon(581, "Swanna", PokemonType.WATER, PokemonType.FLYING, 5, PokedexColor.WHITE, 1.3, 24.2, EvolutionStage.SECOND_STAGE, null, 310),
                PokemonSeedEntry.pokemon(582, "Vanillite", PokemonType.ICE, null, 5, PokedexColor.WHITE, 0.4, 5.7, EvolutionStage.BASE, 35, 311),
                PokemonSeedEntry.pokemon(583, "Vanillish", PokemonType.ICE, null, 5, PokedexColor.WHITE, 1.1, 41.0, EvolutionStage.FIRST_STAGE, 47, 311),
                PokemonSeedEntry.pokemon(584, "Vanilluxe", PokemonType.ICE, null, 5, PokedexColor.WHITE, 1.3, 57.5, EvolutionStage.SECOND_STAGE, null, 311),
                PokemonSeedEntry.pokemon(585, "Deerling", PokemonType.NORMAL, PokemonType.GRASS, 5, PokedexColor.PINK, 0.6, 19.5, EvolutionStage.BASE, 34, 312),
                PokemonSeedEntry.pokemon(586, "Sawsbuck", PokemonType.NORMAL, PokemonType.GRASS, 5, PokedexColor.BROWN, 1.9, 92.5, EvolutionStage.SECOND_STAGE, null, 312),
                PokemonSeedEntry.pokemon(587, "Emolga", PokemonType.ELECTRIC, PokemonType.FLYING, 5, PokedexColor.WHITE, 0.4, 5.0, null, null, 313),
                PokemonSeedEntry.pokemon(588, "Karrablast", PokemonType.BUG, null, 5, PokedexColor.BLUE, 0.5, 5.9, EvolutionStage.BASE, null, 314),
                PokemonSeedEntry.pokemon(589, "Escavalier", PokemonType.BUG, PokemonType.STEEL, 5, PokedexColor.GRAY, 1.0, 33.0, EvolutionStage.SECOND_STAGE, null, 314),
                PokemonSeedEntry.pokemon(590, "Foongus", PokemonType.GRASS, PokemonType.POISON, 5, PokedexColor.WHITE, 0.2, 1.0, EvolutionStage.BASE, 39, 315),
                PokemonSeedEntry.pokemon(591, "Amoonguss", PokemonType.GRASS, PokemonType.POISON, 5, PokedexColor.WHITE, 0.6, 10.5, EvolutionStage.SECOND_STAGE, null, 315),
                PokemonSeedEntry.pokemon(592, "Frillish", PokemonType.WATER, PokemonType.GHOST, 5, PokedexColor.WHITE, 1.2, 33.0, EvolutionStage.BASE, 40, 316),
                PokemonSeedEntry.pokemon(593, "Jellicent", PokemonType.WATER, PokemonType.GHOST, 5, PokedexColor.WHITE, 2.2, 135.0, EvolutionStage.SECOND_STAGE, null, 316),
                PokemonSeedEntry.pokemon(594, "Alomomola", PokemonType.WATER, null, 5, PokedexColor.PINK, 1.2, 31.6, null, null, 317),
                PokemonSeedEntry.pokemon(595, "Joltik", PokemonType.BUG, PokemonType.ELECTRIC, 5, PokedexColor.YELLOW, 0.1, 0.6, EvolutionStage.BASE, 36, 318),
                PokemonSeedEntry.pokemon(596, "Galvantula", PokemonType.BUG, PokemonType.ELECTRIC, 5, PokedexColor.YELLOW, 0.8, 14.3, EvolutionStage.SECOND_STAGE, null, 318),
                PokemonSeedEntry.pokemon(597, "Ferroseed", PokemonType.GRASS, PokemonType.STEEL, 5, PokedexColor.GRAY, 0.6, 18.8, EvolutionStage.BASE, 40, 319),
                PokemonSeedEntry.pokemon(598, "Ferrothorn", PokemonType.GRASS, PokemonType.STEEL, 5, PokedexColor.GRAY, 1.0, 110.0, EvolutionStage.SECOND_STAGE, null, 319),
                PokemonSeedEntry.pokemon(599, "Klink", PokemonType.STEEL, null, 5, PokedexColor.GRAY, 0.3, 21.0, EvolutionStage.BASE, 38, 320),
                PokemonSeedEntry.pokemon(600, "Klang", PokemonType.STEEL, null, 5, PokedexColor.GRAY, 0.6, 51.0, EvolutionStage.FIRST_STAGE, 49, 320),
                PokemonSeedEntry.pokemon(601, "Klinklang", PokemonType.STEEL, null, 5, PokedexColor.GRAY, 0.6, 81.0, EvolutionStage.SECOND_STAGE, null, 320),
                PokemonSeedEntry.pokemon(602, "Tynamo", PokemonType.ELECTRIC, null, 5, PokedexColor.WHITE, 0.2, 0.3, EvolutionStage.BASE, 39, 321),
                PokemonSeedEntry.pokemon(603, "Eelektrik", PokemonType.ELECTRIC, null, 5, PokedexColor.BLUE, 1.2, 22.0, EvolutionStage.FIRST_STAGE, null, 321),
                PokemonSeedEntry.pokemon(604, "Eelektross", PokemonType.ELECTRIC, null, 5, PokedexColor.BLUE, 2.1, 80.5, EvolutionStage.SECOND_STAGE, null, 321),
                PokemonSeedEntry.pokemon(605, "Elgyem", PokemonType.PSYCHIC, null, 5, PokedexColor.BLUE, 0.5, 9.0, EvolutionStage.BASE, 42, 322),
                PokemonSeedEntry.pokemon(606, "Beheeyem", PokemonType.PSYCHIC, null, 5, PokedexColor.BROWN, 1.0, 34.5, EvolutionStage.SECOND_STAGE, null, 322),
                PokemonSeedEntry.pokemon(607, "Litwick", PokemonType.GHOST, PokemonType.FIRE, 5, PokedexColor.WHITE, 0.3, 3.1, EvolutionStage.BASE, 41, 323),
                PokemonSeedEntry.pokemon(608, "Lampent", PokemonType.GHOST, PokemonType.FIRE, 5, PokedexColor.BLACK, 0.6, 13.0, EvolutionStage.FIRST_STAGE, null, 323),
                PokemonSeedEntry.pokemon(609, "Chandelure", PokemonType.GHOST, PokemonType.FIRE, 5, PokedexColor.BLACK, 1.0, 34.3, EvolutionStage.SECOND_STAGE, null, 323),
                PokemonSeedEntry.pokemon(610, "Axew", PokemonType.DRAGON, null, 5, PokedexColor.GREEN, 0.6, 18.0, EvolutionStage.BASE, 38, 324),
                PokemonSeedEntry.pokemon(611, "Fraxure", PokemonType.DRAGON, null, 5, PokedexColor.GREEN, 1.0, 36.0, EvolutionStage.FIRST_STAGE, 48, 324),
                PokemonSeedEntry.pokemon(612, "Haxorus", PokemonType.DRAGON, null, 5, PokedexColor.YELLOW, 1.8, 105.5, EvolutionStage.SECOND_STAGE, null, 324),
                PokemonSeedEntry.pokemon(613, "Cubchoo", PokemonType.ICE, null, 5, PokedexColor.WHITE, 0.5, 8.5, EvolutionStage.BASE, 37, 325),
                PokemonSeedEntry.pokemon(614, "Beartic", PokemonType.ICE, null, 5, PokedexColor.WHITE, 2.6, 260.0, EvolutionStage.SECOND_STAGE, null, 325),
                PokemonSeedEntry.pokemon(615, "Cryogonal", PokemonType.ICE, null, 5, PokedexColor.BLUE, 1.1, 148.0, null, null, 326),
                PokemonSeedEntry.pokemon(616, "Shelmet", PokemonType.BUG, null, 5, PokedexColor.RED, 0.4, 7.7, EvolutionStage.BASE, null, 327),
                PokemonSeedEntry.pokemon(617, "Accelgor", PokemonType.BUG, null, 5, PokedexColor.RED, 0.8, 25.3, EvolutionStage.SECOND_STAGE, null, 327),
                PokemonSeedEntry.pokemon(618, "Stunfisk", PokemonType.GROUND, PokemonType.ELECTRIC, 5, PokedexColor.BROWN, 0.7, 11.0, null, null, 328),
                PokemonSeedEntry.pokemon(619, "Mienfoo", PokemonType.FIGHTING, null, 5, PokedexColor.YELLOW, 0.9, 20.0, EvolutionStage.BASE, 50, 329),
                PokemonSeedEntry.pokemon(620, "Mienshao", PokemonType.FIGHTING, null, 5, PokedexColor.PURPLE, 1.4, 35.5, EvolutionStage.SECOND_STAGE, null, 329),
                PokemonSeedEntry.pokemon(621, "Druddigon", PokemonType.DRAGON, null, 5, PokedexColor.RED, 1.6, 139.0, null, null, 330),
                PokemonSeedEntry.pokemon(622, "Golett", PokemonType.GROUND, PokemonType.GHOST, 5, PokedexColor.GREEN, 1.0, 92.0, EvolutionStage.BASE, 43, 331),
                PokemonSeedEntry.pokemon(623, "Golurk", PokemonType.GROUND, PokemonType.GHOST, 5, PokedexColor.GREEN, 2.8, 330.0, EvolutionStage.SECOND_STAGE, null, 331),
                PokemonSeedEntry.pokemon(624, "Pawniard", PokemonType.DARK, PokemonType.STEEL, 5, PokedexColor.RED, 0.5, 10.2, EvolutionStage.BASE, 52, 332),
                PokemonSeedEntry.pokemon(625, "Bisharp", PokemonType.DARK, PokemonType.STEEL, 5, PokedexColor.RED, 1.6, 70.0, EvolutionStage.FIRST_STAGE, null, 332),
                PokemonSeedEntry.pokemon(626, "Bouffalant", PokemonType.NORMAL, null, 5, PokedexColor.BROWN, 1.6, 94.6, null, null, 333),
                PokemonSeedEntry.pokemon(627, "Rufflet", PokemonType.NORMAL, PokemonType.FLYING, 5, PokedexColor.WHITE, 0.5, 10.5, EvolutionStage.BASE, 54, 334),
                PokemonSeedEntry.pokemon(628, "Braviary", PokemonType.NORMAL, PokemonType.FLYING, 5, PokedexColor.RED, 1.5, 41.0, EvolutionStage.SECOND_STAGE, null, 334),
                PokemonSeedEntry.pokemon(629, "Vullaby", PokemonType.DARK, PokemonType.FLYING, 5, PokedexColor.BROWN, 0.5, 9.0, EvolutionStage.BASE, 54, 335),
                PokemonSeedEntry.pokemon(630, "Mandibuzz", PokemonType.DARK, PokemonType.FLYING, 5, PokedexColor.BROWN, 1.2, 39.5, EvolutionStage.SECOND_STAGE, null, 335),
                PokemonSeedEntry.pokemon(631, "Heatmor", PokemonType.FIRE, null, 5, PokedexColor.RED, 1.4, 58.0, null, null, 336),
                PokemonSeedEntry.pokemon(632, "Durant", PokemonType.BUG, PokemonType.STEEL, 5, PokedexColor.GRAY, 0.3, 33.0, null, null, 337),
                PokemonSeedEntry.pokemon(633, "Deino", PokemonType.DARK, PokemonType.DRAGON, 5, PokedexColor.BLUE, 0.8, 17.3, EvolutionStage.BASE, 50, 338),
                PokemonSeedEntry.pokemon(634, "Zweilous", PokemonType.DARK, PokemonType.DRAGON, 5, PokedexColor.BLUE, 1.4, 50.0, EvolutionStage.FIRST_STAGE, 64, 338),
                PokemonSeedEntry.pokemon(635, "Hydreigon", PokemonType.DARK, PokemonType.DRAGON, 5, PokedexColor.BLUE, 1.8, 160.0, EvolutionStage.SECOND_STAGE, null, 338),
                PokemonSeedEntry.pokemon(636, "Larvesta", PokemonType.BUG, PokemonType.FIRE, 5, PokedexColor.WHITE, 1.1, 28.8, EvolutionStage.BASE, 59, 339),
                PokemonSeedEntry.pokemon(637, "Volcarona", PokemonType.BUG, PokemonType.FIRE, 5, PokedexColor.WHITE, 1.6, 46.0, EvolutionStage.SECOND_STAGE, null, 339),
                PokemonSeedEntry.pokemon(638, "Cobalion", PokemonType.STEEL, PokemonType.FIGHTING, 5, PokedexColor.BLUE, 2.1, 250.0, null, null, 340),
                PokemonSeedEntry.pokemon(639, "Terrakion", PokemonType.ROCK, PokemonType.FIGHTING, 5, PokedexColor.GRAY, 1.9, 260.0, null, null, 341),
                PokemonSeedEntry.pokemon(640, "Virizion", PokemonType.GRASS, PokemonType.FIGHTING, 5, PokedexColor.GREEN, 2.0, 200.0, null, null, 342),
                PokemonSeedEntry.pokemon(641, "Tornadus", PokemonType.FLYING, null, 5, PokedexColor.GREEN, 1.5, 63.0, null, null, 343),
                PokemonSeedEntry.pokemon(642, "Thundurus", PokemonType.ELECTRIC, PokemonType.FLYING, 5, PokedexColor.BLUE, 1.5, 61.0, null, null, 344),
                PokemonSeedEntry.pokemon(643, "Reshiram", PokemonType.DRAGON, PokemonType.FIRE, 5, PokedexColor.WHITE, 3.2, 330.0, null, null, 345),
                PokemonSeedEntry.pokemon(644, "Zekrom", PokemonType.DRAGON, PokemonType.ELECTRIC, 5, PokedexColor.BLACK, 2.9, 345.0, null, null, 346),
                PokemonSeedEntry.pokemon(645, "Landorus", PokemonType.GROUND, PokemonType.FLYING, 5, PokedexColor.BROWN, 1.5, 68.0, null, null, 347),
                PokemonSeedEntry.pokemon(646, "Kyurem", PokemonType.DRAGON, PokemonType.ICE, 5, PokedexColor.GRAY, 3.0, 325.0, null, null, 348),
                PokemonSeedEntry.pokemon(647, "Keldeo", PokemonType.WATER, PokemonType.FIGHTING, 5, PokedexColor.YELLOW, 1.4, 48.5, null, null, 349),
                PokemonSeedEntry.pokemon(648, "Meloetta", PokemonType.NORMAL, PokemonType.PSYCHIC, 5, PokedexColor.WHITE, 0.6, 6.5, null, null, 350),
                PokemonSeedEntry.pokemon(649, "Genesect", PokemonType.BUG, PokemonType.STEEL, 5, PokedexColor.PURPLE, 1.5, 82.5, null, null, 351)
        );
    }
}
